# New questions for Reviews (4 MC + 2 gap per unit) and Progress Tests (30 MC each).
# They are not used anywhere else, so a review is fresh practice. build.py rejects duplicates of unit items.

REVIEWS = {
1: {"mc": [
  ("There ___ three bedrooms in our flat.", ["are", "is", "be"]),
  ("My uncle ___ in a bank.", ["works", "work", "working"]),
  ("___ very windy outside today.", ["It's", "There's", "Its"]),
  ("___ your brother play the piano?", ["Does", "Do", "Is"]),
  ("Be quiet! Grandpa ___ a nap.", ["is having", "has", "have"]),
  ("I ___ what you're saying.", ["don't understand", "am not understanding", "not understand"]),
  ("Why ___ you wearing a coat? It's hot!", ["are", "do", "is"]),
  ("This car ___ to my uncle.", ["belongs", "is belonging", "belong"]),
  ("My aunt's husband is my ___.", ["uncle", "nephew", "grandfather"]),
  ("Your parents' parents are your ___.", ["grandparents", "cousins", "nephews"]),
  ("Babysitters ___ children when parents go out.", ["look after", "look like", "grow up"]),
  ("My sister is ___ to a doctor.", ["married", "single", "twin"]),
 ], "gap": [
  ("My mum ___ (teach) maths at a school.", ["teaches"]),
  ("___ there a supermarket near your house?", ["Is"]),
  ("Look! Those boys ___ (run) to the bus.", ["are running", "'re running"]),
  ("I ___ (not wear) a jacket today because it's warm.", ["am not wearing", "'m not wearing"]),
  ("My sister's daughter is my ___.", ["niece"]),
  ("I ___ up in a small village, but now I live in the city.", ["grew"]),
 ]},
2: {"mc": [
  ("She ___ her grandparents last weekend.", ["visited", "visit", "visitted"]),
  ("We didn't ___ the film. It was boring.", ["enjoy", "enjoyed", "enjoying"]),
  ("The baby ___ all night.", ["cried", "cryed", "cry"]),
  ("I ___ in Bukhara when I was a child.", ["lived", "live", "living"]),
  ("We ___ very happy yesterday.", ["were", "was", "did"]),
  ("He ___ a letter to his friend.", ["wrote", "writed", "write"]),
  ("I ___ my homework at nine o'clock.", ["did", "done", "do"]),
  ("___ you at school on Monday?", ["Were", "Was", "Did"]),
  ("My sister ___ gymnastics after school.", ["does", "plays", "goes"]),
  ("Let's ___ fishing on Sunday.", ["go", "do", "play"]),
  ("He's very good ___ playing the guitar.", ["at", "in", "on"]),
  ("I love ___ comics in my free time.", ["reading", "doing", "going"]),
 ], "gap": [
  ("They ___ (plan) a party for their teacher.", ["planned"]),
  ("We ___ (not / watch) the news last night.", ["didn't watch", "did not watch"]),
  ("She ___ (buy) a present for her mum.", ["bought"]),
  ("The shop ___ (not be) open on Sunday.", ["wasn't", "was not"]),
  ("My brother ___ (collect) old coins. He has 300!", ["collects"]),
  ("I'm interested ___ photography.", ["in"]),
 ]},
3: {"mc": [
  ("I ___ a bath when the phone rang.", ["was having", "had", "have"]),
  ("While we ___ dinner, the lights went out.", ["were having", "had", "was having"]),
  ("What ___ he doing at 10 pm?", ["was", "were", "did"]),
  ("She ___ her keys while she was running.", ["dropped", "was dropping", "drops"]),
  ("___ late for school!", ["Don't be", "Not be", "No be"]),
  ("I hope ___ you soon.", ["to see", "seeing", "see"]),
  ("He finished ___ his room at six.", ["tidying", "to tidy", "tidy"]),
  ("I remember ___ that film as a child.", ["watching", "to watching", "watch"]),
  ("The ___ gave the player a yellow card.", ["referee", "coach", "fan"]),
  ("Our team ___ the cup last year.", ["won", "beat", "scored"]),
  ("Basketball is played on a ___.", ["court", "pitch", "pool"]),
  ("She ___ the 400-metre race.", ["won", "beat", "scored"]),
 ], "gap": [
  ("It ___ (rain) when we left the cinema.", ["was raining"]),
  ("They were playing cards ___ the teacher came in.", ["when"]),
  ("She decided ___ (learn) Chinese.", ["to learn"]),
  ("Do you enjoy ___ (dance)?", ["dancing"]),
  ("Thousands of ___ watched the match at the stadium.", ["fans", "people"]),
  ("He ___ three goals in one match!", ["scored"]),
 ]},
4: {"mc": [
  ("I've ___ finished my essay. Here it is!", ["just", "yet", "ever"]),
  ("Have you ___ your homework yet?", ["done", "did", "do"]),
  ("She ___ never tried Korean food.", ["has", "have", "is"]),
  ("We haven't met the new teacher ___.", ["yet", "already", "just"]),
  ("I've known Aziz ___ we were five.", ["since", "for", "ago"]),
  ("She ___ to London in 2019.", ["went", "has gone", "has been"]),
  ("They have been married ___ twenty years.", ["for", "since", "ago"]),
  ("___ have you lived in this flat?", ["How long", "When", "How often"]),
  ("You can find lots of books in the school ___.", ["library", "canteen", "lab"]),
  ("If you don't study, you might ___ the exam.", ["fail", "pass", "revise"]),
  ("Our school ___ is blue and white.", ["uniform", "timetable", "term"]),
  ("Children start ___ school at the age of six or seven.", ["primary", "secondary", "high"]),
 ], "gap": [
  ("They ___ (already / eat) lunch.", ["have already eaten", "'ve already eaten"]),
  ("Have you ever ___ (see) a real snake?", ["seen"]),
  ("I ___ (buy) this bike two years ago.", ["bought"]),
  ("He has worked here ___ 2020.", ["since"]),
  ("We eat lunch in the school ___ at one o'clock.", ["canteen"]),
  ("I have to ___ for my history test tonight.", ["revise", "study"]),
 ]},
5: {"mc": [
  ("I'm hungry. I think I ___ make a sandwich.", ["'ll", "'m going", "am"]),
  ("Look at that car! It ___ crash!", ["is going to", "will to", "going"]),
  ("They've bought tickets. They ___ travel to Paris.", ["are going to", "will to", "go to"]),
  ("I promise I ___ forget your birthday.", ["won't", "don't", "am not"]),
  ("Is this pen ___? — Yes, it's mine.", ["yours", "your", "you"]),
  ("___ car is red. Hers is blue.", ["My", "Mine", "Me"]),
  ("The children painted the room ___.", ["themselves", "them", "their"]),
  ("That's ___ house. They live there.", ["their", "there", "they're"]),
  ("A ___ helps doctors at a hospital.", ["nurse", "mechanic", "chef"]),
  ("He sent his ___ to ten companies.", ["CV", "salary", "boss"]),
  ("How much do nurses ___ in your country?", ["earn", "win", "pay"]),
  ("She works at a desk in an ___.", ["office", "factory", "farm"]),
 ], "gap": [
  ("It's cold. I ___ (close) the window.", ["'ll close", "will close"]),
  ("We ___ (visit) Khiva next month. We've planned it.", ["are going to visit", "'re going to visit", "are visiting", "'re visiting"]),
  ("I can't find my keys. Can you help ___?", ["me"]),
  ("This is my sister and that is ___ husband.", ["her"]),
  ("He lost his job last year and he's ___ now.", ["unemployed"]),
  ("She has ten years of ___ as a teacher.", ["experience"]),
 ]},
6: {"mc": [
  ("The concert ___ at 8 pm.", ["starts", "is start", "starting"]),
  ("I ___ my aunt this evening. We arranged it last week.", ["am seeing", "see", "sees"]),
  ("When ___ the next train leave?", ["does", "is", "do"]),
  ("___ you doing anything on Saturday?", ["Are", "Do", "Will"]),
  ("You ___ talk during the exam.", ["mustn't", "don't have to", "needn't to"]),
  ("___ you help me carry this box?", ["Could", "Should", "Must"]),
  ("You ___ eat more vegetables. They're good for you.", ["should", "shouldn't", "mustn't"]),
  ("I ___ ride a bike when I was four.", ["could", "can", "must"]),
  ("You can buy bread at the ___.", ["bakery", "chemist's", "bank"]),
  ("Can I pay ___ cash?", ["in", "by", "on"]),
  ("There's a long ___ at the checkout.", ["queue", "sale", "bargain"]),
  ("Everything is half price today. There's a big ___.", ["sale", "queue", "change"]),
 ], "gap": [
  ("The museum ___ (close) at 6 pm today.", ["closes"]),
  ("We ___ (have) a party on Friday. Can you come?", ["are having", "'re having"]),
  ("It's Sunday. You ___ get up early. (not necessary)", ["don't have to", "do not have to"]),
  ("You look ill. You ___ go home. (advice)", ["should"]),
  ("Here's your ___ — 5,000 som.", ["change"]),
  ("I ___ too much money on clothes last month.", ["spent"]),
 ]},
7: {"mc": [
  ("This house ___ in 1950.", ["was built", "built", "is build"]),
  ("Cars ___ in this factory.", ["are made", "make", "is made"]),
  ("The telephone ___ by Alexander Graham Bell.", ["was invented", "invented", "is invent"]),
  ("A lot of cotton ___ in Uzbekistan.", ["is grown", "grows up", "is grow"]),
  ("I'd like ___ apple, please.", ["an", "a", "the"]),
  ("___ Earth goes around the Sun.", ["The", "A", "An"]),
  ("She plays ___ violin.", ["the", "a", "an"]),
  ("We have ___ dinner at seven.", ["no article", "the", "a"]),
  ("People give each other ___ on birthdays.", ["presents", "guests", "parades"]),
  ("The man who is getting married is the ___.", ["groom", "bride", "guest"]),
  ("On New Year's Eve we watch ___ in the sky.", ["fireworks", "costumes", "parades"]),
  ("We ___ our house with lights for the festival.", ["decorate", "celebrate", "invite"]),
 ], "gap": [
  ("The letter ___ (send) yesterday.", ["was sent"]),
  ("English ___ (speak) in many countries.", ["is spoken"]),
  ("He's ___ honest man.", ["an"]),
  ("___ Nile is a very long river.", ["The"]),
  ("How do you ___ your birthday?", ["celebrate"]),
  ("We sent ___ to 200 people for the wedding.", ["invitations"]),
 ]},
8: {"mc": [
  ("There ___ some milk in the fridge.", ["is", "are", "be"]),
  ("Can I have some ___ about the trip?", ["information", "informations", "an information"]),
  ("Are there ___ apples left?", ["any", "some", "a"]),
  ("My glasses ___ broken.", ["are", "is", "was"]),
  ("How ___ tea do you drink a day?", ["much", "many", "a few"]),
  ("I've got ___ friends in London — just two.", ["a few", "a little", "much"]),
  ("There isn't ___ time left.", ["much", "many", "a few"]),
  ("We need ___ salt for the soup — just a bit.", ["a little", "a few", "many"]),
  ("These jeans are too ___. I need a smaller size.", ["loose", "tight", "short"]),
  ("Your shoes ___ your bag perfectly!", ["match", "fit", "wear"]),
  ("She reads magazines about ___ and style.", ["fashion", "fashionable", "designer"]),
  ("Can I ___ this dress in the changing room?", ["try on", "wear on", "put in"]),
 ], "gap": [
  ("Would you like ___ coffee?", ["some"]),
  ("We haven't got ___ bread.", ["any"]),
  ("How ___ students are there in your class?", ["many"]),
  ("There's too ___ noise in here!", ["much"]),
  ("It's cold. Put ___ your gloves.", ["on"]),
  ("A famous fashion ___ made this dress.", ["designer"]),
 ]},
9: {"mc": [
  ("Planes are ___ than trains.", ["faster", "fast", "more fast"]),
  ("My sister is ___ than me.", ["younger", "more young", "youngest"]),
  ("Is maths ___ than science?", ["more difficult", "difficulter", "most difficult"]),
  ("This film isn't as good ___ the book.", ["as", "than", "like"]),
  ("It's the ___ building in the city.", ["tallest", "taller", "most tall"]),
  ("He's the ___ runner in our school.", ["fastest", "faster", "most fast"]),
  ("That was the ___ meal I've ever had!", ["best", "better", "goodest"]),
  ("July is the ___ month of the year here.", ["hottest", "hotest", "most hot"]),
  ("You can watch a play at the ___.", ["theatre", "bank", "library"]),
  ("If someone steals your car, go to the ___.", ["police station", "post office", "museum"]),
  ("We bought fruit and vegetables at the ___.", ["market", "library", "bank"]),
  ("The ___ goes over the river.", ["bridge", "square", "park"]),
 ], "gap": [
  ("My bag is ___ (heavy) than yours.", ["heavier"]),
  ("A mouse is ___ (small) than a cat.", ["smaller"]),
  ("This is the ___ (interesting) book I've ever read.", ["most interesting"]),
  ("Who is the ___ (old) person in your family?", ["oldest", "eldest"]),
  ("I need to change money. Where's the ___?", ["bank"]),
  ("Trains to Tashkent leave from the railway ___.", ["station"]),
 ]},
10: {"mc": [
  ("She sings ___.", ["beautifully", "beautiful", "beautifuly"]),
  ("He works very ___.", ["hard", "hardly", "hardy"]),
  ("She answered all the questions ___.", ["correctly", "correct", "corrected"]),
  ("Our team played ___ yesterday and lost 5–0.", ["badly", "bad", "worse"]),
  ("My birthday is ___ June.", ["in", "on", "at"]),
  ("The cat jumped ___ the wall.", ["over", "along", "at"]),
  ("We walked ___ the river for an hour.", ["along", "into", "at"]),
  ("I'll meet you ___ noon.", ["at", "in", "on"]),
  ("Our flight was ___ for three hours because of the snow.", ["delayed", "booked", "missed"]),
  ("How heavy is your ___? — Twenty kilos.", ["luggage", "ticket", "journey"]),
  ("We got ___ the bus at the museum.", ["off", "out", "down"]),
  ("She goes to work ___ train.", ["by", "on", "with"]),
 ], "gap": [
  ("quick → ___", ["quickly"]),
  ("happy → ___", ["happily"]),
  ("She came ___ the room and sat down.", ["into", "in"]),
  ("See you ___ Monday!", ["on"]),
  ("Hurry up! We'll ___ the train!", ["miss"]),
  ("We went ___ in Bukhara and saw many old buildings.", ["sightseeing"]),
 ]},
11: {"mc": [
  ("If it ___ sunny tomorrow, we'll go to the lake.", ["is", "will be", "was"]),
  ("If you eat too much, you ___ feel sick.", ["will", "would", "are"]),
  ("___ you leave now, you'll be late.", ["Unless", "If", "When"]),
  ("If you freeze water, it ___ ice.", ["becomes", "will became", "became"]),
  ("If I ___ a car, I'd drive to school.", ["had", "have", "will have"]),
  ("What would you do if you ___ a million dollars?", ["won", "win", "will win"]),
  ("If I were you, I ___ buy it.", ["wouldn't", "won't", "don't"]),
  ("If she ___ more time, she would learn Spanish.", ["had", "has", "would have"]),
  ("I go to the ___ to lift weights.", ["gym", "pharmacy", "dentist"]),
  ("He wants to ___ weight, so he's eating less.", ["lose", "win", "miss"]),
  ("Running every day helps you keep ___.", ["fit", "fat", "ill"]),
  ("You should drink a lot of water and eat a healthy ___.", ["diet", "gym", "medicine"]),
 ], "gap": [
  ("If you ___ (study), you'll pass the test.", ["study"]),
  ("We ___ (not / go) out if it rains.", ["won't go", "will not go"]),
  ("If I ___ (be) you, I would call her.", ["were", "was"]),
  ("She ___ (buy) a house if she had the money.", ["would buy", "'d buy"]),
  ("I've got a terrible ___. My head hurts.", ["headache"]),
  ("Doctors say we should do some ___ every day.", ["exercise", "sport"]),
 ]},
12: {"mc": [
  ("It was ___ hot day that we stayed inside.", ["such a", "so", "such"]),
  ("The coffee was ___ hot that I couldn't drink it.", ["so", "such", "such a"]),
  ("\"I'm hungry.\" \"So ___ I.\"", ["am", "do", "have"]),
  ("\"I don't like tea.\" \"Neither ___ I.\"", ["do", "am", "like"]),
  ("She's a doctor, ___?", ["isn't she", "is she", "doesn't she"]),
  ("You didn't call me, ___?", ["did you", "didn't you", "do you"]),
  ("They can speak English, ___?", ["can't they", "can they", "don't they"]),
  ("He won't be late, ___?", ["will he", "won't he", "does he"]),
  ("I need to ___ my phone. The battery is low.", ["charge", "download", "share"]),
  ("Type your ___ to log in.", ["password", "keyboard", "charger"]),
  ("She ___ a video to YouTube yesterday.", ["uploaded", "downloaded", "searched"]),
  ("I use an ___ on my phone to learn new words.", ["app", "screen", "battery"]),
 ], "gap": [
  ("\"I can't ride a horse.\" \"___ can I.\"", ["Neither", "Nor"]),
  ("She's ___ a kind person!", ["such"]),
  ("It's cold today, ___ it?", ["isn't"]),
  ("You haven't seen my keys, ___ you?", ["have"]),
  ("I'll ___ you the photos by email.", ["send"]),
  ("My laptop ___ is broken, so I can't see anything.", ["screen"]),
 ]},
13: {"mc": [
  ("The woman ___ lives upstairs is a teacher.", ["who", "which", "where"]),
  ("This is the shop ___ I bought my shoes.", ["where", "which", "who"]),
  ("The book ___ you gave me is great.", ["that", "who", "where"]),
  ("That's the girl ___ bag was stolen.", ["whose", "who", "which"]),
  ("She was sad because she ___ her cat.", ["had lost", "has lost", "loses"]),
  ("I didn't recognise him because he ___ a beard.", ["had grown", "has grown", "grows"]),
  ("___ you finished your homework before dinner?", ["Had", "Have", "Did"]),
  ("They were hungry because they ___ eaten anything.", ["hadn't", "haven't", "didn't"]),
  ("It's ___ today. Take your sunglasses.", ["sunny", "snowy", "foggy"]),
  ("Many trees grow in a ___.", ["forest", "desert", "field"]),
  ("The ___ says it will rain tomorrow.", ["forecast", "weather", "climate"]),
  ("A ___ is smaller than a mountain.", ["hill", "lake", "island"]),
 ], "gap": [
  ("This is the town ___ I was born.", ["where"]),
  ("The man ___ helped me was very kind.", ["who", "that"]),
  ("When I got to the station, the train ___ (leave).", ["had left", "'d left"]),
  ("She ___ (never / see) the sea before that trip.", ["had never seen", "'d never seen"]),
  ("It's minus ten degrees. It's ___!", ["freezing"]),
  ("There was a big ___ last night with thunder and lightning.", ["storm"]),
 ]},
14: {"mc": [
  ("He ___ that he was hungry.", ["said", "told", "talked"]),
  ("\"I'm busy.\" → She said she ___ busy.", ["was", "is", "be"]),
  ("\"I can help.\" → He said he ___ help.", ["could", "can", "will"]),
  ("\"We will come.\" → They said they ___ come.", ["would", "will", "can"]),
  ("I ___ TV every evening.", ["watch", "am watching", "watched"]),
  ("She ___ in Tashkent since 2015.", ["has lived", "lived", "lives"]),
  ("While I ___, it started to rain.", ["was walking", "walked", "am walking"]),
  ("Next year I ___ study at university. I've decided.", ["am going to", "will to", "go to"]),
  ("Please put your ___ in the bin.", ["rubbish", "environment", "pollution"]),
  ("Many people have no money and live in ___.", ["poverty", "pollution", "disease"]),
  ("We should ___ paper and plastic.", ["recycle", "pollute", "waste"]),
  ("The ___ destroyed many houses. The ground was shaking.", ["earthquake", "drought", "flood"]),
 ], "gap": [
  ("\"I like pizza.\" → He said he ___ pizza.", ["liked"]),
  ("She ___ us a story about her trip.", ["told"]),
  ("Right now I ___ (read) a great book.", ["am reading", "'m reading"]),
  ("Last year we ___ (visit) our cousins in Kazakhstan.", ["visited"]),
  ("Turn off the lights to save ___.", ["energy", "electricity"]),
  ("We must ___ endangered animals.", ["protect", "save"]),
 ]},
}

PROGRESS = {
1: [
  ("My sister ___ her teeth twice a day.", ["brushes", "brush", "brushing"]),
  ("There ___ a lot of people at the market today.", ["are", "is", "be"]),
  ("Shh! I ___ to the radio.", ["'m listening", "listen", "listens"]),
  ("He ___ a new car. He bought it last month.", ["has", "is having", "have"]),
  ("My mother's brother is my ___.", ["uncle", "cousin", "nephew"]),
  ("We ___ the museum yesterday.", ["visited", "visit", "have visit"]),
  ("I ___ to the dentist last week.", ["went", "go", "gone"]),
  ("___ the weather nice in Samarkand?", ["Was", "Were", "Did"]),
  ("My brother ___ karate twice a week.", ["does", "plays", "goes"]),
  ("She ___ dinner when I called her.", ["was cooking", "cooked", "cooks"]),
  ("I don't mind ___ early.", ["getting up", "to get up", "get up"]),
  ("Please ___ the door. It's cold.", ["close", "to close", "closing"]),
  ("Our team ___ the final 3–0!", ["won", "beat", "scored"]),
  ("I've ___ been to India.", ["never", "ever", "yet"]),
  ("Have you finished ___?", ["yet", "already", "since"]),
  ("They've lived here ___ 2010.", ["since", "for", "ago"]),
  ("I ___ him two days ago.", ["met", "have met", "meet"]),
  ("We have a 15-minute ___ between lessons.", ["break", "term", "mark"]),
  ("I think it ___ snow tonight.", ["will", "is", "going"]),
  ("Is this Ali's pen? — Yes, it's ___.", ["his", "him", "he"]),
  ("She'd like to ___ for a job at the hotel.", ["apply", "earn", "retire"]),
  ("The film ___ at 7:30 tonight.", ["starts", "is start", "will starting"]),
  ("We ___ our grandparents on Sunday. It's arranged.", ["are visiting", "visits", "visited"]),
  ("You ___ run near the swimming pool. It's dangerous.", ["mustn't", "don't have to", "can"]),
  ("___ I use your phone, please?", ["Can", "Must", "Should"]),
  ("How much ___ this T-shirt cost?", ["does", "do", "is"]),
  ("This bridge ___ 100 years ago.", ["was built", "built", "is built"]),
  ("Rice ___ in many countries in Asia.", ["is eaten", "eats", "is eat"]),
  ("She is ___ best singer in our school.", ["the", "a", "an"]),
  ("We ___ New Year with fireworks.", ["celebrate", "decorate", "invite"]),
],
2: [
  ("There isn't ___ juice in the bottle.", ["any", "some", "many"]),
  ("The news ___ very bad today.", ["is", "are", "were"]),
  ("How ___ money did you spend?", ["much", "many", "few"]),
  ("I have ___ questions for you — just two or three.", ["a few", "a little", "much"]),
  ("These shoes don't ___ me. They're too small.", ["fit", "suit", "match"]),
  ("Many diseases come from dirty ___.", ["water", "energy", "poverty"]),
  ("A bus is ___ than a bike.", ["bigger", "biger", "more big"]),
  ("My room isn't as big ___ yours.", ["as", "than", "that"]),
  ("It's the ___ city I've ever visited.", ["most beautiful", "beautifulest", "more beautiful"]),
  ("He's the ___ player in the team.", ["worst", "baddest", "worse"]),
  ("I borrowed three books from the ___.", ["library", "bank", "bakery"]),
  ("She drives very ___.", ["carefully", "careful", "carefuly"]),
  ("He did ___ in the test than last time.", ["better", "gooder", "best"]),
  ("The shop is ___ the bank and the café.", ["between", "opposite of", "next"]),
  ("I was born ___ 12th May.", ["on", "in", "at"]),
  ("There was a two-hour ___, so we waited at the airport.", ["delay", "journey", "trip"]),
  ("If you don't hurry, you ___ the bus.", ["'ll miss", "miss", "missed"]),
  ("I won't go ___ you come with me.", ["unless", "if", "when"]),
  ("If I ___ rich, I would travel the world.", ["were", "am", "will be"]),
  ("What ___ you do if you lost your phone?", ["would", "will", "did"]),
  ("You should go to the ___ if your tooth hurts.", ["dentist", "gym", "baker's"]),
  ("It was ___ a good film that I watched it twice.", ["such", "so", "such an"]),
  ("\"I didn't sleep well.\" \"Neither ___ I.\"", ["did", "do", "was"]),
  ("You like football, ___?", ["don't you", "do you", "aren't you"]),
  ("I'll ___ the photos on Instagram.", ["post", "charge", "type"]),
  ("The girl ___ won the competition is my cousin.", ["who", "which", "where"]),
  ("When I arrived, everyone ___ home.", ["had gone", "has gone", "goes"]),
  ("It's very ___ — I can't see the road.", ["foggy", "sunny", "windy"]),
  ("\"I'm tired.\" → He said he ___ tired.", ["was", "is", "were"]),
  ("We ___ each other since we were children.", ["have known", "know", "knew"]),
],
}
