# Units 15-28. Same format as units_a.py.

UNITS_B = [
{
 "n": 15, "title": "Work",
 "words": [
  ("job", "ish, kasb", "What's your mum's job?"),
  ("boss", "rahbar, xo'jayin", "My boss is very kind."),
  ("colleague", "hamkasb", "My colleagues are friendly."),
  ("salary", "maosh", "Doctors get a good salary."),
  ("earn", "(pul) topmoq", "How much does a pilot earn?"),
  ("apply for", "... ga ariza topshirmoq", "He applied for a job at the bank."),
  ("CV", "rezyume", "Send your CV by email."),
  ("interview", "suhbat (ishga qabul)", "I've got a job interview tomorrow."),
  ("experience", "tajriba", "She has five years of experience."),
  ("full-time / part-time", "to'liq / yarim stavka", "She has a part-time job."),
  ("office / factory", "ofis / zavod", "Cars are made in a factory."),
  ("unemployed", "ishsiz", "He lost his job and is unemployed now."),
  ("retire", "nafaqaga chiqmoq", "My grandfather retired at 60."),
  ("nurse / chef / mechanic", "hamshira / oshpaz / mexanik", "A mechanic repairs cars."),
 ],
 "tip": "apply for a job · have / go to an interview · earn money · work full-time / part-time · work in an office / for a company.",
 "ex": [
  ("Choose the correct word.", "mc", [
   ("The money you get for your job is your ___.", ["salary", "bill", "price"]),
   ("A person you work with is a ___.", ["colleague", "boss", "customer"]),
   ("You ___ for a job by sending a CV.", ["apply", "retire", "revise"]),
   ("When people get old, they stop working: they ___.", ["retire", "apply", "fail"]),
   ("You go to a job ___ to meet the boss and answer questions.", ["interview", "meeting", "office"]),
   ("People who have no job are ___.", ["unemployed", "employed", "retired"]),
  ]),
  ("Complete with a word from the box.", "gap", [
   ("She works ___, only four hours a day.", ["part-time"]),
   ("How much do you ___ a month?", ["earn"]),
   ("My dad works in an ___ in the city centre.", ["office"]),
   ("I have three years of ___ as a waiter.", ["experience"]),
   ("My ___ are very friendly. We often have lunch together.", ["colleagues"]),
   ("Teachers want a higher ___.", ["salary"]),
  ], ["part-time", "earn", "office", "experience", "colleagues", "salary"]),
  ("What's the job?", "gap", [
   ("This person teaches students: a ___", ["teacher"]),
   ("This person drives a bus: a bus ___", ["driver"]),
   ("This person helps doctors in a hospital: a ___", ["nurse"]),
   ("This person cooks in a restaurant: a ___", ["chef", "cook"]),
   ("This person repairs cars: a ___", ["mechanic"]),
   ("This person designs buildings: an ___", ["architect"]),
  ]),
 ],
 "test": [
  ("My ___ is very kind; she's the manager.", ["boss", "classmate", "customer"]),
  ("A ___ job is about 40 hours a week.", ["full-time", "part-time", "half"]),
  ("She wants to ___ for a job at the bank.", ["apply", "work", "ask"]),
  ("My grandfather ___ when he was 60.", ["retired", "failed", "applied"]),
  ("A ___ helps sick people in hospital.", ["nurse", "chef", "mechanic"]),
  ("I have a job ___ tomorrow. I'm nervous!", ["interview", "colleague", "salary"]),
  ("Footballers ___ a lot of money.", ["earn", "win", "pay"]),
  ("Send your ___ to the company by email.", ["CV", "salary", "boss"]),
  ("Cars are made in a ___.", ["factory", "office", "farm"]),
  ("He lost his job, so now he's ___.", ["unemployed", "retired", "employed"]),
 ],
 "task": "Write about the job you want in the future (8–10 sentences). What does the person do? Where do they work? Why do you want this job?",
},
{
 "n": 16, "title": "Present simple and present continuous to talk about the future",
 "lesson": [
  ("Present continuous for arrangements", [
   "Use it for fixed plans with a time and place (often with other people): I<b>'m meeting</b> Aziz at 6 tomorrow.",
   "What <b>are</b> you <b>doing</b> this weekend? — We<b>'re visiting</b> my grandparents.",
   "UZ: Aniq kelishilgan, rejalashtirilgan uchrashuv va tadbirlar uchun."]),
  ("Present simple for timetables", [
   "Use it for timetables and schedules (trains, buses, films, lessons, shops): The train <b>leaves</b> at 7:30. The film <b>starts</b> at 8.",
   "When <b>does</b> the plane <b>land</b>? · The shop <b>doesn't close</b> until 10 pm.",
   "UZ: Jadval bo'yicha bo'ladigan narsalar (poyezd, dars, kino) uchun present simple."]),
  ("Compare", [
   "Arrangement: I<b>'m flying</b> to Istanbul on Friday (I've got a ticket).",
   "Timetable: My flight <b>leaves</b> at 6 am.",
   "Plan / intention: I<b>'m going to</b> learn Turkish. · Instant decision: OK, I<b>'ll</b> come with you."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("I ___ Dilnoza at 6 tomorrow. It's in my diary.", ["am meeting", "meet", "meets"]),
   ("The train ___ at 7:30 tomorrow morning.", ["leaves", "is leave", "leaving"]),
   ("What ___ you doing this weekend?", ["are", "do", "will"]),
   ("According to the timetable, the bus ___ at 9:15.", ["leaves", "leave", "left"]),
   ("We ___ to Istanbul on Friday. We've got the tickets.", ["are flying", "flies", "flew"]),
   ("My sister ___ married next month.", ["is getting", "get", "got"]),
  ]),
  ("Put the verb in brackets in the present simple or present continuous.", "gap", [
   ("I ___ (see) the dentist at 4 o'clock tomorrow.", ["am seeing", "'m seeing"]),
   ("The museum ___ (open) at 10 am on Sundays.", ["opens"]),
   ("___ (you / come) to my party on Saturday?", ["Are you coming"]),
   ("Our English lesson ___ (start) at 9:00 tomorrow.", ["starts"]),
   ("They ___ (not / go) out tonight. They're too tired.", ["aren't going", "are not going"]),
   ("What time ___ (the plane / land)?", ["does the plane land"]),
  ]),
  ("Timetable or arrangement? Put the verb in the correct form.", "gap", [
   ("My flight ___ (arrive) at 11:45 pm.", ["arrives"]),
   ("I ___ (have) lunch with my aunt tomorrow.", ["am having", "'m having"]),
   ("The shop ___ (close) at 9 pm today.", ["closes"]),
   ("We ___ (play) football after school on Friday.", ["are playing", "'re playing"]),
   ("The next bus ___ (leave) in ten minutes.", ["leaves"]),
  ]),
 ],
 "test": [
  ("What ___ you doing tomorrow evening?", ["are", "do", "will"]),
  ("The film ___ at 7:30.", ["starts", "start", "starting"]),
  ("I ___ my grandparents this Sunday. It's all arranged.", ["am visiting", "visit to", "visited"]),
  ("When ___ the train arrive?", ["does", "is", "do"]),
  ("She ___ to Paris next week. She's got her ticket.", ["is going", "go", "gone"]),
  ("The term ___ on 2nd September.", ["begins", "begin", "beginning"]),
  ("We ___ a barbecue on Saturday. Can you come?", ["are having", "has", "having"]),
  ("The shop ___ until 10 pm tonight.", ["doesn't close", "isn't close", "don't close"]),
  ("___ you working tomorrow?", ["Are", "Do", "Is"]),
  ("My plane ___ at 6 am, so I need to get up early.", ["leaves", "leave", "is leave"]),
 ],
 "task": "Write your diary for next week: 6 arrangements (present continuous) and 3 timetable facts (buses, lessons, films) in the present simple.",
},
{
 "n": 17, "title": "Modal verbs",
 "lesson": [
  ("can / could", [
   "Ability: I <b>can</b> swim. She <b>can't</b> drive. When I was five, I <b>could</b> read.",
   "Permission and requests: <b>Can</b> I open the window? <b>Could</b> you help me, please? (more polite)"]),
  ("must / have to", [
   "<b>must</b>: strong obligation, often from the speaker: I <b>must</b> finish this today.",
   "<b>have to</b>: obligation from rules: We <b>have to</b> wear a uniform. She <b>has to</b> work on Saturdays.",
   "<b>mustn't</b> = it is not allowed: You <b>mustn't</b> smoke here.",
   "<b>don't have to</b> = it is not necessary: It's Sunday. I <b>don't have to</b> get up early.",
   "UZ: mustn't – mumkin emas (taqiq); don't have to – shart emas."]),
  ("should / may / might", [
   "Advice: You <b>should</b> see a doctor. You <b>shouldn't</b> eat so much sugar.",
   "Possibility: It <b>may / might</b> rain later.",
   "Form: modal + base verb, no <i>to</i>: ✔ can swim ✘ can to swim · ✔ should go ✘ should to go",
   "Remember: <i>have to</i> changes: he <b>has to</b>, <b>do</b> you <b>have to</b>...?"]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("I ___ swim when I was five.", ["could", "can", "must"]),
   ("You ___ smoke in the hospital.", ["mustn't", "don't have to", "shouldn't to"]),
   ("It's Sunday, so we ___ go to school.", ["don't have to", "mustn't", "can't to"]),
   ("You look tired. You ___ go to bed early.", ["should", "must to", "could to"]),
   ("___ I open the window, please?", ["Can", "Must", "Should to"]),
   ("She ___ wear a uniform at work. It's a rule.", ["has to", "have to", "must to"]),
  ]),
  ("Complete the sentences.", "gap", [
   ("My grandmother ___ (can / not) use a computer.", ["can't", "cannot", "can not"]),
   ("You ___ (should / not) eat so much sugar. It's bad for you.", ["shouldn't", "should not"]),
   ("Students ___ (have to) wear a uniform at our school.", ["have to"]),
   ("___ you help me, please? (polite request)", ["Could", "Can"]),
   ("It's very important. He ___ finish the report today.", ["must", "has to"]),
   ("We ___ hurry. We have plenty of time. (not necessary)", ["don't have to", "do not have to"]),
  ]),
  ("Each sentence has a mistake. Write the correct words.", "gap", [
   ("She can to speak three languages. → She ___ three languages.", ["can speak"]),
   ("You must to listen to the teacher. → You ___ to the teacher.", ["must listen"]),
   ("He have to work on Saturdays. → He ___ work on Saturdays.", ["has to"]),
   ("We don't must shout in the library. → We ___ shout in the library.", ["mustn't", "must not"]),
   ("You should to see a doctor. → You ___ a doctor.", ["should see"]),
  ]),
 ],
 "test": [
  ("___ you ride a bike?", ["Can", "Must", "Have"]),
  ("You ___ touch that. It's dangerous!", ["mustn't", "don't have to", "can"]),
  ("I ___ get up early tomorrow — it's a holiday!", ["don't have to", "mustn't", "can't"]),
  ("What ___ I do? I've lost my passport.", ["should", "have", "must to"]),
  ("When I was young, I ___ run very fast.", ["could", "can", "must"]),
  ("___ I borrow your pen, please?", ["Could", "Should", "Must"]),
  ("Does she ___ work at weekends?", ["have to", "must", "has to"]),
  ("Take an umbrella. It ___ rain later.", ["might", "must", "has to"]),
  ("You ___ try this cake. It's delicious!", ["should", "have", "can to"]),
  ("We ___ go now or we'll miss the bus.", ["must", "mustn't", "don't have to"]),
 ],
 "task": "Write the rules of your school or home: 3 things you have to do, 3 things you mustn't do, 2 things you don't have to do. Then give a friend 3 pieces of advice with should.",
},
{
 "n": 18, "title": "Shopping",
 "words": [
  ("shop assistant", "sotuvchi", "The shop assistant was very helpful."),
  ("customer", "xaridor", "The shop was full of customers."),
  ("price / cost", "narx / turmoq (narxi)", "How much does it cost?"),
  ("cheap / expensive", "arzon / qimmat", "These trainers are expensive."),
  ("sale", "chegirmali savdo", "Everything is 50% off in the sale."),
  ("bargain", "arzon va foydali xarid", "Only $5? What a bargain!"),
  ("receipt", "chek", "Keep the receipt."),
  ("cash / card", "naqd pul / karta", "I'll pay by card."),
  ("change", "qaytim", "Here's your change."),
  ("queue", "navbat", "There was a long queue at the checkout."),
  ("spend", "(pul) sarflamoq", "I spent all my money on books."),
  ("shopping centre", "savdo markazi", "There are 100 shops in the shopping centre."),
  ("supermarket / bakery", "supermarket / novvoyxona", "You buy bread at a bakery."),
  ("chemist's", "dorixona", "You can buy medicine at the chemist's."),
 ],
 "tip": "pay by card / in cash · spend money on something · How much is it? / How much does it cost?",
 "ex": [
  ("Choose the correct word.", "mc", [
   ("You buy bread at a ___.", ["bakery", "chemist's", "bookshop"]),
   ("How much does it ___?", ["cost", "pay", "price"]),
   ("You get a ___ after you pay.", ["receipt", "recipe", "price"]),
   ("Are you paying by card or in ___?", ["cash", "money", "coins"]),
   ("It was only $5. What a ___!", ["bargain", "sale", "receipt"]),
   ("There were ten people in the ___ at the checkout.", ["queue", "row", "group"]),
  ]),
  ("Complete with a word or phrase from the box.", "gap", [
   ("The ___ helped me find the right shoes.", ["shop assistant"]),
   ("It's too ___. I can't buy it.", ["expensive"]),
   ("Here's 20,000 som. — Thanks, and here's your ___.", ["change"]),
   ("Every ___ gets a free bag today.", ["customer"]),
   ("There are 100 shops in the new ___.", ["shopping centre"]),
   ("Everything is 50% off in the ___.", ["sale"]),
  ], ["shop assistant", "expensive", "change", "customer", "shopping centre", "sale"]),
  ("Write the opposite.", "gap", [
   ("cheap → ___", ["expensive"]),
   ("buy → ___", ["sell"]),
   ("open → ___", ["closed", "shut"]),
   ("cash → ___", ["card"]),
   ("full → ___", ["empty"]),
  ]),
 ],
 "test": [
  ("The ___ of this bag is 200,000 som.", ["price", "receipt", "sale"]),
  ("I always pay ___ card.", ["by", "in", "on"]),
  ("Can I have a ___ for this, please?", ["receipt", "recipe", "ticket"]),
  ("How much ___ these shoes cost?", ["do", "does", "are"]),
  ("The ___ is very helpful. She works in the shop.", ["shop assistant", "customer", "receipt"]),
  ("You can buy medicine at the ___.", ["chemist's", "baker's", "butcher's"]),
  ("I'm sorry, we're ___. We open at 9 am.", ["closed", "close", "closing"]),
  ("Please wait in the ___.", ["queue", "sale", "bill"]),
  ("Can I ___ this jacket for a bigger size?", ["change", "sell", "cost"]),
  ("We ___ a lot of money at the market.", ["spent", "cost", "bought"]),
 ],
 "task": "Role-play in pairs: a customer and a shop assistant. Write the dialogue (10–12 lines): ask for something, ask the price, pay and get your change.",
},
{
 "n": 19, "title": "The passive",
 "lesson": [
  ("Form", [
   "be + past participle",
   "Present simple passive: English <b>is spoken</b> here. Cars <b>are made</b> in this factory.",
   "Past simple passive: The bridge <b>was built</b> in 1990. The letters <b>were sent</b> yesterday.",
   "Negative: It <b>isn't made</b> / It <b>wasn't built</b> · Question: <b>Is</b> it <b>made</b>…? <b>Was</b> it <b>built</b>…?",
   "UZ: Majhul nisbat: be + fe'lning 3-shakli. Harakatni kim bajargani emas, harakatning o'zi muhim bo'lganda ishlatiladi."]),
  ("Use", [
   "We use the passive when the action is more important than who does it, or when we don't know who does it: My bike <b>was stolen</b>.",
   "Use <b>by</b> to say who did it: Harry Potter <b>was written by</b> J.K. Rowling.",
   "Active: Leonardo painted the Mona Lisa. → Passive: The Mona Lisa <b>was painted by</b> Leonardo."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("English ___ all over the world.", ["is spoken", "speaks", "is speak"]),
   ("This bridge ___ in 1995.", ["was built", "is built", "built"]),
   ("Rice ___ in many Asian countries.", ["is grown", "is grow", "grown"]),
   ("The letters ___ yesterday.", ["were sent", "was sent", "sent"]),
   ("The Mona Lisa was painted ___ Leonardo da Vinci.", ["by", "from", "with"]),
   ("___ the car washed every week?", ["Is", "Does", "Do"]),
  ]),
  ("Put the verb in brackets in the passive.", "gap", [
   ("Paper ___ (make) from wood.", ["is made"]),
   ("The Registan ___ (build) many years ago.", ["was built"]),
   ("These phones ___ (produce) in Korea.", ["are produced"]),
   ("My bike ___ (steal) last night.", ["was stolen"]),
   ("The windows ___ (clean) every Monday.", ["are cleaned"]),
   ("Harry Potter ___ (write) by J.K. Rowling.", ["was written"]),
  ]),
  ("Write the past participle.", "gap", [
   ("make → ___", ["made"]),
   ("write → ___", ["written"]),
   ("sell → ___", ["sold"]),
   ("find → ___", ["found"]),
   ("speak → ___", ["spoken"]),
   ("give → ___", ["given"]),
  ]),
 ],
 "test": [
  ("Cheese ___ from milk.", ["is made", "made", "makes"]),
  ("The film ___ in 2010.", ["was made", "is made", "made"]),
  ("The rooms ___ every day.", ["are cleaned", "is cleaned", "cleans"]),
  ("This song was sung ___ a famous singer.", ["by", "from", "of"]),
  ("The thief ___ by the police.", ["was caught", "caught", "is catch"]),
  ("Where ___ these shoes made?", ["were", "was", "did"]),
  ("Tea ___ in Uzbekistan every day.", ["is drunk", "drinks", "is drank"]),
  ("The emails ___ yesterday.", ["were sent", "are sent", "was sent"]),
  ("Our house ___ in 1980.", ["was built", "built", "is build"]),
  ("Many languages ___ in India.", ["are spoken", "speak", "is spoken"]),
 ],
 "task": "Write 8 passive sentences about your country: what is grown, made or eaten there; what famous buildings were built and when.",
},
{
 "n": 20, "title": "Articles",
 "lesson": [
  ("a / an", [
   "Use <b>a / an</b> with a singular countable noun when we mention it for the first time or say what someone is: I've got <b>a</b> cat. She's <b>an</b> engineer.",
   "<b>an</b> before a vowel sound: <b>an</b> apple, <b>an</b> hour · <b>a</b> before a consonant sound: <b>a</b> university, <b>a</b> European city",
   "UZ: a/an – birinchi marta tilga olinganda yoki kasbni aytganda ishlatiladi."]),
  ("the", [
   "Something we already know or mentioned before: I've got a cat. <b>The</b> cat is black.",
   "There is only one: <b>the</b> sun, <b>the</b> moon, <b>the</b> sky, <b>the</b> world",
   "Superlatives: <b>the</b> best, <b>the</b> most expensive · Musical instruments: play <b>the</b> piano",
   "Rivers, seas, some countries: <b>the</b> Amu Darya, <b>the</b> Black Sea, <b>the</b> UK, <b>the</b> USA, <b>the</b> Netherlands"]),
  ("No article", [
   "Plural and uncountable nouns in general: I love <b>music</b>. <b>Dogs</b> are friendly.",
   "Most countries, cities, streets: Uzbekistan, Tashkent, Navoi Street",
   "Meals and some phrases: have breakfast / lunch, go to school / work / bed, at home, by bus",
   "UZ: Umumiy ma'nodagi ko'plik va sanalmaydigan otlar, shahar va ko'pchilik davlat nomlari oldidan artikl qo'yilmaydi."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("I saw ___ interesting film yesterday.", ["an", "a", "the"]),
   ("___ sun is very hot today.", ["The", "A", "An"]),
   ("My mum is ___ doctor.", ["a", "the", "an"]),
   ("I usually go to ___ bed at 10.", ["no article", "the", "a"]),
   ("Can you play ___ guitar?", ["the", "a", "an"]),
   ("She lives in ___ Tashkent.", ["no article", "the", "a"]),
  ]),
  ("Complete with a, an or the. Write - if no article is needed.", "gap", [
   ("It takes ___ hour to get there.", ["an"]),
   ("He's ___ best student in our class.", ["the"]),
   ("I have a cat. ___ cat is black.", ["The"]),
   ("We have ___ breakfast at 7.", ["-", "—", "no article", "0", "x"]),
   ("She is ___ university student.", ["a"]),
   ("___ Amu Darya is a long river.", ["The"]),
  ]),
  ("Complete with the or - (no article).", "gap", [
   ("I love ___ music. (in general)", ["-", "—", "no article", "0", "x"]),
   ("___ music at the party was too loud.", ["The"]),
   ("___ dogs are friendly animals. (in general)", ["-", "—", "no article", "0", "x"]),
   ("___ dogs next door bark all night.", ["The"]),
   ("Have you ever been to ___ Netherlands?", ["the"]),
  ]),
 ],
 "test": [
  ("She's ___ engineer.", ["an", "a", "the"]),
  ("___ moon goes round the Earth.", ["The", "A", "An"]),
  ("I like ___ apples.", ["no article", "the", "an"]),
  ("He plays ___ piano very well.", ["the", "a", "an"]),
  ("It's ___ most expensive hotel in town.", ["the", "a", "an"]),
  ("We had ___ lunch in a café.", ["no article", "a", "an"]),
  ("There's ___ bank near my house.", ["a", "an", "the"]),
  ("Is there ___ university in your town?", ["a", "an", "no article"]),
  ("My father goes to ___ work by car.", ["no article", "the", "a"]),
  ("Look at ___ sky! It's so blue.", ["the", "a", "no article"]),
 ],
 "task": "Write 8 sentences about your town. Then underline every a, an and the and explain to a partner why you used it.",
},
{
 "n": 21, "title": "Customs and traditions",
 "words": [
  ("celebrate", "nishonlamoq", "We celebrate Navruz in March."),
  ("festival", "bayram, festival", "There's a music festival every summer."),
  ("tradition / custom", "an'ana / odat, urf-odat", "It's a custom to offer guests tea."),
  ("traditional", "an'anaviy", "Sumalak is a traditional Navruz dish."),
  ("wedding", "to'y", "My cousin's wedding is on Saturday."),
  ("bride / groom", "kelin / kuyov", "The bride wore a white dress."),
  ("guest", "mehmon", "There were 300 guests at the wedding."),
  ("invite / invitation", "taklif qilmoq / taklifnoma", "Thanks for the invitation!"),
  ("present / gift", "sovg'a", "I got a lot of presents on my birthday."),
  ("decorate", "bezamoq", "We decorate the house for New Year."),
  ("fireworks", "mushakbozlik", "We watched the fireworks at midnight."),
  ("costume", "(milliy) kiyim, libos", "The dancers wore national costume."),
  ("parade", "parad, namoyish", "There was a big parade in the centre."),
  ("national", "milliy", "Plov is a national dish."),
 ],
 "tip": "celebrate a birthday / Navruz · give / get a present · invite someone to a party · wear national costume.",
 "ex": [
  ("Choose the correct word.", "mc", [
   ("People ___ Navruz on 21st March.", ["celebrate", "decorate", "invite"]),
   ("A woman on her wedding day is a ___.", ["bride", "groom", "guest"]),
   ("At midnight on New Year's Eve we watch the ___.", ["fireworks", "parade", "costume"]),
   ("People who come to your party are ___.", ["guests", "hosts", "customers"]),
   ("We ___ the house with flowers.", ["decorate", "celebrate", "invite"]),
   ("Sumalak is a ___ Navruz dish.", ["traditional", "modern", "foreign"]),
  ]),
  ("Complete with a word from the box.", "gap", [
   ("My cousin's ___ is on Saturday. 300 guests are coming!", ["wedding"]),
   ("I got an ___ to her birthday party.", ["invitation"]),
   ("What ___ did you give your mum for her birthday?", ["present"]),
   ("The dancers wore national ___.", ["costume", "costumes"]),
   ("There's a music ___ in the park every summer.", ["festival"]),
   ("It's a ___ in Uzbekistan to offer guests tea.", ["custom", "tradition"]),
  ], ["wedding", "invitation", "present", "costume", "festival", "custom"]),
  ("Word formation: write the word.", "gap", [
   ("celebration → verb: ___", ["celebrate"]),
   ("invitation → verb: ___", ["invite"]),
   ("decoration → verb: ___", ["decorate"]),
   ("tradition → adjective: ___", ["traditional"]),
   ("nation → adjective: ___", ["national"]),
   ("culture → adjective: ___", ["cultural"]),
  ]),
 ],
 "test": [
  ("On my birthday I got a lot of ___.", ["presents", "guests", "parades"]),
  ("The ___ and groom danced together.", ["bride", "guest", "fan"]),
  ("Did they ___ you to the wedding?", ["invite", "celebrate", "decorate"]),
  ("In many countries people ___ trees at Christmas.", ["decorate", "celebrate", "invite"]),
  ("Navruz is a very old ___.", ["festival", "parade", "guest"]),
  ("We ___ New Year with our family.", ["celebrate", "invite", "decorate"]),
  ("There was a big ___ through the city centre.", ["parade", "costume", "gift"]),
  ("Plov is a ___ dish in Uzbekistan.", ["national", "nation", "nationality"]),
  ("In many homes it's a ___ to take off your shoes at the door.", ["custom", "guest", "present"]),
  ("Thank you for the ___!", ["invitation", "invite", "inviting"]),
 ],
 "task": "Describe a festival or tradition in your country (8–10 sentences). When is it? What do people eat, wear and do?",
},
{
 "n": 22, "title": "Countable and uncountable nouns 1",
 "lesson": [
  ("Countable nouns", [
   "They have a singular and a plural form: a shirt → shirts, an apple → two apples.",
   "The verb agrees: The dress <b>is</b> beautiful. The dresses <b>are</b> beautiful.",
   "Use <b>some</b> in positive sentences and <b>any</b> in negatives and questions: There are <b>some</b> T-shirts. There aren't <b>any</b> T-shirts. Are there <b>any</b> T-shirts?"]),
  ("Uncountable nouns", [
   "Substances and abstract ideas: water, bread, butter, cheese, milk, rice, sugar, money, music, news, information, advice, furniture, hair, jewellery, work, travel",
   "No <i>a / an</i>, no plural, singular verb: Her news <b>was</b> really good! ✘ an advice, ✘ informations",
   "Use some / any too: There's <b>some</b> jewellery in the box. Is there <b>any</b> milk?",
   "Some nouns can be both: a cake / some cake, a light / light, a paper (newspaper) / paper, a room / room (space)",
   "UZ: Sanalmaydigan otlar (water, money, advice, news) ko'plikda ishlatilmaydi va birlikdagi fe'l bilan keladi."]),
  ("Plural-only nouns", [
   "Some nouns are always plural: jeans, trousers, shorts, glasses, scissors — Your jeans <b>are</b> new. These glasses <b>are</b> mine."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("There isn't ___ milk in the fridge.", ["any", "some", "a"]),
   ("Would you like ___ tea?", ["some", "any", "a"]),
   ("Can you give me some ___?", ["advice", "advices", "an advice"]),
   ("Her news ___ really good!", ["was", "were", "are"]),
   ("My jeans ___ too long.", ["are", "is", "was"]),
   ("There ___ some bread on the table.", ["is", "are", "be"]),
  ]),
  ("Complete with a, an, some or any.", "gap", [
   ("Are there ___ shops near here?", ["any"]),
   ("I bought ___ apples at the market.", ["some"]),
   ("I need ___ umbrella.", ["an"]),
   ("There isn't ___ sugar left.", ["any"]),
   ("Can I have ___ glass of water?", ["a"]),
   ("We've got ___ cheese in the fridge.", ["some"]),
  ]),
  ("Write C (countable) or U (uncountable).", "gap", [
   ("bread → ___", ["U", "uncountable"]),
   ("chair → ___", ["C", "countable"]),
   ("music → ___", ["U", "uncountable"]),
   ("money → ___", ["U", "uncountable"]),
   ("coin → ___", ["C", "countable"]),
   ("information → ___", ["U", "uncountable"]),
  ]),
 ],
 "test": [
  ("There's ___ sugar in my coffee.", ["some", "a", "many"]),
  ("I haven't got ___ brothers.", ["any", "some", "a"]),
  ("Can I have ___ water, please?", ["some", "a", "many"]),
  ("___ information is wrong.", ["This", "These", "An"]),
  ("Is there ___ bread left?", ["any", "many", "a"]),
  ("Our new ___ is very comfortable.", ["furniture", "furnitures", "a furniture"]),
  ("Your hair ___ lovely!", ["looks", "look", "are looking"]),
  ("These trousers ___ too tight.", ["are", "is", "was"]),
  ("I'd like ___ orange, please.", ["an", "a", "some"]),
  ("We don't have ___ homework today.", ["any", "a", "some"]),
 ],
 "task": "Look in your kitchen (or imagine it). Write 8 sentences with there is / there are + a, an, some, any.",
},
{
 "n": 23, "title": "Countable and uncountable nouns 2",
 "lesson": [
  ("a lot of / lots of", [
   "Both mean the same. Use them with plural countable and uncountable nouns: She's got <b>a lot of</b> bags. She's got <b>lots of</b> jewellery.",
   "We can also use them in negatives: I haven't got <b>a lot of</b> time."]),
  ("(not) many / (not) much", [
   "<b>many</b> + plural countable: There aren't <b>many</b> dresses. How <b>many</b> eggs?",
   "<b>much</b> + uncountable: She doesn't wear <b>much</b> make-up. How <b>much</b> money?",
   "We normally use many / much in negatives and questions. In positive sentences use a lot of: ✔ He's got <b>a lot of</b> chocolate. ✘ He's got much chocolate.",
   "UZ: many – sanaladigan, much – sanalmaydigan otlar bilan; darak gapda odatda a lot of ishlatiladi."]),
  ("a few / a little", [
   "<b>a few</b> + plural countable (a small number): I'm taking <b>a few</b> T-shirts.",
   "<b>a little</b> + uncountable (a small amount): Put <b>a little</b> shampoo on your hair.",
   "UZ: a few – bir nechta (sanaladigan); a little – ozgina (sanalmaydigan)."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("How ___ eggs do we need?", ["many", "much", "a lot"]),
   ("I have ___ friends in this city. Only three.", ["a few", "a little", "much"]),
   ("We don't have ___ time.", ["much", "many", "a few"]),
   ("She's got ___ jewellery.", ["lots of", "many", "a few"]),
   ("How ___ money have you got?", ["much", "many", "lot"]),
   ("Put ___ shampoo on your hair.", ["a little", "a few", "many"]),
  ]),
  ("Complete with much, many, a lot, a few or a little.", "gap", [
   ("How ___ money have you got?", ["much"]),
   ("There aren't ___ students in the class today.", ["many"]),
   ("She drinks ___ of water every day.", ["a lot", "lots"]),
   ("Add ___ salt — just a small amount.", ["a little"]),
   ("I'm taking ___ T-shirts with me — three or four.", ["a few"]),
   ("How ___ people live in your house?", ["many"]),
  ]),
  ("Each sentence has a mistake. Write the correct words.", "gap", [
   ("He has got much chocolate. → He has got ___ chocolate.", ["a lot of", "lots of"]),
   ("She has got many bags. → She has got ___ bags.", ["a lot of", "lots of"]),
   ("How much books have you read? → How ___ books have you read?", ["many"]),
   ("I have a few money. → I have ___ money.", ["a little"]),
   ("There isn't many milk. → There isn't ___ milk.", ["much"]),
  ]),
 ],
 "test": [
  ("How ___ people came?", ["many", "much", "any"]),
  ("There is too ___ traffic today.", ["much", "many", "few"]),
  ("We've got ___ oranges, so let's make juice.", ["a lot of", "much", "a little"]),
  ("She speaks ___ English — just a few words.", ["a little", "a few", "many"]),
  ("I've got ___ friends in Samarkand — two or three.", ["a few", "a little", "much"]),
  ("How ___ sugar do you take in your tea?", ["much", "many", "few"]),
  ("There aren't ___ trees in our street.", ["many", "much", "a little"]),
  ("He's got ___ money. He's very rich.", ["lots of", "many", "a few"]),
  ("Can I have ___ milk in my coffee?", ["a little", "a few", "many"]),
  ("I don't have ___ free time this week.", ["much", "many", "a few"]),
 ],
 "task": "Write a shopping list for a class party with 8 items. Then write sentences: We need a lot of…, We don't need much…, We need a few…, We need a little…",
},
{
 "n": 24, "title": "Fashion",
 "words": [
  ("fashion / fashionable", "moda / modali", "Short jackets are in fashion."),
  ("old-fashioned", "eskirgan, eski uslubdagi", "Grandad's hat is old-fashioned."),
  ("designer", "dizayner", "She wants to be a fashion designer."),
  ("wear", "kiymoq, kiyib yurmoq", "I wear a uniform at school."),
  ("put on / take off", "kiymoq / yechmoq", "Take off your shoes, please."),
  ("try on", "kiyib ko'rmoq", "Can I try on this jacket?"),
  ("size", "o'lcham", "What size are you?"),
  ("fit / suit / match", "(o'lchamda) to'g'ri kelmoq / yarashmoq / mos kelmoq", "The red bag matches your shoes."),
  ("tight / loose", "tor / keng", "These jeans are too tight."),
  ("changing room", "kiyinish xonasi", "The changing room is over there."),
  ("jewellery", "zargarlik buyumlari", "She loves gold jewellery."),
  ("jacket / sweater / skirt", "kurtka / sviter / yubka", "It's cold — wear a sweater."),
  ("jeans / trainers / boots", "jinsi shim / krossovka / etik", "I'm wearing jeans and trainers."),
  ("scarf / gloves", "sharf / qo'lqop", "Wear a scarf and gloves in winter."),
 ],
 "tip": "fit = the size is right · suit = it looks good on you · match = the colours/styles go together.",
 "ex": [
  ("Choose the correct word.", "mc", [
   ("Can I ___ this jacket?", ["try on", "try in", "wear on"]),
   ("These shoes are too small. They don't ___ me.", ["fit", "suit", "match"]),
   ("Your bag ___ your shoes — they're both red.", ["matches", "fits", "wears"]),
   ("That style is very ___ — everybody's wearing it now.", ["fashionable", "old-fashioned", "loose"]),
   ("My grandad's hat is ___. Nobody wears those now.", ["old-fashioned", "trendy", "fashionable"]),
   ("Rings and necklaces are ___.", ["jewellery", "clothes", "shoes"]),
  ]),
  ("Complete with a word or phrase from the box.", "gap", [
   ("What ___ are you? — Medium.", ["size"]),
   ("That colour really ___ you!", ["suits"]),
   ("You can try it on in the ___.", ["changing room"]),
   ("I ___ a uniform at school.", ["wear"]),
   ("She wants to be a fashion ___.", ["designer"]),
   ("These trousers are too ___. I need a belt.", ["loose"]),
  ], ["size", "suits", "changing room", "wear", "designer", "loose"]),
  ("What is it?", "gap", [
   ("You wear them on your feet for sport: ___", ["trainers"]),
   ("A warm top made of wool: a ___", ["sweater", "jumper"]),
   ("Blue trousers made of denim: ___", ["jeans"]),
   ("You wear it round your neck in winter: a ___", ["scarf"]),
   ("You wear them on your hands when it's cold: ___", ["gloves"]),
   ("A woman's clothing from the waist down: a ___", ["skirt"]),
  ]),
 ],
 "test": [
  ("These jeans are too ___; I need a bigger size.", ["tight", "loose", "cheap"]),
  ("Where can I ___ these trousers on?", ["try", "test", "wear"]),
  ("This dress doesn't ___ me. The colour is wrong for me.", ["suit", "cost", "try"]),
  ("Trainers are a kind of ___.", ["shoe", "hat", "shirt"]),
  ("It's winter, so wear a warm ___.", ["jacket", "T-shirt", "shorts"]),
  ("What are you ___ to the party tonight?", ["wearing", "dressing", "putting"]),
  ("Her earrings are real gold ___.", ["jewellery", "clothes", "fashion"]),
  ("Put ___ your coat; it's cold.", ["on", "in", "up"]),
  ("Take ___ your shoes, please.", ["off", "out", "away"]),
  ("Short skirts are in ___ this year.", ["fashion", "mode", "dress"]),
 ],
 "task": "Describe what you are wearing today and your favourite outfit (8 sentences). Is fashion important to you? Why / why not?",
},
{
 "n": 25, "title": "Comparatives",
 "lesson": [
  ("Form", [
   "Short adjectives: tall → tall<b>er</b>, cheap → cheap<b>er</b>",
   "Ending in -e: nice → nice<b>r</b> · Ending in -y: happy → happ<b>ier</b>, easy → eas<b>ier</b>",
   "One vowel + one consonant: big → bi<b>gger</b>, hot → ho<b>tter</b>",
   "Long adjectives: <b>more</b> expensive, <b>more</b> interesting · <b>less</b> expensive",
   "Irregular: good → <b>better</b>, bad → <b>worse</b>, far → <b>further / farther</b>",
   "UZ: Ikki narsani solishtirishda: -er / more + than."]),
  ("than / as ... as", [
   "Use <b>than</b>: My brother is taller <b>than</b> me.",
   "<b>as</b> + adjective + <b>as</b> = the same: She's <b>as tall as</b> her sister.",
   "<b>not as</b> ... <b>as</b> = less: This book is<b>n't as</b> interesting <b>as</b> that one.",
   "UZ: as ... as – bir xil darajada; not as ... as – ... chalik emas."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("My brother is ___ than me.", ["taller", "tall", "tallest"]),
   ("Tashkent is ___ than Bukhara.", ["bigger", "big", "biggest"]),
   ("Maths is ___ than history for me.", ["more difficult", "difficulter", "most difficult"]),
   ("Today is ___ than yesterday.", ["worse", "bad", "worst"]),
   ("She is as ___ as her sister.", ["clever", "cleverer", "cleverest"]),
   ("He's older ___ me.", ["than", "as", "that"]),
  ]),
  ("Write the comparative form.", "gap", [
   ("This bag is ___ (cheap) than that one.", ["cheaper"]),
   ("My new phone is ___ (good) than my old one.", ["better"]),
   ("This hotel is ___ (expensive) than ours.", ["more expensive"]),
   ("I'm ___ (happy) now than last year.", ["happier"]),
   ("July is ___ (hot) than May.", ["hotter"]),
   ("My school is ___ (far) from my house than yours.", ["further", "farther"]),
  ]),
  ("Complete with than, as, more or less.", "gap", [
   ("She isn't as tall ___ her mum.", ["as"]),
   ("This question is ___ difficult than the last one.", ["more"]),
   ("Buses are ___ expensive than taxis. (= cheaper)", ["less"]),
   ("My room is bigger ___ yours.", ["than"]),
   ("He is ___ old as my father. (the same age)", ["as"]),
  ]),
 ],
 "test": [
  ("A car is ___ than a bike.", ["faster", "fast", "fastest"]),
  ("Her English is ___ than mine.", ["better", "gooder", "best"]),
  ("My room is ___ than yours.", ["bigger", "biger", "more big"]),
  ("He isn't as friendly ___ his brother.", ["as", "than", "like"]),
  ("Walking is ___ than driving.", ["healthier", "healthyer", "more healthier"]),
  ("The library is ___ away than the park.", ["further", "far", "furthest"]),
  ("This book is ___ interesting than that one.", ["more", "most", "much"]),
  ("Is Russian ___ than English?", ["easier", "easyer", "more easy"]),
  ("My sister is two years older ___ me.", ["than", "as", "that"]),
  ("The weather today is ___ than yesterday.", ["worse", "badder", "more bad"]),
 ],
 "task": "Compare two cities, two phones or two sports you know. Write 8 sentences with comparatives, as … as and not as … as.",
},
{
 "n": 26, "title": "Superlatives",
 "lesson": [
  ("Form", [
   "Short adjectives: the tall<b>est</b>, the cheap<b>est</b>",
   "-e: the nice<b>st</b> · -y: the happ<b>iest</b>, the eas<b>iest</b> · double consonant: the bi<b>ggest</b>, the ho<b>ttest</b>",
   "Long adjectives: <b>the most</b> expensive, <b>the least</b> expensive",
   "Irregular: good → <b>the best</b>, bad → <b>the worst</b>, far → <b>the furthest</b>",
   "UZ: Uch yoki undan ortiq narsa ichidan eng ...sini ko'rsatish: the + -est / the most."]),
  ("Use", [
   "We usually use <b>the</b> before a superlative: It's <b>the best</b> café in town.",
   "<b>in</b> + places / groups: the tallest boy <b>in</b> our class, the biggest city <b>in</b> the world",
   "<b>of</b> + time / numbers: the best day <b>of</b> the year, the oldest <b>of</b> the three",
   "With present perfect + ever: It's the best film I've <b>ever</b> seen."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("This is the ___ film I've ever seen.", ["funniest", "funnier", "most funny"]),
   ("Winter is the ___ season.", ["coldest", "colder", "most cold"]),
   ("It's the ___ beautiful place in the city.", ["most", "more", "much"]),
   ("It was the ___ day of my life!", ["worst", "worse", "baddest"]),
   ("She's the ___ student in the class.", ["best", "better", "goodest"]),
   ("Everest is the ___ mountain in the world.", ["highest", "higher", "most high"]),
  ]),
  ("Write the superlative form.", "gap", [
   ("It's the ___ (hot) day of the year.", ["hottest"]),
   ("Who is the ___ (happy) person you know?", ["happiest"]),
   ("That was the ___ (bad) meal of my life!", ["worst"]),
   ("This is the ___ (expensive) phone in the shop.", ["most expensive"]),
   ("February is the ___ (short) month.", ["shortest"]),
   ("Which is the ___ (big) city in Uzbekistan?", ["biggest"]),
  ]),
  ("Complete with the, most, in, of or ever.", "gap", [
   ("It's ___ best café in town.", ["the"]),
   ("He's the tallest boy ___ our class.", ["in"]),
   ("It's the ___ famous mountain in the world.", ["most"]),
   ("It was the best day ___ the year.", ["of"]),
   ("This is the best book I've ___ read.", ["ever"]),
  ]),
 ],
 "test": [
  ("February is the ___ month of the year.", ["shortest", "shorter", "most short"]),
  ("Tashkent is the ___ city in Uzbekistan.", ["biggest", "bigger", "most big"]),
  ("This is ___ easiest exercise in the book.", ["the", "a", "most"]),
  ("She's the ___ intelligent girl I know.", ["most", "more", "much"]),
  ("Who is the ___ player in your team?", ["best", "better", "goodest"]),
  ("It's the coldest place ___ the world.", ["in", "of", "at"]),
  ("That was the ___ film I've ever seen.", ["worst", "baddest", "worse"]),
  ("He is the ___ person in our family.", ["oldest", "older", "most old"]),
  ("It's the most beautiful beach I've ___ seen.", ["ever", "never", "yet"]),
  ("Which is the ___ interesting subject for you?", ["most", "more", "very"]),
 ],
 "task": "Write 8 superlative sentences about your class, your city and your country (the tallest…, the most famous…, the best…).",
},
{
 "n": 27, "title": "Places",
 "words": [
  ("town centre / square", "shahar markazi / maydon", "There's a big fountain in the main square."),
  ("museum / gallery", "muzey / galereya", "We saw old coins at the museum."),
  ("library", "kutubxona", "You can borrow books from the library."),
  ("post office", "pochta", "I sent a parcel from the post office."),
  ("bank", "bank", "I need to go to the bank to change money."),
  ("hospital", "kasalxona", "He broke his arm and went to hospital."),
  ("police station", "politsiya bo'limi", "Someone stole my bag, so I went to the police station."),
  ("bus station / railway station", "avtovokzal / temir yo'l vokzali", "Trains to Samarkand leave from the railway station."),
  ("airport", "aeroport", "The plane landed at the airport."),
  ("market", "bozor", "We buy fruit at Chorsu market."),
  ("cinema / theatre", "kinoteatr / teatr", "Let's see a play at the theatre."),
  ("hotel / restaurant / café", "mehmonxona / restoran / kafe", "We stayed in a hotel near the centre."),
  ("mosque", "masjid", "There's an old mosque in the square."),
  ("bridge / park", "ko'prik / bog'", "Walk across the bridge to the park."),
 ],
 "tip": "at the station / at the airport · in the park / in the town centre · on the corner · next to the bank · opposite the library.",
 "ex": [
  ("Choose the correct word.", "mc", [
   ("You borrow books from a ___.", ["library", "museum", "bank"]),
   ("You see old things from history in a ___.", ["museum", "market", "hospital"]),
   ("You send a parcel at the ___.", ["post office", "police station", "bus station"]),
   ("You catch a train at the ___.", ["railway station", "bus stop", "airport"]),
   ("You watch a film at the ___.", ["cinema", "library", "post office"]),
   ("Doctors and nurses work in a ___.", ["hospital", "bank", "hotel"]),
  ]),
  ("Complete with a word or phrase from the box.", "gap", [
   ("We stayed in a nice ___ near the centre.", ["hotel"]),
   ("There's a big fountain in the main ___.", ["square"]),
   ("You can buy fresh fruit at the ___.", ["market"]),
   ("Someone stole my bag, so I went to the ___.", ["police station"]),
   ("We had dinner at a Turkish ___.", ["restaurant"]),
   ("Walk across the ___ over the river.", ["bridge"]),
  ], ["hotel", "square", "market", "police station", "restaurant", "bridge"]),
  ("Where do you go?", "gap", [
   ("to change money → the ___", ["bank"]),
   ("to see a play → the ___", ["theatre", "theater"]),
   ("to catch a plane → the ___", ["airport"]),
   ("to pray → a ___", ["mosque"]),
   ("to see paintings → a ___", ["gallery", "museum"]),
   ("to play on the grass → the ___", ["park"]),
  ]),
 ],
 "test": [
  ("Let's meet in front of the ___ and see a film.", ["cinema", "library", "bank"]),
  ("I need money. Is there a ___ near here?", ["bank", "park", "square"]),
  ("Buses to Samarkand leave from the ___.", ["bus station", "railway station", "airport"]),
  ("We went to the ___ to see paintings.", ["gallery", "hospital", "post office"]),
  ("There are lots of shops in the town ___.", ["centre", "middle", "place"]),
  ("He broke his arm and went to ___.", ["hospital", "hotel", "museum"]),
  ("Planes land at the ___.", ["airport", "station", "harbour"]),
  ("The bank is ___ to the post office.", ["next", "near", "between"]),
  ("The ___ is closed, so I can't borrow books.", ["library", "bookshop", "museum"]),
  ("We had coffee in a small ___.", ["café", "bank", "office"]),
 ],
 "task": "Describe your town or district for a tourist (8–10 sentences): what places are there, where are they and what can you do there?",
},
{
 "n": 28, "title": "Adverbs",
 "lesson": [
  ("Adverbs of manner", [
   "Most adverbs = adjective + <b>-ly</b>: slow → slow<b>ly</b>, careful → careful<b>ly</b>, simple → simp<b>ly</b>, happy → happ<b>ily</b>",
   "Irregular: good → <b>well</b> · hard → <b>hard</b> · fast → <b>fast</b> · late → <b>late</b> · early → <b>early</b>",
   "<i>friendly</i> is an adjective. Say: in a friendly way.",
   "UZ: Ravish harakat qanday bajarilishini bildiradi: sifat + -ly. good → well."]),
  ("Other adverbs", [
   "Time: soon, now, then, later — We'll arrive <b>soon</b>.",
   "Frequency: always, usually, often, sometimes, rarely, never — She <b>rarely</b> travels by train.",
   "Degree (before an adjective / adverb): very, really, quite, too — We were <b>really</b> tired. She drives <b>very</b> fast."]),
  ("Comparison of adverbs", [
   "loudly → <b>more</b> loudly → <b>the most</b> loudly",
   "hard → harder → the hardest · early → earlier → the earliest · well → <b>better</b> → <b>the best</b> · badly → <b>worse</b> → <b>the worst</b> · far → further → the furthest",
   "Cars travel <b>more slowly</b> than planes. Andy drove <b>the fastest</b> of all."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("She speaks English very ___.", ["well", "good", "goodly"]),
   ("Please drive ___.", ["carefully", "careful", "carefuly"]),
   ("He runs very ___.", ["fast", "fastly", "faster than"]),
   ("They worked ___ all day.", ["hard", "hardly", "hardy"]),
   ("The children played ___.", ["happily", "happy", "happyly"]),
   ("I got up ___ this morning.", ["early", "earlily", "earlyly"]),
  ]),
  ("Write the adverb.", "gap", [
   ("slow → ___", ["slowly"]),
   ("easy → ___", ["easily"]),
   ("quiet → ___", ["quietly"]),
   ("good → ___", ["well"]),
   ("bad → ___", ["badly"]),
   ("gentle → ___", ["gently"]),
  ]),
  ("Write the comparative or superlative adverb.", "gap", [
   ("Can you speak ___ (slowly)? I don't understand. (comparative)", ["more slowly"]),
   ("She sings ___ (well) than her sister.", ["better"]),
   ("He arrived ___ (late) than us.", ["later"]),
   ("Who works ___ (hard) in your class? (superlative)", ["the hardest", "hardest"]),
   ("I did the test ___ (badly) than last time.", ["worse"]),
  ]),
 ],
 "test": [
  ("He answered the question ___.", ["correctly", "correct", "correctlly"]),
  ("You play the guitar really ___!", ["well", "good", "nice"]),
  ("She always dresses ___.", ["nicely", "nice", "nicer"]),
  ("Our teacher is very ___.", ["friendly", "friendlily", "friendlyly"]),
  ("Why are you walking so ___?", ["slowly", "slow", "slowlier"]),
  ("Aziz can swim ___ than me.", ["faster", "more fast", "fastlier"]),
  ("We ___ go to the cinema — maybe once a year.", ["rarely", "rare", "rarer"]),
  ("I was ___ tired after the trip.", ["really", "real", "reallly"]),
  ("He drives the ___ carefully of all my friends.", ["most", "more", "much"]),
  ("The bus arrived ___. We waited 30 minutes.", ["late", "lately", "latly"]),
 ],
 "task": "Describe how the people in your family do things (8 sentences): My dad drives carefully, My sister sings beautifully…",
},
]
