# Units 1-14. Grammar units have "lesson"; vocabulary units have "words" + "tip".
# MC items: (question, [correct, wrong, wrong]) - build.py shuffles options.
# Gap items: (sentence with one ___, [accepted answers]); optional word bank as 4th element of the exercise.

UNITS_A = [
{
 "n": 1, "title": "Present simple, there is / there are, it's",
 "lesson": [
  ("Present simple", [
   "Use it for <b>habits, routines, feelings and facts</b>.",
   "I / you / we / they <b>talk</b> · he / she / it <b>talks</b>",
   "Negative: I <b>don't</b> talk · She <b>doesn't</b> talk · Question: <b>Do</b> you talk? <b>Does</b> he talk?",
   "Spelling: go → go<b>es</b>, do → do<b>es</b>, watch → watch<b>es</b>, study → stud<b>ies</b>",
   "Time words: always, usually, often, sometimes, never (before the main verb, after <i>be</i>) · every day, on Mondays, at weekends",
   "UZ: Doimiy, takrorlanadigan harakatlar va umumiy faktlar. He/she/it bilan fe'lga -s qo'shiladi."]),
  ("There is / There are", [
   "Use it to say that something exists or is in a place.",
   "<b>There is</b> a bike in the street. · <b>There are</b> two men in the photo.",
   "Negative: There isn't … / There aren't … · Question: <b>Is there</b> …? <b>Are there</b> …?",
   "After the first mention, use <i>it</i> or <i>they</i>: There's a bike outside. <b>It's</b> my sister's.",
   "UZ: Biror joyda nimadir borligini aytish uchun: there is (birlik), there are (ko'plik)."]),
  ("It's", [
   "Use <i>it</i> as the subject for weather, time, days, distance and situations:",
   "<b>It's</b> cold today. · <b>It's</b> nine o'clock. · <b>It's</b> Friday! · <b>Is it</b> far to your school? · <b>It's</b> great to see you.",
   "UZ: Ob-havo, vaqt, sana va masofa haqida gapirganda gap <b>it</b> bilan boshlanadi."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("My brother ___ football every Saturday.", ["plays", "play", "playing"]),
   ("___ your mum work in a hospital?", ["Does", "Do", "Is"]),
   ("There ___ two cats in the garden.", ["are", "is", "be"]),
   ("___ there a bank near here?", ["Is", "Are", "It"]),
   ("___ very cold today.", ["It's", "There's", "Is"]),
   ("Water ___ at 100°C.", ["boils", "boil", "is boil"]),
  ]),
  ("Put the verb in brackets in the present simple.", "gap", [
   ("She ___ (not like) coffee.", ["doesn't like", "does not like"]),
   ("Tom usually ___ (get) up at seven.", ["gets"]),
   ("He ___ (watch) a film every Friday.", ["watches"]),
   ("How often ___ you go to the gym?", ["do"]),
   ("My sister ___ (study) at university.", ["studies"]),
   ("We ___ (not have) lessons on Sunday.", ["don't have", "do not have"]),
  ]),
  ("Complete with there is, there are, is there, are there or it's.", "gap", [
   ("___ a new café in our street.", ["There's", "There is"]),
   ("___ ten o'clock. Time for bed!", ["It's", "It is"]),
   ("___ any eggs in the fridge?", ["Are there"]),
   ("___ a lot of people in the park today.", ["There are"]),
   ("___ about 5 km from my house to the school.", ["It's", "It is"]),
   ("___ nice to see you again!", ["It's", "It is"]),
  ]),
 ],
 "test": [
  ("Sara ___ to music every evening.", ["listens", "listen", "is listen"]),
  ("I ___ understand this word.", ["don't", "doesn't", "not"]),
  ("How often ___ you go swimming?", ["do", "are", "does"]),
  ("The sun ___ in the east.", ["rises", "rise", "rising"]),
  ("He never ___ breakfast.", ["eats", "eat", "eating"]),
  ("There ___ a bottle of water on the table.", ["is", "are", "it's"]),
  ("___ there any shops in your village?", ["Are", "Is", "Do"]),
  ("___ Monday today.", ["It's", "There's", "It"]),
  ("There ___ many students in the class today.", ["aren't", "isn't", "not"]),
  ("Is there a park near your house? — Yes, there ___.", ["is", "are", "it is"]),
 ],
 "task": "Describe your town or village: write 4 sentences with there is / there are, 4 sentences about what people usually do there and 2 sentences with It's.",
},
{
 "n": 2, "title": "Present continuous, stative verbs",
 "lesson": [
  ("Present continuous", [
   "Use it for actions happening <b>now</b> or <b>around now</b> (temporary situations).",
   "I <b>am</b> reading · he / she / it <b>is</b> reading · you / we / they <b>are</b> reading",
   "Negative: I'm not / She isn't / They aren't reading · Question: <b>Are</b> you reading? <b>Is</b> she reading?",
   "Time words: now, right now, at the moment, today, this week, Look! Listen!",
   "Spelling: make → mak<b>ing</b>, swim → swi<b>mming</b>, sit → si<b>tting</b>, lie → l<b>ying</b>",
   "UZ: Hozir, ayni paytda davom etayotgan yoki vaqtinchalik harakat: am/is/are + fe'l-ing."]),
  ("Present simple or present continuous?", [
   "Present simple = always, usually: He <b>walks</b> to school every day.",
   "Present continuous = now, temporary: Today he <b>is taking</b> the bus."]),
  ("Stative verbs", [
   "Some verbs describe states (feelings, thoughts, possession), not actions. We don't usually use them in the continuous.",
   "like, love, hate, want, need, prefer, know, understand, believe, remember, mean, belong, own",
   "✔ I <b>know</b> the answer. ✘ I am knowing the answer.",
   "UZ: Holat fe'llari (like, know, want...) odatda -ing shaklida ishlatilmaydi."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("Look! The baby ___.", ["is sleeping", "sleeps", "sleep"]),
   ("I ___ this song. It's great!", ["love", "am loving", "loves"]),
   ("We can't go out now. It ___.", ["is raining", "rains", "rain"]),
   ("What ___ you doing?", ["are", "do", "is"]),
   ("She ___ the answer.", ["knows", "is knowing", "know"]),
   ("They ___ in London this month.", ["are staying", "stay", "stays"]),
  ]),
  ("Put the verb in brackets in the present continuous.", "gap", [
   ("What are you ___ (do) right now?", ["doing"]),
   ("I ___ (study) for my exam this week.", ["am studying", "'m studying"]),
   ("My parents ___ (not watch) TV at the moment.", ["aren't watching", "are not watching"]),
   ("Listen! Somebody ___ (sing).", ["is singing", "'s singing"]),
   ("___ (she / wear) a hat today?", ["Is she wearing"]),
   ("The children ___ (swim) in the lake now.", ["are swimming", "'re swimming"]),
  ]),
  ("Each sentence has a mistake. Write the correct words.", "gap", [
   ("I am knowing the answer. → I ___ the answer.", ["know"]),
   ("Listen! Somebody sing. → Listen! Somebody ___.", ["is singing", "'s singing"]),
   ("They are play tennis now. → They ___ tennis now.", ["are playing", "'re playing"]),
   ("She is wanting a new phone. → She ___ a new phone.", ["wants"]),
   ("He's siting on the sofa. → He's ___ on the sofa.", ["sitting"]),
  ]),
 ],
 "test": [
  ("Where's Ali? He ___ a shower.", ["is having", "has", "have"]),
  ("Shh! The teacher ___.", ["is talking", "talks", "talk"]),
  ("My sister ___ chocolate.", ["hates", "is hating", "hate"]),
  ("What ___ she doing?", ["is", "does", "do"]),
  ("I ___ what you mean.", ["understand", "am understanding", "understanding"]),
  ("___ it raining now?", ["Is", "Does", "Are"]),
  ("We ___ a new house at the moment.", ["are building", "build", "builds"]),
  ("This bag ___ to me.", ["belongs", "is belonging", "belong"]),
  ("Why ___ you laughing?", ["are", "do", "is"]),
  ("He usually walks, but today he ___ the bus.", ["is taking", "takes", "take"]),
 ],
 "task": "Look out of the window or at a photo. Write 8 sentences about what people are doing. Then write 3 sentences with like, want and need.",
},
{
 "n": 3, "title": "Family and friends",
 "words": [
  ("parents", "ota-ona", "My parents work in a bank."),
  ("grandparents", "bobo va buvi", "I visit my grandparents every Sunday."),
  ("aunt", "xola / amma", "My aunt lives in Samarkand."),
  ("uncle", "amaki / tog'a", "My uncle is a doctor."),
  ("cousin", "amakivachcha, xolavachcha", "My cousin is the same age as me."),
  ("nephew", "jiyan (o'g'il)", "My sister's son is my nephew."),
  ("niece", "jiyan (qiz)", "My niece is three years old."),
  ("twins", "egizaklar", "Hasan and Husan are twins."),
  ("only child", "yolg'iz farzand", "I'm an only child, so I have no brothers or sisters."),
  ("married / single", "oilali / bo'ydoq, turmushga chiqmagan", "My brother is married, but my sister is single."),
  ("neighbour", "qo'shni", "Our neighbour has a big dog."),
  ("get on well with", "... bilan yaxshi chiqishmoq", "I get on well with my cousins."),
  ("look like", "... ga o'xshamoq", "You look like your mum."),
  ("look after", "... ga qaramoq, g'amxo'rlik qilmoq", "Grandma looks after the baby."),
  ("grow up", "katta bo'lmoq, ulg'aymoq", "I grew up in Andijan."),
 ],
 "tip": "Use 's for family: my mother's sister = my aunt; my uncle's son = my cousin.",
 "ex": [
  ("Choose the correct word.", "mc", [
   ("My mother's sister is my ___.", ["aunt", "uncle", "niece"]),
   ("My uncle's son is my ___.", ["cousin", "nephew", "brother"]),
   ("My brother's daughter is my ___.", ["niece", "nephew", "aunt"]),
   ("People who live next door are your ___.", ["neighbours", "cousins", "twins"]),
   ("Two children born at the same time to the same mother are ___.", ["twins", "cousins", "parents"]),
   ("My father's father is my ___.", ["grandfather", "uncle", "grandson"]),
  ]),
  ("Complete with a word or phrase from the box.", "gap", [
   ("I ___ in a small village near Namangan.", ["grew up"]),
   ("She has no brothers or sisters. She's an ___.", ["only child"]),
   ("Many people say I ___ my dad. We have the same eyes.", ["look like"]),
   ("My grandma helps to ___ my little sister.", ["look after"]),
   ("My sister is ___ and has two children.", ["married"]),
   ("I ___ with my classmates. We never argue.", ["get on well"]),
  ], ["grew up", "only child", "look like", "look after", "married", "get on well"]),
  ("Write the female word.", "gap", [
   ("husband → ___", ["wife"]),
   ("son → ___", ["daughter"]),
   ("uncle → ___", ["aunt"]),
   ("nephew → ___", ["niece"]),
   ("grandfather → ___", ["grandmother", "grandma"]),
   ("brother → ___", ["sister"]),
  ]),
 ],
 "test": [
  ("Your mother's mother is your ___.", ["grandmother", "aunt", "niece"]),
  ("My sister's son is my ___.", ["nephew", "niece", "cousin"]),
  ("I ___ with my brother; we're good friends.", ["get on well", "look after", "grow up"]),
  ("She ___ her mother — they both have red hair.", ["looks like", "looks after", "looks for"]),
  ("My aunt's children are my ___.", ["cousins", "nephews", "uncles"]),
  ("He isn't married. He's ___.", ["single", "only", "alone"]),
  ("Your parents are your mother and your ___.", ["father", "brother", "uncle"]),
  ("Who will ___ the dog while we're on holiday?", ["look after", "look like", "grow up"]),
  ("My ___ friend is Madina. We tell each other everything.", ["best", "good", "better"]),
  ("Children ___ very fast!", ["grow up", "get up", "look up"]),
 ],
 "task": "Draw your family tree. Then write 8 sentences about your family: who they are, what they look like and who you get on well with.",
},
{
 "n": 4, "title": "Past simple 1",
 "lesson": [
  ("Past simple: regular verbs", [
   "Use it for <b>finished actions</b> in the past, <b>one action after another</b>, and <b>repeated past actions</b>.",
   "Positive: I / you / he / she / we / they <b>walked</b> to the park.",
   "Negative: They <b>didn't walk</b> (did not walk). ✘ didn't walked",
   "Question: <b>Did</b> you <b>walk</b> to the park? — Yes, I did. / No, I didn't.",
   "UZ: O'tgan zamonda tugallangan harakat. Inkor va so'roqda did + fe'lning asosiy shakli (-ed qo'shilmaydi)."]),
  ("Spelling", [
   "Most verbs + <b>-ed</b>: finish → finish<b>ed</b>, walk → walk<b>ed</b>",
   "Ending in -e + <b>-d</b>: live → liv<b>ed</b> · -ie: die → di<b>ed</b>",
   "Consonant + y → <b>-ied</b>: cry → cr<b>ied</b>, study → stud<b>ied</b> · vowel + y: enjoy → enjoy<b>ed</b>",
   "One vowel + one consonant → double: stop → sto<b>pped</b>, plan → pla<b>nned</b>, prefer → prefe<b>rred</b>",
   "British English -l → -ll: travel → trave<b>lled</b>, cancel → cance<b>lled</b>"]),
  ("Time expressions", [
   "yesterday, yesterday morning, last night / week, two months <b>ago</b>, this morning, on Monday, at six o'clock, in 2014"]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("We ___ football yesterday.", ["played", "play", "plaied"]),
   ("___ you watch the match last night?", ["Did", "Do", "Were"]),
   ("I didn't ___ my homework.", ["finish", "finished", "finishing"]),
   ("They ___ in Tashkent two years ago.", ["lived", "live", "livd"]),
   ("She ___ the bus this morning.", ["missed", "misses", "miss"]),
   ("When ___ they arrive?", ["did", "do", "were"]),
  ]),
  ("Write the past simple form.", "gap", [
   ("stop → ___", ["stopped"]),
   ("study → ___", ["studied"]),
   ("enjoy → ___", ["enjoyed"]),
   ("travel → ___", ["travelled", "traveled"]),
   ("cry → ___", ["cried"]),
   ("prefer → ___", ["preferred"]),
  ]),
  ("Put the verb in brackets in the past simple.", "gap", [
   ("I ___ (not / watch) TV last night.", ["didn't watch", "did not watch"]),
   ("___ (you / visit) your grandma on Sunday?", ["Did you visit"]),
   ("We ___ (walk) to school this morning.", ["walked"]),
   ("He ___ (try) to call you three times.", ["tried"]),
   ("She ___ (not / like) the film.", ["didn't like", "did not like"]),
   ("They ___ (move) to a new flat last year.", ["moved"]),
  ]),
 ],
 "test": [
  ("I ___ my friend last week.", ["visited", "visit", "visitted"]),
  ("Did she ___ the piano?", ["play", "played", "plays"]),
  ("We ___ the museum on Saturday.", ["enjoyed", "enjoied", "enjoy"]),
  ("He ___ answer my question.", ["didn't", "doesn't", "wasn't"]),
  ("They ___ very hard for the test.", ["studied", "studyed", "study"]),
  ("___ you call me yesterday?", ["Did", "Do", "Was"]),
  ("The shop ___ at 8 pm last night.", ["closed", "close", "closes"]),
  ("I saw him three days ___.", ["ago", "last", "before"]),
  ("She ___ the door and went out.", ["opened", "openned", "open"]),
  ("We didn't ___ at home.", ["stay", "stayed", "staying"]),
 ],
 "task": "Write 8 sentences about yesterday using regular verbs (watched, played, cooked, visited, helped...). Then write 2 questions to ask a friend about their day.",
},
{
 "n": 5, "title": "Past simple 2",
 "lesson": [
  ("Past simple: to be", [
   "I / he / she / it <b>was</b> · you / we / they <b>were</b>",
   "Negative: wasn't / weren't · Question: <b>Was</b> she at home? <b>Were</b> they happy? — Yes, they were. / No, they weren't.",
   "UZ: <i>be</i> fe'lining o'tgan zamonda ikki shakli bor: was va were."]),
  ("Past simple: common irregular verbs", [
   "Irregular verbs don't use -ed. You must learn them:",
   "go → <b>went</b>, see → <b>saw</b>, have → <b>had</b>, buy → <b>bought</b>, eat → <b>ate</b>, take → <b>took</b>, write → <b>wrote</b>, get → <b>got</b>, come → <b>came</b>, make → <b>made</b>, give → <b>gave</b>, break → <b>broke</b>, lose → <b>lost</b>",
   "Some verbs don't change: cut → cut, put → put, hit → hit, let → let",
   "Negative and question are the same as regular verbs: I <b>didn't go</b>. <b>Did</b> you <b>go</b>?",
   "UZ: Noto'g'ri fe'llarning o'tgan zamon shaklini yodlash kerak. Inkor va so'roqda baribir did + asosiy shakl."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("She ___ at home on Sunday.", ["was", "were", "did"]),
   ("We ___ to the cinema last night.", ["went", "goed", "go"]),
   ("___ your parents at the party?", ["Were", "Was", "Did"]),
   ("The film ___ very funny.", ["was", "were", "did"]),
   ("I ___ a new phone last week.", ["bought", "buyed", "buy"]),
   ("They ___ tired after the trip.", ["were", "was", "did"]),
  ]),
  ("Write the past simple form.", "gap", [
   ("take → ___", ["took"]),
   ("see → ___", ["saw"]),
   ("make → ___", ["made"]),
   ("come → ___", ["came"]),
   ("eat → ___", ["ate"]),
   ("write → ___", ["wrote"]),
  ]),
  ("Put the verb in brackets in the past simple.", "gap", [
   ("He ___ (buy) a new bike.", ["bought"]),
   ("My grandfather ___ (write) many letters.", ["wrote"]),
   ("I ___ (not be) at school yesterday. I was ill.", ["wasn't", "was not"]),
   ("We ___ (have) a great time on holiday.", ["had"]),
   ("She ___ (lose) her keys.", ["lost"]),
   ("___ (be) the test difficult?", ["Was"]),
  ]),
 ],
 "test": [
  ("I ___ my keys this morning.", ["lost", "lose", "losed"]),
  ("There ___ many people at the concert.", ["were", "was", "did"]),
  ("We ___ a great time on holiday.", ["had", "have", "haved"]),
  ("She ___ the bus to school yesterday.", ["took", "taked", "take"]),
  ("___ it cold yesterday?", ["Was", "Did", "Were"]),
  ("They ___ home at ten o'clock.", ["got", "get", "getted"]),
  ("Did you ___ the new teacher?", ["meet", "met", "meeting"]),
  ("He ___ me a nice present.", ["gave", "gived", "give"]),
  ("The children ___ very happy.", ["were", "was", "are"]),
  ("I ___ my leg last year.", ["broke", "breaked", "break"]),
 ],
 "task": "Write about your last weekend in 6–8 sentences. Where did you go? What did you do? Who did you see? Use at least 5 irregular verbs.",
},
{
 "n": 6, "title": "Leisure time",
 "words": [
  ("free time", "bo'sh vaqt", "What do you do in your free time?"),
  ("hobby", "sevimli mashg'ulot", "My hobby is photography."),
  ("collect", "to'plamoq, yig'moq", "My brother collects old coins."),
  ("go camping", "chodirda dam olishga bormoq", "We went camping in the mountains."),
  ("board game", "stol o'yini", "Chess is a board game."),
  ("hang out with friends", "do'stlar bilan vaqt o'tkazmoq", "I hang out with friends in the park."),
  ("play an instrument", "cholg'u chalmoq", "Can you play the guitar?"),
  ("draw / paint", "chizmoq / bo'yoq bilan rasm solmoq", "She paints beautiful pictures."),
  ("join a club", "to'garakka a'zo bo'lmoq", "I joined the chess club."),
  ("be interested in", "... ga qiziqmoq", "I'm interested in history."),
  ("be good at", "... ni yaxshi bilmoq, uddalamoq", "He's good at drawing."),
  ("relax", "dam olmoq", "On Sundays I relax at home."),
  ("go out", "ko'chaga chiqmoq, sayrga chiqmoq", "We go out on Friday evenings."),
  ("exciting / boring", "hayajonli / zerikarli", "The match was really exciting!"),
 ],
 "tip": "play + games and ball sports (play chess, play football) · go + -ing activities (go swimming, go camping) · do + other activities (do yoga, do karate).",
 "ex": [
  ("Choose the correct verb.", "mc", [
   ("___ swimming", ["go", "do", "play"]),
   ("___ football", ["play", "do", "go"]),
   ("___ yoga", ["do", "go", "play"]),
   ("___ camping", ["go", "do", "play"]),
   ("___ chess", ["play", "do", "go"]),
   ("___ a photo", ["take", "do", "go"]),
  ]),
  ("Complete with a word from the box.", "gap", [
   ("My ___ is photography.", ["hobby"]),
   ("My brother likes to ___ old coins.", ["collect"]),
   ("We went ___ in the mountains and slept in a tent.", ["camping"]),
   ("I'm very ___ in history.", ["interested"]),
   ("She joined a chess ___ at school.", ["club"]),
   ("At weekends I like to ___ and do nothing.", ["relax"]),
  ], ["hobby", "collect", "camping", "interested", "club", "relax"]),
  ("Complete with have, do, go or play.", "gap", [
   ("___ a shower", ["have", "take"]),
   ("___ the piano", ["play"]),
   ("___ for a walk", ["go"]),
   ("___ exercise", ["do"]),
   ("___ a rest", ["have", "take"]),
   ("___ fishing", ["go"]),
  ]),
 ],
 "test": [
  ("We ___ volleyball every Friday.", ["play", "go", "do"]),
  ("She ___ yoga in the morning.", ["does", "plays", "goes"]),
  ("My brother is good ___ drawing.", ["at", "in", "on"]),
  ("Do you want to ___ out with us tonight?", ["hang", "stay", "look"]),
  ("They ___ fishing at the lake.", ["went", "played", "did"]),
  ("I'm interested ___ music.", ["in", "at", "on"]),
  ("Chess is a ___ game.", ["board", "table", "card"]),
  ("What do you do in your free ___?", ["time", "hour", "day"]),
  ("Can you ___ the guitar?", ["play", "do", "go"]),
  ("That film was so ___. I fell asleep!", ["boring", "bored", "exciting"]),
 ],
 "task": "Write about your hobbies and free time in 8–10 sentences. What are you good at? What are you interested in? What do you do at weekends?",
},
{
 "n": 7, "title": "Past continuous",
 "lesson": [
  ("Past continuous", [
   "Form: was / were + verb-ing",
   "Use it for an action <b>in progress</b> at a time in the past: At 8 o'clock last night I <b>was watching</b> a film.",
   "Negative: wasn't / weren't + -ing · Question: Were you sleeping?",
   "UZ: O'tmishda ma'lum bir paytda davom etayotgan harakat."]),
  ("Past continuous + past simple", [
   "A long action is interrupted by a short action: I <b>was having</b> a shower <b>when</b> the phone <b>rang</b>.",
   "<b>While</b> we <b>were walking</b>, it <b>started</b> to rain.",
   "Two long actions at the same time: She was cooking <b>while</b> he was cleaning.",
   "Tip: <b>when</b> + short action (past simple), <b>while</b> + long action (past continuous).",
   "UZ: Uzoq davom etgan harakat (past continuous) qisqa harakat (past simple) bilan bo'linadi."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("At 8 pm yesterday I ___ dinner.", ["was having", "had", "have"]),
   ("They ___ football when it started to rain.", ["were playing", "played", "was playing"]),
   ("While she was cooking, the phone ___.", ["rang", "was ringing", "rings"]),
   ("What ___ you doing at midnight?", ["were", "was", "did"]),
   ("I ___ sleeping when you called.", ["wasn't", "weren't", "didn't"]),
   ("He broke his leg while he ___.", ["was skiing", "skied", "were skiing"]),
  ]),
  ("Put the verb in brackets in the past continuous or past simple.", "gap", [
   ("We ___ (walk) home when we saw the accident.", ["were walking"]),
   ("She ___ (read) a book at 10 o'clock last night.", ["was reading"]),
   ("When I arrived, the children ___ (sleep).", ["were sleeping"]),
   ("I ___ (drop) my phone while I was running.", ["dropped"]),
   ("It ___ (not rain) when we left the house.", ["wasn't raining", "was not raining"]),
   ("___ (you / watch) TV when I phoned?", ["Were you watching"]),
  ]),
  ("Complete with when or while.", "gap", [
   ("___ the teacher came in, everyone stopped talking.", ["When"]),
   ("___ I was waiting for the bus, I read the news.", ["While", "When"]),
   ("The lights went out ___ we were having dinner.", ["while", "when"]),
   ("___ I heard the news, I called my mum.", ["When"]),
   ("She was listening to music ___ she was doing her homework.", ["while", "when"]),
  ]),
 ],
 "test": [
  ("I ___ TV when the doorbell rang.", ["was watching", "watched", "am watching"]),
  ("They ___ in the park at 5 pm yesterday.", ["were running", "was running", "run"]),
  ("She ___ her arm when she fell off her bike.", ["broke", "was breaking", "breaks"]),
  ("___ were you doing at 9 this morning?", ["What", "When", "Who"]),
  ("While I was walking, I ___ a friend.", ["saw", "was seeing", "see"]),
  ("The sun ___ and the birds were singing.", ["was shining", "shone", "shines"]),
  ("He ___ working at 7 pm; he was at home.", ["wasn't", "didn't", "weren't"]),
  ("What happened ___ you were on holiday?", ["while", "during", "at"]),
  ("We ___ to the radio when we heard the news.", ["were listening", "listened", "was listening"]),
  ("___ they sleeping when you got home?", ["Were", "Was", "Did"]),
 ],
 "task": "Tell a short story (6–8 sentences) that begins: \"It was a cold evening. I was walking home when...\" Use the past continuous and the past simple.",
},
{
 "n": 8, "title": "Imperative, infinitive, -ing form",
 "lesson": [
  ("Imperative", [
   "Use it for orders, requests, instructions and advice: <b>Close</b> the door. <b>Don't touch</b> that!",
   "<b>Let's</b> + base verb for suggestions: <b>Let's go</b> to the park.",
   "UZ: Buyruq, iltimos va maslahat: fe'lning asosiy shakli; inkori – Don't + fe'l."]),
  ("Verb + to-infinitive", [
   "agree, ask, choose, decide, forget, hope, learn, offer, plan, promise, refuse, seem, want, would like",
   "He <b>decided to do</b> judo. · I <b>want to be</b> a doctor.",
   "UZ: Bu fe'llardan keyin <b>to + fe'l</b> keladi."]),
  ("Verb + -ing form", [
   "enjoy, finish, like, love, hate, miss, remember, stop, suggest, don't mind",
   "I <b>enjoy playing</b> football. · She <b>finished cleaning</b> her room.",
   "Both are possible after <b>begin, start, continue</b>: It started to rain / raining. But in continuous tenses use to: ✔ It's starting <b>to rain</b>.",
   "UZ: Bu fe'llardan keyin fe'l <b>-ing</b> shaklida keladi."]),
  ("see / hear / watch / notice + object + verb", [
   "Whole action → base verb: I saw the man <b>fall</b> off his horse.",
   "Action in progress → -ing: I saw her <b>walking</b> down the street."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("___ the window, please. It's cold.", ["Close", "To close", "Closing"]),
   ("___ touch that! It's hot.", ["Don't", "Not", "No"]),
   ("I want ___ a doctor.", ["to be", "being", "be"]),
   ("She enjoys ___ books.", ["reading", "to read", "read"]),
   ("We decided ___ at home.", ["to stay", "staying", "stay"]),
   ("Have you finished ___ your room?", ["cleaning", "to clean", "clean"]),
  ]),
  ("Put the verb in brackets in the correct form (to + verb or -ing).", "gap", [
   ("They hope ___ (win) the match.", ["to win"]),
   ("I miss ___ (see) my old friends.", ["seeing"]),
   ("He promised ___ (help) me.", ["to help"]),
   ("Do you like ___ (swim)?", ["swimming", "to swim"]),
   ("My dad stopped ___ (smoke) last year.", ["smoking"]),
   ("She forgot ___ (buy) milk.", ["to buy"]),
  ]),
  ("Complete the imperatives and sentences.", "gap", [
   ("___ (not / be) late tomorrow!", ["Don't be", "Do not be"]),
   ("___ go to the park! (suggestion)", ["Let's"]),
   ("Please ___ (sit) down.", ["sit"]),
   ("___ (not / run) in the corridor.", ["Don't run", "Do not run"]),
   ("I saw him ___ (cross) the road and get into a car.", ["cross"]),
  ]),
 ],
 "test": [
  ("___ quiet, please!", ["Be", "To be", "Being"]),
  ("She agreed ___ me.", ["to help", "helping", "help"]),
  ("I don't mind ___ the dishes.", ["washing", "to wash", "wash"]),
  ("Let's ___ a pizza.", ["order", "to order", "ordering"]),
  ("He refused ___ the question.", ["to answer", "answering", "answer"]),
  ("Look at the sky. It's starting ___.", ["to rain", "raining", "rain"]),
  ("We heard her ___ in the next room.", ["singing", "to sing", "sang"]),
  ("Would you like ___ something?", ["to drink", "drinking", "drink"]),
  ("Stop ___! I'm trying to work.", ["talking", "talk", "talked"]),
  ("___ forget your passport!", ["Don't", "Not", "No"]),
 ],
 "task": "Write 6 rules for new students at your school (imperatives: Do… / Don't…). Then write 6 sentences about your plans and likes with want to, hope to, enjoy …-ing, love …-ing.",
},
{
 "n": 9, "title": "Sport",
 "words": [
  ("team", "jamoa", "Our team has eleven players."),
  ("player", "o'yinchi", "He's the best player in the team."),
  ("coach", "murabbiy", "The coach is very strict."),
  ("match / game", "o'yin, uchrashuv", "Did you watch the match last night?"),
  ("score a goal", "gol urmoq", "Ronaldo scored two goals."),
  ("win / lose", "g'alaba qozonmoq / yutqazmoq", "We won the match 3–1."),
  ("beat", "(raqibni) yengmoq", "We beat Pakhtakor 2–0."),
  ("referee", "hakam", "The referee blew the whistle."),
  ("fan", "muxlis", "Thousands of fans were singing."),
  ("stadium", "stadion", "The stadium has 30,000 seats."),
  ("pitch / court", "maydon / kort", "Tennis is played on a court."),
  ("train", "mashq qilmoq", "Footballers train every day."),
  ("competition", "musobaqa", "She won a swimming competition."),
  ("champion", "chempion", "He's the world champion."),
  ("race", "poyga", "Who won the 100-metre race?"),
 ],
 "tip": "win a match / a prize / a medal — but beat a team or a person. play football · go cycling · do karate.",
 "ex": [
  ("Choose the correct word.", "mc", [
   ("The person who trains a team is the ___.", ["coach", "referee", "fan"]),
   ("In football you try to ___ a goal.", ["score", "win", "beat"]),
   ("We ___ Pakhtakor 2–0!", ["beat", "won", "scored"]),
   ("They ___ the match.", ["won", "beat", "scored"]),
   ("Tennis is played on a ___.", ["court", "pitch", "pool"]),
   ("The ___ blew the whistle.", ["referee", "coach", "fan"]),
  ]),
  ("Complete with a word from the box.", "gap", [
   ("Our ___ has eleven players.", ["team"]),
   ("Thousands of ___ were singing.", ["fans"]),
   ("The new ___ has 30,000 seats.", ["stadium"]),
   ("Footballers ___ every day to stay fit.", ["train"]),
   ("He came first in the 100-metre ___.", ["race"]),
   ("She is the world ___ in chess.", ["champion"]),
  ], ["team", "fans", "stadium", "train", "race", "champion"]),
  ("Complete with play, go or do.", "gap", [
   ("___ karate", ["do"]),
   ("___ basketball", ["play"]),
   ("___ cycling", ["go"]),
   ("___ gymnastics", ["do"]),
   ("___ skiing", ["go"]),
   ("___ tennis", ["play"]),
  ]),
 ],
 "test": [
  ("Who ___ the game last night?", ["won", "beat", "scored"]),
  ("Ronaldo ___ two goals.", ["scored", "won", "made"]),
  ("Our team lost; the other team ___ us.", ["beat", "won", "scored"]),
  ("Football is played on a ___.", ["pitch", "court", "ring"]),
  ("The ___ were very happy when their team won.", ["fans", "referees", "coaches"]),
  ("She ___ judo twice a week.", ["does", "plays", "goes"]),
  ("They go ___ in the mountains in winter.", ["skiing", "ski", "to ski"]),
  ("The Olympic Games is a big sports ___.", ["competition", "team", "coach"]),
  ("He's a tennis ___.", ["player", "playing", "play"]),
  ("We ___ the final, so we got silver medals.", ["lost", "beat", "missed"]),
 ],
 "task": "Write about your favourite sport or sports star in 8–10 sentences. Why do you like them? What did they win?",
},
{
 "n": 10, "title": "Present perfect 1",
 "lesson": [
  ("Form", [
   "have / has + past participle",
   "I <b>have ('ve) taken</b> · She <b>has ('s) taken</b> · They <b>haven't taken</b> · <b>Have</b> you <b>taken</b>…? — Yes, I have. / No, I haven't.",
   "Regular past participles end in -ed. Irregular ones must be learnt: be → been, do → done, give → given, know → known, speak → spoken, take → taken, write → written, eat → eaten, see → seen",
   "UZ: have/has + fe'lning 3-shakli (past participle)."]),
  ("Uses", [
   "An action at an unknown or unimportant time: I<b>'ve finished</b> my project.",
   "A result now: David <b>has lost</b> his bag (he doesn't have it now).",
   "Experience: <b>Have</b> you <b>ever cheated</b> in a test? — No, I<b>'ve never</b> cheated.",
   "UZ: Natijasi hozir muhim bo'lgan yoki vaqti aytilmagan harakat, hayotiy tajriba."]),
  ("Time words", [
   "<b>just</b> (hozirgina): We've <b>just</b> done this exercise.",
   "<b>already</b> (allaqachon): I've <b>already</b> eaten.",
   "<b>yet</b> (hali, negative and questions, at the end): I haven't checked <b>yet</b>. Have you finished <b>yet</b>?",
   "<b>ever / never</b>: Have you <b>ever</b> been to Paris? I've <b>never</b> been there."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("Have you ever ___ to London?", ["been", "went", "go"]),
   ("She ___ finished her homework.", ["has just", "just has", "have just"]),
   ("I ___ seen that film. I don't want to see it again.", ["have already", "have yet", "already"]),
   ("We haven't eaten ___.", ["yet", "already", "just"]),
   ("Has he ___ met a famous person?", ["ever", "never", "yet"]),
   ("They ___ a new car.", ["have bought", "has bought", "have buy"]),
  ]),
  ("Put the verb in brackets in the present perfect.", "gap", [
   ("He ___ (lose) his keys again!", ["has lost", "'s lost"]),
   ("Have you ever ___ (eat) sushi?", ["eaten"]),
   ("I ___ (never / be) to Paris.", ["have never been", "'ve never been"]),
   ("They ___ (not finish) the project yet.", ["haven't finished", "have not finished"]),
   ("___ (you / do) your homework yet?", ["Have you done"]),
   ("She ___ (just / leave).", ["has just left", "'s just left"]),
  ]),
  ("Write the past participle.", "gap", [
   ("go → ___", ["gone"]),
   ("write → ___", ["written"]),
   ("see → ___", ["seen"]),
   ("buy → ___", ["bought"]),
   ("speak → ___", ["spoken"]),
   ("be → ___", ["been"]),
  ]),
 ],
 "test": [
  ("I ___ my homework. Can I go out now?", ["have finished", "finished", "finish"]),
  ("Has she called you ___?", ["yet", "already", "since"]),
  ("I've ___ met a famous person.", ["never", "ever", "yet"]),
  ("They ___ bought a new car.", ["have", "has", "having"]),
  ("Have you ___ read this book?", ["ever", "never", "yet"]),
  ("The train has ___ left. We're too late!", ["just", "yet", "ever"]),
  ("He hasn't ___ his lunch yet.", ["eaten", "ate", "eat"]),
  ("___ you seen my phone?", ["Have", "Has", "Did"]),
  ("She has ___ the letter.", ["written", "wrote", "writed"]),
  ("We've ___ done this exercise.", ["already", "yet", "ever"]),
 ],
 "task": "Interview a classmate: \"Have you ever...?\" (been abroad, cooked plov, climbed a mountain, met a famous person...). Write 6 sentences about their answers.",
},
{
 "n": 11, "title": "Present perfect 2",
 "lesson": [
  ("Present perfect or past simple?", [
   "Present perfect = result now / time not known: She<b>'s taken</b> photos for her project (she has them now).",
   "Past simple = finished action at a known time: She <b>took</b> photos <b>last night</b>.",
   "Past simple time words: ago, yesterday, last week, a few days ago, on Sunday, at eight o'clock, in 2013",
   "Present perfect time words: already, ever, just, never, yet, for, since",
   "UZ: Vaqt aniq aytilsa (yesterday, ago, in 2013) – past simple; aytilmasa yoki natija muhim bo'lsa – present perfect."]),
  ("for and since", [
   "Use the present perfect for actions that started in the past and continue now.",
   "<b>for</b> + a period: for two hours, for five years, for a long time",
   "<b>since</b> + a starting point: since Monday, since 2013, since I was a child",
   "<b>How long</b> have you lived here? — I've lived here <b>for</b> ten years / <b>since</b> 2015.",
   "been vs gone: He<b>'s been</b> to Rome (and came back). He<b>'s gone</b> to Rome (he is there now)."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("They ___ here since 2019.", ["have lived", "lived", "live"]),
   ("I ___ him yesterday.", ["saw", "have seen", "seen"]),
   ("She has worked here ___ five years.", ["for", "since", "ago"]),
   ("We have known each other ___ 2015.", ["since", "for", "ago"]),
   ("He ___ to Samarkand last summer.", ["went", "has gone", "has been"]),
   ("How long ___ you had this phone?", ["have", "did", "are"]),
  ]),
  ("Put the verb in brackets in the present perfect or past simple.", "gap", [
   ("I ___ (see) that film last week.", ["saw"]),
   ("She ___ (be) ill since Monday.", ["has been", "'s been"]),
   ("We ___ (live) here for ten years and we still love it.", ["have lived", "'ve lived"]),
   ("When ___ (you / arrive)?", ["did you arrive"]),
   ("I ___ (never / try) Indian food.", ["have never tried", "'ve never tried"]),
   ("They ___ (move) to Tashkent in 2018.", ["moved"]),
  ]),
  ("Complete with for, since or ago.", "gap", [
   ("___ two hours", ["for"]),
   ("___ last Friday", ["since"]),
   ("three days ___", ["ago"]),
   ("___ 2020", ["since"]),
   ("___ a long time", ["for"]),
   ("___ I was a child", ["since"]),
  ]),
 ],
 "test": [
  ("We have lived here ___ ten years.", ["for", "since", "ago"]),
  ("She has been ill ___ Monday.", ["since", "for", "ago"]),
  ("How long ___ you known him?", ["have", "did", "are"]),
  ("I ___ my grandparents last weekend.", ["visited", "have visited", "visit"]),
  ("He ___ in this company since 2021.", ["has worked", "worked", "works"]),
  ("___ did you start learning English?", ["When", "How long", "Since"]),
  ("They got married two years ___.", ["ago", "for", "since"]),
  ("I ___ this watch for five years.", ["have had", "had", "have"]),
  ("___ you go to the party last night?", ["Did", "Have", "Were"]),
  ("My brother ___ to Korea; he is there now.", ["has gone", "has been", "went"]),
 ],
 "task": "Write about your life: 4 sentences with for / since (I've lived..., I've known..., I've had...) and 4 sentences with past simple and a date (I started school in...).",
},
{
 "n": 12, "title": "Schools",
 "words": [
  ("subject", "fan", "My favourite subject is biology."),
  ("timetable", "dars jadvali", "Check the timetable for Monday."),
  ("break", "tanaffus", "We play football in the break."),
  ("uniform", "forma", "We wear a blue uniform."),
  ("classmate / pupil", "sinfdosh / o'quvchi", "Nodir is my classmate."),
  ("head teacher", "maktab direktori", "The head teacher spoke to all the pupils."),
  ("primary / secondary school", "boshlang'ich / o'rta maktab", "My little brother goes to primary school."),
  ("term", "chorak, semestr", "The autumn term starts in September."),
  ("revise", "takrorlamoq (imtihonga)", "I need to revise for the test."),
  ("take an exam", "imtihon topshirmoq", "I'm taking an exam on Friday."),
  ("pass / fail", "imtihondan o'tmoq / o'ta olmaslik", "She passed all her exams."),
  ("mark", "baho", "I got a good mark in maths."),
  ("homework", "uy vazifasi", "We have a lot of homework today."),
  ("canteen / library / lab", "oshxona / kutubxona / laboratoriya", "We eat lunch in the canteen."),
 ],
 "tip": "do homework · take (sit) an exam · pass / fail an exam · get a good mark · make a mistake.",
 "ex": [
  ("Choose the correct word.", "mc", [
   ("Maths and history are school ___.", ["subjects", "uniforms", "breaks"]),
   ("If you get 90%, you ___ the exam.", ["pass", "fail", "take"]),
   ("The person in charge of a school is the ___.", ["head teacher", "classmate", "pupil"]),
   ("Children aged 7–10 go to ___ school.", ["primary", "secondary", "university"]),
   ("You borrow books from the ___.", ["library", "gym", "canteen"]),
   ("The school year in the UK has three ___.", ["terms", "breaks", "marks"]),
  ]),
  ("Complete with a word from the box.", "gap", [
   ("Look at the ___ to see when we have PE.", ["timetable"]),
   ("I need to ___ for my test tomorrow.", ["revise"]),
   ("We play football in the ___ between lessons.", ["break"]),
   ("Students at my school wear a blue ___.", ["uniform"]),
   ("Our teacher gives us a lot of ___.", ["homework"]),
   ("Nodir is my ___. We sit together in maths.", ["classmate"]),
  ], ["timetable", "revise", "break", "uniform", "homework", "classmate"]),
  ("Complete with do, take, pass, get or make.", "gap", [
   ("___ your homework", ["do"]),
   ("___ a good mark", ["get"]),
   ("___ an exam (= sit it)", ["take", "sit"]),
   ("___ an exam (= get a good result)", ["pass"]),
   ("___ a mistake", ["make"]),
   ("___ notes in class", ["take", "make"]),
  ]),
 ],
 "test": [
  ("I'm going to ___ an exam on Friday.", ["take", "give", "win"]),
  ("He studied hard, so he didn't ___.", ["fail", "pass", "revise"]),
  ("We have ten minutes of ___ between lessons.", ["break", "timetable", "holiday"]),
  ("Did you do your ___?", ["homework", "housework", "work home"]),
  ("I got a good ___ in my test: A!", ["mark", "salary", "subject"]),
  ("We eat lunch in the school ___.", ["canteen", "library", "classroom"]),
  ("Sorry, I made a ___ in my essay.", ["mistake", "wrong", "fail"]),
  ("Pupils do experiments in the science ___.", ["lab", "gym", "canteen"]),
  ("After secondary school she went to ___.", ["university", "primary school", "nursery"]),
  ("Revise well before the ___.", ["exam", "break", "uniform"]),
 ],
 "task": "Write about your school in 8–10 sentences: subjects, timetable, breaks, teachers. What would you change?",
},
{
 "n": 13, "title": "will and be going to",
 "lesson": [
  ("will", [
   "Predictions (opinion): I think it <b>will</b> be sunny tomorrow. People <b>will</b> live on Mars.",
   "Decisions at the moment of speaking: The phone's ringing. I<b>'ll</b> answer it.",
   "Offers and promises: I<b>'ll</b> help you. I <b>won't</b> be late.",
   "Form: will + base verb · won't = will not · <b>Will</b> you help me?"]),
  ("be going to", [
   "Plans and intentions (decided before): I<b>'m going to</b> study medicine.",
   "Predictions with evidence now: Look at those clouds! It<b>'s going to</b> rain.",
   "Form: am / is / are + going to + base verb"]),
  ("Future time words", [
   "tomorrow, next week / year, soon, in two days, in 2030, this weekend",
   "UZ: will – shu zahoti qilingan qaror, taxmin, taklif, va'da; going to – oldindan rejalashtirilgan niyat yoki ko'rinib turgan dalilga asoslangan taxmin."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("Look at those clouds! It ___ rain.", ["is going to", "will", "rains"]),
   ("The phone is ringing. I ___ answer it.", ["'ll", "am going to", "answer"]),
   ("I think it ___ be sunny tomorrow.", ["will", "is", "going"]),
   ("I think robots ___ do most jobs in the future.", ["will", "are", "going"]),
   ("We ___ visit our grandparents this weekend. We decided last week.", ["are going to", "will", "going to"]),
   ("Don't worry, I ___ tell anyone.", ["won't", "am not going", "don't"]),
  ]),
  ("Put the verb in brackets in the correct future form.", "gap", [
   ("I'm tired. I think I ___ (go) to bed.", ["'ll go", "will go"]),
   ("She ___ (study) medicine next year — it's her plan.", ["is going to study", "'s going to study"]),
   ("I'm sure she ___ (like) your present.", ["will like", "'ll like"]),
   ("___ (you / help) me with this bag, please?", ["Will you help"]),
   ("Be careful! You ___ (fall)!", ["are going to fall", "'re going to fall"]),
   ("I promise I ___ (not be) late.", ["won't be", "will not be"]),
  ]),
  ("Complete with will, won't or going to.", "gap", [
   ("I've decided. I'm ___ learn to drive.", ["going to"]),
   ("It's cold. I ___ close the window.", ["'ll", "will"]),
   ("He's very busy, so he ___ come to the party.", ["won't"]),
   ("Are you ___ watch the match tonight?", ["going to"]),
   ("___ you marry me?", ["Will"]),
  ]),
 ],
 "test": [
  ("What ___ to do after school?", ["are you going", "will you", "do you go"]),
  ("That bag looks heavy. I ___ carry it for you.", ["'ll", "'m going", "going"]),
  ("My cousin ___ get married in June. They've planned everything.", ["is going to", "will to", "going"]),
  ("In 2050 people ___ live on Mars.", ["will probably", "are probably", "probably will to"]),
  ("She's saved money. She ___ buy a laptop.", ["is going to", "going to", "will to"]),
  ("I ___ be home late tonight, Mum.", ["won't", "not will", "don't"]),
  ("Watch out! That glass ___ fall!", ["is going to", "will to", "going"]),
  ("I promise I ___ call you tonight.", ["will", "am", "going"]),
  ("I'm sure you ___ pass your exam.", ["will", "are", "going"]),
  ("\"It's hot in here.\" \"I ___ open the window.\"", ["'ll", "'m going", "open"]),
 ],
 "task": "Write about your plans for next summer (going to) and 5 predictions about the world in 2050 (will / won't).",
},
{
 "n": 14, "title": "Pronouns and possessive determiners",
 "lesson": [
  ("Subject and object pronouns", [
   "Subject: I, you, he, she, it, we, they — <b>She</b> is my friend.",
   "Object: me, you, him, her, it, us, them — I like <b>her</b>. Call <b>me</b>!",
   "UZ: Ega sifatida – I, he, she...; fe'ldan yoki predlogdan keyin – me, him, her..."]),
  ("Possessive determiners and possessive pronouns", [
   "Determiner + noun: <b>my</b> bag, <b>your</b> bag, <b>his</b> bag, <b>her</b> bag, <b>its</b> tail, <b>our</b> bag, <b>their</b> bag",
   "Pronoun (no noun after it): It's <b>mine</b> / yours / his / <b>hers</b> / ours / theirs.",
   "<b>its</b> (egalik) ≠ <b>it's</b> (= it is) · <b>their</b> ≠ <b>there</b> ≠ <b>they're</b>",
   "UZ: my/your... dan keyin ot keladi; mine/yours... o'zi yolg'iz ishlatiladi."]),
  ("Possessive 's and reflexive pronouns", [
   "Ali<b>'s</b> car · my sister<b>'s</b> room · the children<b>'s</b> toys · my parents<b>'</b> house (plural -s → only ')",
   "Reflexive: myself, yourself, himself, herself, itself, ourselves, yourselves, themselves — She cut <b>herself</b>. We did it <b>ourselves</b>."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("This is my brother. ___ name is Aziz.", ["His", "He", "Him"]),
   ("Can you help ___?", ["me", "I", "my"]),
   ("Is this bag ___?", ["yours", "your", "you"]),
   ("The dog is eating ___ food.", ["its", "it's", "it"]),
   ("___ are my best friends.", ["They", "Them", "Their"]),
   ("She cut ___ with a knife.", ["herself", "her", "hers"]),
  ]),
  ("Complete with the correct pronoun or determiner.", "gap", [
   ("I like Madina. I often visit ___.", ["her"]),
   ("We love ___ new teacher.", ["our"]),
   ("This isn't my pen. It's ___ (she).", ["hers"]),
   ("My parents are nice. I help ___ at weekends.", ["them"]),
   ("Did you make this cake ___? (reflexive)", ["yourself"]),
   ("That car is ___ (we).", ["ours"]),
  ]),
  ("Rewrite with 's or '.", "gap", [
   ("the bag of my sister → my ___ bag", ["sister's"]),
   ("the toys of the children → the ___ toys", ["children's"]),
   ("the car of my parents → my ___ car", ["parents'"]),
   ("the house of Tom → ___ house", ["Tom's"]),
   ("the room of the teachers → the ___ room", ["teachers'"]),
  ]),
 ],
 "test": [
  ("___ is a doctor.", ["She", "Her", "Hers"]),
  ("Give the book to ___.", ["him", "he", "his"]),
  ("Is this ___ phone?", ["your", "yours", "you"]),
  ("The cat hurt ___ leg.", ["its", "it's", "it"]),
  ("These books are ___.", ["mine", "my", "me"]),
  ("We did it ___. Nobody helped us.", ["ourselves", "us", "our"]),
  ("That's my ___ house. They bought it last year.", ["parents'", "parent's", "parents's"]),
  ("Where are ___ keys?", ["their", "there", "they're"]),
  ("Call ___ later, OK?", ["us", "we", "our"]),
  ("The idea was ___, not mine.", ["hers", "her", "she"]),
 ],
 "task": "Write 8 sentences about things in your home and whose they are: This is my…, That's my brother's…, The blue one is mine…",
},
]
