# Extra unit-test items, written only for the unit tests (never used in practice sessions).
# Each unit: 5 multiple-choice items (question with ___, [correct, wrong, wrong]) and
# 5 write-in items (sentence with ___ and a hint in brackets, [accepted answers]).
# Grammar units give the base verb in brackets; vocabulary units give the Uzbek meaning.

TESTS = {
1: {"mc": [
    ("My sister ___ in a bank in Tashkent.", ["works", "work", "working"]),
    ("___ there a cinema in your town?", ["Is", "Are", "Does"]),
    ("We ___ go to school on Sundays.", ["don't", "doesn't", "aren't"]),
    ("___ very hot in Termez in summer.", ["It's", "There's", "It"]),
    ("There ___ some apples on the table.", ["are", "is", "be"])],
  "gap": [
    ("My father ___ (drive) to work every day.", ["drives"]),
    ("There ___ (not be) a park near my house.", ["isn't", "is not"]),
    ("She ___ (not eat) meat.", ["doesn't eat", "does not eat"]),
    ("The shop ___ (open) at 9 o'clock every morning.", ["opens"]),
    ("___ (do) they live near the school? — Yes, they do.", ["Do"])]},
2: {"mc": [
    ("Be quiet! The baby ___.", ["is sleeping", "sleeps", "sleep"]),
    ("I ___ your sister. She's in my class.", ["know", "am knowing", "knowing"]),
    ("Look! It ___ outside.", ["is snowing", "snows", "snow"]),
    ("This soup ___ delicious.", ["tastes", "is tasting", "taste"]),
    ("What ___ you doing at the moment?", ["are", "do", "is"])],
  "gap": [
    ("Listen! Somebody ___ (knock) at the door.", ["is knocking"]),
    ("I ___ (not want) any more tea, thanks.", ["don't want", "do not want"]),
    ("We ___ (study) for our exams this week.", ["are studying"]),
    ("She usually walks to school, but today she ___ (take) the bus.", ["is taking"]),
    ("This bag ___ (belong) to my sister.", ["belongs"])]},
3: {"mc": [
    ("My aunt's daughter is my ___.", ["cousin", "niece", "sister"]),
    ("Ali and Vali were born on the same day. They are ___.", ["twins", "cousins", "neighbours"]),
    ("I ___ my little brother when my mum is at work.", ["look after", "look like", "grow up"]),
    ("My brother's son is my ___.", ["nephew", "niece", "uncle"]),
    ("She isn't married. She is ___.", ["single", "only", "alone"])],
  "gap": [
    ("My ___ (bobo va buvi) live in a village near Samarkand.", ["grandparents"]),
    ("Our ___ (qo'shni) helped us carry the boxes.", ["neighbour", "neighbor"]),
    ("I have no brothers or sisters. I'm an ___ (yolg'iz farzand).", ["only child"]),
    ("My father's brother is my ___ (amaki).", ["uncle"]),
    ("You ___ (... ga o'xshamoq) your father. You have the same smile.", ["look like"])]},
4: {"mc": [
    ("We ___ basketball after school on Tuesday.", ["played", "play", "playing"]),
    ("She ___ the museum last summer.", ["visited", "visits", "visit"]),
    ("I didn't ___ my grandmother last weekend.", ["visit", "visited", "visiting"]),
    ("___ you watch the match on Saturday?", ["Did", "Do", "Were"]),
    ("They moved to Bukhara two years ___.", ["ago", "last", "before"])],
  "gap": [
    ("The bus ___ (stop) outside the hospital.", ["stopped"]),
    ("My little brother ___ (cry) all night.", ["cried"]),
    ("We ___ (not enjoy) the film.", ["didn't enjoy", "did not enjoy"]),
    ("I ___ (plan) a trip to Khiva last month.", ["planned"]),
    ("She ___ (arrive) home at ten o'clock last night.", ["arrived"])]},
5: {"mc": [
    ("I ___ at home all day yesterday.", ["was", "were", "am"]),
    ("They ___ very tired after the trip.", ["were", "was", "did"]),
    ("We ___ a lot of photos in Samarkand.", ["took", "taked", "take"]),
    ("___ you at school on Monday?", ["Were", "Was", "Did"]),
    ("He ___ his keys at the café.", ["left", "leaved", "leave"])],
  "gap": [
    ("Aziz ___ (buy) some bread at the bakery this morning.", ["bought"]),
    ("She ___ (write) a letter to her grandmother.", ["wrote"]),
    ("We ___ (not be) at the party.", ["weren't", "were not"]),
    ("My dad ___ (go) to Tashkent by train.", ["went"]),
    ("They ___ (eat) plov for lunch.", ["ate"])]},
6: {"mc": [
    ("My uncle likes to ___ old cars. He has twelve!", ["collect", "join", "relax"]),
    ("On Friday evenings I ___ with my friends in the park.", ["hang out", "go camping", "collect"]),
    ("She is very ___ drawing. Her pictures are beautiful.", ["good at", "interested", "bored"]),
    ("Monopoly is my favourite ___.", ["board game", "hobby club", "free time"]),
    ("The film was so ___ that I fell asleep.", ["boring", "exciting", "interested"])],
  "gap": [
    ("I don't have much ___ (bo'sh vaqt) because I have a lot of homework.", ["free time", "spare time"]),
    ("I want to ___ (a'zo bo'lmoq) the chess club.", ["join"]),
    ("Every summer we ___ (chodirda dam olishga bormoq) in the mountains.", ["go camping"]),
    ("After school I listen to music and ___ (dam olmoq).", ["relax"]),
    ("My favourite ___ (sevimli mashg'ulot) is photography.", ["hobby"])]},
7: {"mc": [
    ("At 8 o'clock last night I ___ TV.", ["was watching", "watched", "am watching"]),
    ("The children ___ in the garden when their dad came home.", ["were playing", "was playing", "played"]),
    ("What ___ you doing at 10 am yesterday?", ["were", "was", "did"]),
    ("While I was walking home, I ___ my teacher.", ["saw", "was seeing", "see"]),
    ("She ___ sleeping when the phone rang.", ["wasn't", "weren't", "didn't"])],
  "gap": [
    ("I ___ (read) a book when the lights went out.", ["was reading"]),
    ("We ___ (have) dinner at seven o'clock yesterday evening.", ["were having"]),
    ("Tom fell while he ___ (run) in the park.", ["was running"]),
    ("It ___ (rain) when we left the house.", ["was raining"]),
    ("The children ___ (not listen) to the teacher.", ["weren't listening", "were not listening"])]},
8: {"mc": [
    ("___ your hands before lunch, children!", ["Wash", "Washing", "To wash"]),
    ("I enjoy ___ in the sea.", ["swimming", "to swim", "swim"]),
    ("She decided ___ a new bike.", ["to buy", "buying", "buy"]),
    ("___ late for the lesson!", ["Don't be", "Not be", "Don't being"]),
    ("I heard him ___ the door.", ["open", "to open", "opens"])],
  "gap": [
    ("We hope ___ (visit) London next year.", ["to visit"]),
    ("Do you mind ___ (wait) for a few minutes?", ["waiting"]),
    ("My sister wants ___ (become) a doctor.", ["to become"]),
    ("He finished ___ (clean) his room at six.", ["cleaning"]),
    ("I saw the boys ___ (play) in the street.", ["play", "playing"])]},
9: {"mc": [
    ("The ___ blew his whistle and stopped the game.", ["referee", "coach", "fan"]),
    ("Our team ___ the champions 3–1!", ["beat", "won", "scored"]),
    ("Thousands of ___ watched the match in the stadium.", ["fans", "players", "coaches"]),
    ("Basketball is played on a ___, not on a pitch.", ["court", "stadium", "race"]),
    ("Who ___ the race yesterday?", ["won", "beat", "scored"])],
  "gap": [
    ("Our ___ (murabbiy) tells us to train hard.", ["coach"]),
    ("There are eleven ___ (o'yinchilar) in a football team.", ["players"]),
    ("He ___ (urdi) a great goal in the last minute.", ["scored"]),
    ("We ___ (mashq qilmoq) three times a week.", ["train"]),
    ("She became the world ___ (chempion) last year.", ["champion"])]},
10: {"mc": [
    ("My grandparents ___ never flown on a plane.", ["have", "has", "are"]),
    ("She has ___ her homework.", ["done", "did", "do"]),
    ("Have you ___ ridden a horse?", ["ever", "yet", "since"]),
    ("They haven't arrived ___.", ["yet", "already", "ever"]),
    ("He ___ just left the office.", ["has", "have", "is"])],
  "gap": [
    ("We ___ (see) this film three times.", ["have seen", "'ve seen"]),
    ("Oh no! She ___ (lose) her keys again!", ["has lost", "'s lost"]),
    ("I ___ (not finish) the book yet.", ["haven't finished", "have not finished"]),
    ("Look! My parents ___ (buy) a new car.", ["have bought", "'ve bought"]),
    ("Tom ___ (write) three emails today, and it's only 10 am.", ["has written", "'s written"])]},
11: {"mc": [
    ("I have lived here ___ 2015.", ["since", "for", "ago"]),
    ("She has worked at the bank ___ ten years.", ["for", "since", "ago"]),
    ("We ___ to Khiva last summer.", ["went", "have gone", "have been"]),
    ("How long ___ you known Aziz?", ["have", "did", "are"]),
    ("I ___ him yesterday.", ["met", "have met", "meet"])],
  "gap": [
    ("They ___ (be) married for twenty years.", ["have been", "'ve been"]),
    ("I ___ (see) Madina two days ago.", ["saw"]),
    ("He has had this phone ___ (for / since) three months.", ["for"]),
    ("We ___ (not see) our cousins since the wedding.", ["haven't seen", "have not seen"]),
    ("She ___ (start) school in 2019.", ["started"])]},
12: {"mc": [
    ("Maths is my favourite ___.", ["subject", "term", "timetable"]),
    ("We have a 20-minute ___ between lessons.", ["break", "term", "mark"]),
    ("Before the exam, I ___ all the new words at home.", ["revised", "failed", "took"]),
    ("She got a very good ___ in English: a five!", ["mark", "subject", "uniform"]),
    ("You can borrow books from the school ___.", ["library", "canteen", "lab"])],
  "gap": [
    ("Our ___ (maktab direktori) is very kind.", ["head teacher", "headteacher"]),
    ("Our ___ (oshxona) serves hot soup every day.", ["canteen"]),
    ("I was happy because I ___ (topshirdim, o'tdim) the exam.", ["passed"]),
    ("According to our ___ (dars jadvali), we have English on Thursday.", ["timetable"]),
    ("All pupils wear a school ___ (forma).", ["uniform"])]},
13: {"mc": [
    ("Look at that car! It ___ crash!", ["is going to", "will", "going to"]),
    ("I'm tired. I think I ___ go to bed.", ["will", "am going", "going to"]),
    ("My cousins ___ stay with us in July. They've already bought the tickets.", ["are going to", "will", "going"]),
    ("___ you carry this box for me, please?", ["Will", "Are", "Going"]),
    ("I'm sorry. I ___ be late again, I promise.", ["won't", "am not", "don't"])],
  "gap": [
    ("I think Uzbekistan ___ (win) the match.", ["will win", "'ll win"]),
    ("My brother ___ (become) a pilot. He has already decided.", ["is going to become", "'s going to become"]),
    ("The phone is ringing. I ___ (answer) it.", ["will answer", "'ll answer"]),
    ("Watch out! That dog ___ (bite) you!", ["is going to bite", "'s going to bite", "will bite"]),
    ("I promise I ___ (bring) your book back on Monday.", ["will bring", "'ll bring"])]},
14: {"mc": [
    ("This is my bag. It's ___.", ["mine", "my", "me"]),
    ("Can you help ___? We're lost.", ["us", "we", "our"]),
    ("The children did the work ___.", ["themselves", "theirselves", "them"]),
    ("That is ___ car, not ours.", ["their", "theirs", "them"]),
    ("This is ___ bike.", ["my sister's", "my sisters", "my sister"])],
  "gap": [
    ("Tell ___ (she) the news.", ["her"]),
    ("This isn't my pen. Is it ___ (you)?", ["yours"]),
    ("He hurt ___ (he) when he fell.", ["himself"]),
    ("The bird is building ___ (it) nest.", ["its"]),
    ("___ (we) teacher is from London.", ["Our"])]},
15: {"mc": [
    ("A ___ looks after people in hospital.", ["nurse", "chef", "mechanic"]),
    ("She works only in the mornings. It's a ___ job.", ["part-time", "full-time", "unemployed"]),
    ("My grandfather stopped working at 60. He ___.", ["retired", "applied", "earned"]),
    ("I sent my ___ to the company and they called me.", ["CV", "salary", "boss"]),
    ("He lost his job and now he is ___.", ["unemployed", "retired", "part-time"])],
  "gap": [
    ("My ___ (hamkasb) and I have lunch together.", ["colleague"]),
    ("How much money do you ___ (ishlab topmoq) a month?", ["earn"]),
    ("I want to ___ (... ga ariza bermoq) this job.", ["apply for"]),
    ("A ___ (oshpaz) works in a restaurant kitchen.", ["chef", "cook"]),
    ("The job ___ (suhbat, intervyu) is tomorrow at 10.", ["interview"])]},
16: {"mc": [
    ("The train ___ at 7.15 tomorrow morning.", ["leaves", "leave", "left"]),
    ("I ___ my dentist on Friday. I made an appointment.", ["am seeing", "see", "sees"]),
    ("What time ___ the film start tonight?", ["does", "is", "do"]),
    ("We ___ a party next Saturday. Can you come?", ["are having", "have", "has"]),
    ("The museum ___ at 6 pm on Sundays.", ["closes", "close", "closed"])],
  "gap": [
    ("My flight ___ (arrive) at 11 pm tonight.", ["arrives"]),
    ("I ___ (meet) Sara at the café at five. We've arranged it.", ["am meeting", "'m meeting"]),
    ("They ___ (fly) to Istanbul next Monday. They have the tickets.", ["are flying", "'re flying"]),
    ("The lesson ___ (begin) at 8.30 tomorrow.", ["begins"]),
    ("She ___ (not work) this Saturday. She's going to a wedding.", ["isn't working", "is not working"])]},
17: {"mc": [
    ("You ___ use your phone during the exam. It's against the rules.", ["mustn't", "don't have to", "can"]),
    ("___ I open the window, please?", ["May", "Am", "Have"]),
    ("You have a cough. You ___ drink hot tea with honey.", ["should", "mustn't", "can't"]),
    ("When I was five, I ___ swim.", ["could", "can", "must"]),
    ("It's a holiday tomorrow, so we ___ wear our uniform.", ["don't have to", "mustn't", "can't"])],
  "gap": [
    ("I can't come tonight. I ___ (majburman) study for the exam.", ["have to", "must"]),
    ("I'm not sure, but I ___ (balki) go to the cinema tonight.", ["might", "may"]),
    ("___ (qila olasanmi) you speak Chinese? — No, I can't.", ["Can"]),
    ("You ___ (shart emas) bring food. We have a lot.", ["don't have to", "do not have to", "needn't"]),
    ("You ___ (maslahat: kerak) eat more fruit.", ["should"])]},
18: {"mc": [
    ("Ask the ___. She works here and knows all the prices.", ["shop assistant", "customer", "receipt"]),
    ("It was only 5 dollars! What a ___!", ["bargain", "receipt", "queue"]),
    ("Keep the ___ in case you want to return it.", ["receipt", "change", "price"]),
    ("We waited in a long ___ at the supermarket.", ["queue", "sale", "change"]),
    ("We buy fresh bread every morning at the ___.", ["bakery", "chemist's", "bank"])],
  "gap": [
    ("These shoes ___ (turadi) 300,000 sums.", ["cost"]),
    ("This phone is too ___ (qimmat). I can't buy it.", ["expensive"]),
    ("Can I pay by ___ (karta)?", ["card"]),
    ("Here's your ___ (qaytim): two thousand sums.", ["change"]),
    ("I ___ (sarflamoq) too much money on clothes.", ["spend"])]},
19: {"mc": [
    ("This mosque ___ in the 16th century.", ["was built", "built", "is build"]),
    ("English ___ in many countries.", ["is spoken", "speaks", "is speaking"]),
    ("The letters ___ every morning.", ["are delivered", "deliver", "is delivered"]),
    ("The window ___ by a football yesterday.", ["was broken", "broke", "is broken"]),
    ("Plov ___ with rice, meat and carrots.", ["is made", "makes", "is making"])],
  "gap": [
    ("Silk ___ (produce) in Margilan.", ["is produced"]),
    ("The windows ___ (clean) last week.", ["were cleaned"]),
    ("This song ___ (write) by a famous singer in 2010.", ["was written"]),
    ("Cars ___ (not allow) in the old city.", ["aren't allowed", "are not allowed"]),
    ("The museum ___ (visit) by thousands of people every year.", ["is visited"])]},
20: {"mc": [
    ("I saw ___ elephant at the zoo.", ["an", "a", "the"]),
    ("___ Moon goes around the Earth.", ["The", "A", "An"]),
    ("She is ___ doctor.", ["a", "an", "the"]),
    ("Can you close ___ door, please?", ["the", "a", "an"]),
    ("He plays ___ guitar very well.", ["the", "a", "an"])],
  "gap": [
    ("I have ___ (a / an / the) idea!", ["an"]),
    ("There is ___ (a / an / the) cat on the roof.", ["a"]),
    ("Tashkent is ___ (a / an / the) capital of Uzbekistan.", ["the"]),
    ("She is ___ (a / an / the) honest girl.", ["an"]),
    ("Look at ___ (a / an / the) moon! It's beautiful.", ["the"])]},
21: {"mc": [
    ("Navruz is a spring ___.", ["festival", "costume", "guest"]),
    ("The ___ wore a beautiful white dress.", ["bride", "groom", "guest"]),
    ("We ___ the room with flowers and balloons.", ["decorated", "celebrated", "invited"]),
    ("There were ___ in the sky at midnight.", ["fireworks", "parades", "costumes"]),
    ("Atlas is a ___ Uzbek fabric.", ["traditional", "fashionable", "foreign"])],
  "gap": [
    ("How do you ___ (nishonlamoq) your birthday?", ["celebrate"]),
    ("We had 300 ___ (mehmonlar) at the wedding.", ["guests"]),
    ("Did you get an ___ (taklifnoma) to the party?", ["invitation"]),
    ("The ___ (kuyov) arrived with his family.", ["groom", "bridegroom"]),
    ("Children wore funny ___ (kostyumlar) at the festival.", ["costumes"])]},
22: {"mc": [
    ("I'd like some ___ in my tea.", ["milk", "milks", "a milk"]),
    ("I need some new ___.", ["jeans", "jean", "a jeans"]),
    ("There ___ a lot of furniture in this room.", ["is", "are", "be"]),
    ("She gave me some good ___.", ["advice", "advices", "an advice"]),
    ("How many ___ are there in your class?", ["students", "student", "studentes"])],
  "gap": [
    ("The news ___ (be) very good today.", ["is"]),
    ("My trousers ___ (be) too long.", ["are"]),
    ("We need two ___ (loaf) of bread.", ["loaves"]),
    ("Can you give me some ___ (information) about the trip?", ["information"]),
    ("I bought three ___ (box) of chocolates.", ["boxes"])]},
23: {"mc": [
    ("There isn't ___ milk in the fridge.", ["much", "many", "a few"]),
    ("I have ___ friends in London, so I'm not alone there.", ["a few", "a little", "much"]),
    ("How ___ money do you need?", ["much", "many", "few"]),
    ("We've got ___ time. Let's have a cup of tea.", ["a little", "a few", "many"]),
    ("There are ___ people at the concert.", ["lots of", "much", "a little"])],
  "gap": [
    ("How ___ (much / many) brothers have you got?", ["many"]),
    ("Could I have a ___ (little / few) sugar in my tea?", ["little"]),
    ("I don't have ___ (much / many) homework today.", ["much"]),
    ("She only has a ___ (little / few) close friends.", ["few"]),
    ("There are a ___ (lot / much) of shops in the centre.", ["lot"])]},
24: {"mc": [
    ("Excuse me, can I ___ this jacket in the changing room?", ["try on", "take off", "wear out"]),
    ("This jacket is too big. It doesn't ___ me.", ["fit", "suit", "wear"]),
    ("It's cold. Wear your ___ and gloves.", ["scarf", "trainers", "skirt"]),
    ("Green really ___ you. It goes with your eyes.", ["suits", "fits", "tries"]),
    ("My grandad's hat is very ___. Nobody wears hats like that now.", ["old-fashioned", "fashionable", "tight"])],
  "gap": [
    ("Do you have these boots in a bigger ___ (o'lcham)?", ["size"]),
    ("She always wears beautiful ___ (taqinchoqlar).", ["jewellery", "jewelry"]),
    ("Please ___ (yechmoq) your shoes at the door.", ["take off"]),
    ("These trousers are too ___ (tor). I need a bigger size.", ["tight"]),
    ("I bought new ___ (krossovkalar) for running.", ["trainers"])]},
25: {"mc": [
    ("A giraffe is ___ than a horse.", ["taller", "more tall", "tallest"]),
    ("For me, history is ___ than physics.", ["more interesting", "interestinger", "most interesting"]),
    ("Today is ___ than yesterday.", ["hotter", "hoter", "more hot"]),
    ("Our flat isn't as big ___ your house.", ["as", "than", "so"]),
    ("Your English is ___ than mine.", ["better", "gooder", "more good"])],
  "gap": [
    ("A plane is ___ (fast) than a train.", ["faster"]),
    ("This exercise is ___ (easy) than the last one.", ["easier"]),
    ("My cold is ___ (bad) today than it was yesterday.", ["worse"]),
    ("Gold is ___ (expensive) than silver.", ["more expensive"]),
    ("My bag is as ___ (heavy) as yours.", ["heavy"])]},
26: {"mc": [
    ("The cheetah is the ___ animal on land.", ["fastest", "faster", "most fast"]),
    ("This is the ___ film I have ever seen.", ["best", "better", "goodest"]),
    ("She is the ___ student in our class.", ["most intelligent", "intelligentest", "more intelligent"]),
    ("It was the ___ day of the year.", ["hottest", "hotest", "most hot"]),
    ("Who is the youngest person ___ your family?", ["in", "than", "at"])],
  "gap": [
    ("The Nile is the ___ (long) river in Africa.", ["longest"]),
    ("That was the ___ (bad) day of my life!", ["worst"]),
    ("The blue whale is the ___ (big) animal in the world.", ["biggest"]),
    ("This is the ___ (beautiful) place I know.", ["most beautiful"]),
    ("Friday is the ___ (busy) day of the week.", ["busiest"])]},
27: {"mc": [
    ("You can see old paintings in the art ___.", ["gallery", "station", "market"]),
    ("I need to send a parcel. Where is the ___?", ["post office", "police station", "hotel"]),
    ("We watched a play at the ___.", ["theatre", "bank", "mosque"]),
    ("You can take a plane at the ___.", ["airport", "railway station", "bridge"]),
    ("I bought fresh fruit and vegetables at the ___.", ["market", "museum", "library"])],
  "gap": [
    ("The ___ (kasalxona) is next to the park. Doctors and nurses work there.", ["hospital"]),
    ("Our ___ (mehmonxona) had a swimming pool on the roof.", ["hotel"]),
    ("We saw very old coins in the ___ (muzey).", ["museum"]),
    ("Let's walk across the ___ (ko'prik) to the other side of the river.", ["bridge"]),
    ("Trains leave from the ___ (temir yo'l vokzali) every hour.", ["railway station", "train station"])]},
28: {"mc": [
    ("She sings very ___.", ["beautifully", "beautiful", "beauty"]),
    ("He drives too ___.", ["fast", "fastly", "fastest"]),
    ("I ___ go to the gym on Mondays.", ["usually", "usual", "usualy"]),
    ("Please speak more ___.", ["slowly", "slow", "slowlier"]),
    ("You did the test very ___. Well done!", ["well", "good", "goodly"])],
  "gap": [
    ("Walk ___ (quiet). The baby is sleeping.", ["quietly"]),
    ("He works very ___ (hard).", ["hard"]),
    ("She answered the question ___ (correct).", ["correctly"]),
    ("They arrived ___ (late) for the lesson.", ["late"]),
    ("Can you write more ___ (careful)?", ["carefully"])]},
29: {"mc": [
    ("My birthday is ___ May.", ["in", "on", "at"]),
    ("The lesson starts ___ 9 o'clock.", ["at", "in", "on"]),
    ("The cat jumped ___ the table.", ["onto", "into", "at"]),
    ("The children ran ___ the road to the park.", ["across", "into", "between"]),
    ("The bank is ___ the café and the post office.", ["between", "among", "across"])],
  "gap": [
    ("See you ___ (at / on / in) Monday!", ["on"]),
    ("My brother was born ___ (at / on / in) 2015.", ["in"]),
    ("She put the milk ___ (into / onto) the fridge.", ["into", "in"]),
    ("Your phone is ___ (at / on / in) the sofa.", ["on"]),
    ("We have lunch ___ (at / on / in) noon.", ["at"])]},
30: {"mc": [
    ("Passengers for Samarkand, please go to ___ 2.", ["platform", "passport", "luggage"]),
    ("We ___ the bus because we were late.", ["missed", "caught", "booked"]),
    ("Please show your ___ at the border.", ["passport", "platform", "departure"]),
    ("The flight had a two-hour ___ because of the snow.", ["delay", "trip", "journey"]),
    ("We went ___ in Rome and saw the Colosseum.", ["sightseeing", "abroad", "luggage"])],
  "gap": [
    ("I ___ (bron qildim) a hotel room online.", ["booked"]),
    ("How much ___ (yuk, bagaj) do you have?", ["luggage"]),
    ("We need to ___ (tushmoq) the bus at the next stop.", ["get off"]),
    ("The ___ (yo'l, safar) to the mountains was long but beautiful.", ["journey", "trip"]),
    ("My aunt works ___ (chet elda), in Korea.", ["abroad"])]},
31: {"mc": [
    ("If it rains, we ___ at home.", ["will stay", "stay will", "would stay"]),
    ("If you heat water to 100 degrees, it ___.", ["boils", "will boils", "boiled"]),
    ("___ you leave now, you'll miss the bus.", ["Unless", "If", "When"]),
    ("I'll call you as soon as I ___ home.", ["get", "will get", "got"]),
    ("If she ___ the bus, she will be late.", ["misses", "will miss", "missed"])],
  "gap": [
    ("If you ___ (not hurry), you'll miss the train.", ["don't hurry", "do not hurry"]),
    ("If I see Ali, I ___ (tell) him.", ["will tell", "'ll tell"]),
    ("We ___ (go) to the park if the weather is nice.", ["will go", "'ll go"]),
    ("If you mix red and blue, you ___ (get) purple.", ["get"]),
    ("When I ___ (finish) my homework, I'll watch TV.", ["finish"])]},
32: {"mc": [
    ("If I ___ rich, I would travel the world.", ["were", "am", "will be"]),
    ("If she had more time, she ___ learn Spanish.", ["would", "will", "can"]),
    ("If I ___ his phone number, I would call him.", ["knew", "know", "would know"]),
    ("I ___ eat that fish if I were you. It smells bad.", ["wouldn't", "won't", "don't"]),
    ("If my grandma lived closer, I ___ visit her every day.", ["would", "will", "did"])],
  "gap": [
    ("If I ___ (have) a dog, I would walk it every day.", ["had"]),
    ("If he studied more, he ___ (pass) the exam.", ["would pass", "'d pass"]),
    ("If I ___ (be) you, I'd see a doctor.", ["were", "was"]),
    ("She ___ (not be) so tired if she went to bed earlier.", ["wouldn't be", "would not be"]),
    ("If they ___ (live) in London, they would speak English every day.", ["lived"])]},
33: {"mc": [
    ("I have a terrible ___. I can't eat anything.", ["stomach ache", "sore throat", "cough"]),
    ("You have a high ___. Stay in bed.", ["temperature", "appointment", "diet"]),
    ("I called the clinic to make an ___.", ["appointment", "exercise", "medicine"]),
    ("He goes to the ___ three times a week to keep fit.", ["gym", "chemist's", "diet"]),
    ("I ate too much and ___ weight.", ["put on", "lost", "got better"])],
  "gap": [
    ("The doctor gave me some ___ (dori) for my cough.", ["medicine"]),
    ("My leg ___ (og'riyapti) after the match.", ["hurts"]),
    ("I was ill last week, but now I'm ___ (tuzalmoq) better.", ["getting"]),
    ("Fruit and vegetables are ___ (foydali, sog'lom) food.", ["healthy"]),
    ("I can't talk. I've got a ___ (tomoq og'rig'i).", ["sore throat"])]},
34: {"mc": [
    ("It was ___ a good film that I watched it twice.", ["such", "so", "too"]),
    ("The test was ___ easy!", ["so", "such", "such an"]),
    ("I don't like coffee. — ___ do I.", ["Neither", "So", "Either"]),
    ("I love football. — ___ do I.", ["So", "Neither", "Such"]),
    ("She can't swim, and I can't ___.", ["either", "neither", "too"])],
  "gap": [
    ("He is ___ (so / such) a kind man.", ["such"]),
    ("It's ___ (so / such) cold today!", ["so"]),
    ("I'm hungry. — So ___ (be) I.", ["am"]),
    ("I didn't go to the party. — Neither ___ (do) I.", ["did"]),
    ("I like tea. — I do, ___ (too / either).", ["too"])]},
35: {"mc": [
    ("You're from Samarkand, ___?", ["aren't you", "are you", "don't you"]),
    ("Your dad doesn't drive, ___?", ["does he", "doesn't he", "is he"]),
    ("They went to the cinema, ___?", ["didn't they", "did they", "weren't they"]),
    ("He can drive, ___?", ["can't he", "can he", "doesn't he"]),
    ("It isn't cold today, ___?", ["is it", "isn't it", "does it"])],
  "gap": [
    ("You play the piano, ___ (do) you?", ["don't"]),
    ("She has finished, ___ (have) she?", ["hasn't"]),
    ("They aren't at home, ___ (be) they?", ["are"]),
    ("Tom was at school yesterday, ___ (be) he?", ["wasn't"]),
    ("She will come tomorrow, ___ (will) she?", ["won't"])]},
36: {"mc": [
    ("My old laptop's ___ lasts only two hours now.", ["battery", "keyboard", "website"]),
    ("Don't tell anyone your ___.", ["password", "screen", "charger"]),
    ("I ___ a new game from the internet.", ["downloaded", "subscribed", "posted"]),
    ("She ___ a photo of her cat on Instagram.", ["posted", "searched", "charged"]),
    ("I can't find my laptop ___. Can I borrow yours?", ["charger", "password", "message"])],
  "gap": [
    ("I sent you a ___ (xabar) an hour ago.", ["message"]),
    ("You can buy tickets on our ___ (veb-sayt).", ["website"]),
    ("Let's ___ (qidirmoq) for the answer online.", ["search"]),
    ("This ___ (ilova) helps me learn English words.", ["app"]),
    ("The ___ (ekran) of my phone is broken.", ["screen"])]},
37: {"mc": [
    ("The woman ___ works in the bakery is my aunt.", ["who", "which", "where"]),
    ("That's the film ___ everyone is talking about.", ["that", "who", "where"]),
    ("That's the café ___ we first met.", ["where", "which", "who"]),
    ("I have a friend ___ brother is a pilot.", ["whose", "who", "which"]),
    ("The bike ___ my dad gave me is red.", ["which", "who", "whose"])],
  "gap": [
    ("A teacher is a person ___ (who / which) teaches students.", ["who", "that"]),
    ("That's the school ___ (where / which) my mother teaches.", ["where"]),
    ("The dog ___ (who / which) bit me was very big.", ["which", "that"]),
    ("She's the girl ___ (who / whose) mother is our teacher.", ["whose"]),
    ("Is this the bus ___ (which / where) goes to the airport?", ["which", "that"])]},
38: {"mc": [
    ("When I called, she ___ already gone to bed.", ["had", "has", "was"]),
    ("She was sad because she ___ her phone.", ["had lost", "has lost", "lose"]),
    ("I ___ never seen snow before I went to Moscow.", ["had", "have", "was"]),
    ("After they ___ lunch, they went for a walk.", ["had eaten", "have eaten", "eating"]),
    ("By the time the doctor arrived, the pain ___.", ["had stopped", "has stopped", "stops"])],
  "gap": [
    ("They ___ (eat) all the cake before we came.", ["had eaten", "'d eaten"]),
    ("I ___ (not meet) him before the party.", ["hadn't met", "had not met"]),
    ("I didn't know the city because I ___ (not be) there before.", ["hadn't been", "had not been"]),
    ("When we reached the cinema, all the tickets ___ (sell) out.", ["had sold", "had been sold"]),
    ("He told me he ___ (visit) Khiva twice before.", ["had visited", "'d visited"])]},
39: {"mc": [
    ("It's ___ today. Take your umbrella.", ["rainy", "sunny", "foggy"]),
    ("The Sahara is a hot ___.", ["desert", "forest", "lake"]),
    ("According to the ___, tomorrow will be sunny.", ["forecast", "degrees", "storm"]),
    ("It's minus ten degrees. It's ___!", ["freezing", "sunny", "windy"]),
    ("There are thousands of trees in the ___.", ["forest", "desert", "coast"])],
  "gap": [
    ("In winter it can be minus 10 ___ (daraja) here.", ["degrees"]),
    ("The Amu Darya is a long ___ (daryo).", ["river"]),
    ("We climbed a high ___ (tog').", ["mountain"]),
    ("A big ___ (bo'ron) broke many trees last night.", ["storm"]),
    ("I can't see the road. It's very ___ (tumanli).", ["foggy"])]},
40: {"mc": [
    ("She said that she ___ tired.", ["was", "is", "be"]),
    ("He ___ me that he liked the film.", ["told", "said", "says"]),
    ("Tom said he ___ come to the party.", ["would", "will to", "coming"]),
    ("They said they ___ in London the day before.", ["had been", "have been", "are"]),
    ("She ___ that she was hungry.", ["said", "told", "talked"])],
  "gap": [
    ("'I live in Tashkent.' → He said he ___ (live) in Tashkent.", ["lived"]),
    ("'I am busy.' → She said she ___ (be) busy.", ["was"]),
    ("'We will call you.' → They said they ___ (will) call me.", ["would"]),
    ("'I can swim.' → He said he ___ (can) swim.", ["could"]),
    ("Ali ___ (say / tell) me that he was ill.", ["told"])]},
41: {"mc": [
    ("I ___ to school every day.", ["walk", "am walk", "walking"]),
    ("Look! The children ___ in the garden.", ["are playing", "play", "played"]),
    ("We ___ in Bukhara in 2020.", ["lived", "have lived", "live"]),
    ("I ___ this film before. It's great.", ["have seen", "am seeing", "see"]),
    ("While she was cooking, the phone ___.", ["rang", "was ring", "rings"])],
  "gap": [
    ("Tomorrow I ___ (visit) my grandma. I've already decided.", ["am going to visit", "'m going to visit", "am visiting", "'m visiting"]),
    ("She ___ (live) here since 2018.", ["has lived", "has been living", "'s lived"]),
    ("What ___ (be) you doing at 9 o'clock last night?", ["were"]),
    ("He usually ___ (get up) at seven.", ["gets up"]),
    ("When I woke up, my parents ___ (go) to work already.", ["had gone", "'d gone"])]},
42: {"mc": [
    ("We should ___ plastic bottles, not throw them away.", ["recycle", "pollute", "protect"]),
    ("Many animals are ___ because people destroy their homes.", ["endangered", "recycled", "saved"]),
    ("Dirty water from factories causes river ___.", ["pollution", "poverty", "hunger"]),
    ("There was no rain for months, so there was a ___.", ["drought", "flood", "earthquake"]),
    ("Use less hot water to ___ energy.", ["save", "waste", "protect"])],
  "gap": [
    ("Don't drop ___ (axlat) in the street.", ["rubbish", "litter", "trash"]),
    ("We must ___ (himoya qilmoq) the environment.", ["protect"]),
    ("Many people suffer from ___ (ochlik) during a war.", ["hunger"]),
    ("___ (qashshoqlik) is a big problem in some countries.", ["Poverty"]),
    ("After the heavy rain there was a ___ (suv toshqini).", ["flood"])]},
}

# Spare multiple-choice items. The build drops any book test item that repeats a practice sentence word for word,
# and fills its place from here so every unit test keeps 20 unseen questions.
SPARE = {
3: [("My mother's mother is my ___.", ["grandmother", "aunt", "niece"])],
5: [("Where ___ you last summer?", ["were", "was", "did"])],
6: [("I'm ___ in history. I read a lot about it.", ["interested", "interesting", "good"]),
    ("Let's ___ tonight. There's a good film at the cinema.", ["go out", "relax", "collect"]),
    ("My sister can ___ the piano and the violin.", ["play", "draw", "join"])],
9: [("The two best teams met in the final of the ___.", ["competition", "coach", "referee"])],
10: [("___ you finished your project yet?", ["Have", "Has", "Did"])],
11: [("I haven't seen my cousin ___ last year.", ["since", "for", "ago"])],
15: [("She has five years of ___ as a teacher.", ["experience", "salary", "interview"])],
18: [("There's a big ___ in this shop. Everything is 50% off!", ["sale", "queue", "receipt"])],
24: [("She wears a gold necklace and other ___.", ["jewellery", "gloves", "trainers"])],
25: [("Tashkent is ___ than Samarkand.", ["bigger", "biger", "more big"])],
27: [("You can watch a new film at the ___.", ["cinema", "bank", "post office"])],
39: [("There are many small islands near the ___ of Greece.", ["coast", "desert", "field"]),
     ("It's very ___ today. My hat flew away!", ["windy", "foggy", "sunny"])],
}
