# Units 29-42. Same format as units_a.py.

UNITS_C = [
{
 "n": 29, "title": "Prepositions of place, movement and time",
 "lesson": [
  ("Time: at, on, in", [
   "<b>at</b> + clock times and some phrases: at 7 o'clock, at night, at noon, at the moment",
   "<b>on</b> + days and dates: on Monday, on 5th May, on my birthday, on New Year's Day",
   "<b>in</b> + months, years, seasons, parts of the day: in July, in 2010, in winter, in the morning",
   "UZ: at – soat; on – kun, sana; in – oy, yil, fasl, kunning qismi."]),
  ("Place", [
   "<b>in</b> + inside a space: in the kitchen, in Tashkent · <b>on</b> + a surface: on the table, on the wall, on the second floor · <b>at</b> + a point: at home, at school, at the bus stop",
   "next to, between, opposite, behind, in front of, under, above",
   "UZ: next to – yonida; between – orasida; opposite – qarshisida; behind – orqasida; in front of – oldida; under – ostida; above – tepasida."]),
  ("Movement", [
   "<b>into / out of</b>: She went <b>into</b> the shop. He took his phone <b>out of</b> his bag.",
   "<b>up / down</b>: Go <b>up</b> the stairs. · <b>across / over</b>: Walk <b>across</b> the bridge. The dog jumped <b>over</b> the fence.",
   "<b>along</b>: We cycled <b>along</b> the river. · <b>through</b>: The train went <b>through</b> a tunnel. · <b>past</b>: Walk <b>past</b> the bank. · <b>towards</b>: He ran <b>towards</b> me.",
   "UZ: into – ichiga; out of – ichidan tashqariga; across – u tomoniga; along – bo'ylab; through – orqali, ichidan o'tib; past – yonidan o'tib."]),
 ],
 "ex": [
  ("Choose the correct preposition.", "mc", [
   ("The meeting is ___ Monday.", ["on", "in", "at"]),
   ("I was born ___ 2010.", ["in", "on", "at"]),
   ("See you ___ 7 o'clock.", ["at", "in", "on"]),
   ("The picture is ___ the wall.", ["on", "in", "at"]),
   ("She's ___ work right now.", ["at", "in", "on"]),
   ("We go skiing ___ winter.", ["in", "on", "at"]),
  ]),
  ("Complete with in, on or at.", "gap", [
   ("My birthday is ___ 5th May.", ["on"]),
   ("I usually read ___ the evening.", ["in"]),
   ("They live ___ Tashkent.", ["in"]),
   ("Wait for me ___ the bus stop.", ["at"]),
   ("I never go out ___ night.", ["at"]),
   ("The keys are ___ the table.", ["on"]),
  ]),
  ("Complete with a preposition of movement from the box.", "gap", [
   ("The cat ran ___ the house and hid under the bed.", ["into"]),
   ("We walked ___ the bridge to the other side.", ["across", "over"]),
   ("They cycled ___ the river for two hours.", ["along"]),
   ("He climbed ___ the tree to get the ball.", ["up"]),
   ("The train went ___ a long tunnel.", ["through"]),
   ("She took her phone ___ her bag.", ["out of"]),
  ], ["into", "across", "along", "up", "through", "out of"]),
 ],
 "test": [
  ("The shop opens ___ 9 am.", ["at", "in", "on"]),
  ("We have English ___ Tuesdays.", ["on", "in", "at"]),
  ("It's very hot here ___ July.", ["in", "on", "at"]),
  ("Is your brother ___ home?", ["at", "in", "on"]),
  ("Go ___ the stairs to the first floor.", ["up", "on", "at"]),
  ("My school is ___ the post office. It's across the street.", ["opposite", "between", "under"]),
  ("Put the milk ___ the fridge.", ["in", "on", "at"]),
  ("We met ___ New Year's Day.", ["on", "in", "at"]),
  ("The dog jumped ___ the fence.", ["over", "along", "at"]),
  ("She lives ___ the second floor.", ["on", "in", "at"]),
 ],
 "task": "Write directions from your school to your home (8 sentences): Go out of the school, walk along…, go past…, turn left…, cross… Then add 4 sentences about when you do things (at / on / in).",
},
{
 "n": 30, "title": "Travel",
 "words": [
  ("journey", "safar, yo'l", "The journey takes five hours."),
  ("trip", "sayohat (qisqa)", "We went on a school trip."),
  ("luggage", "yuk, bagaj", "Don't forget your luggage!"),
  ("passport", "pasport", "You need a passport to travel abroad."),
  ("ticket", "chipta", "A return ticket, please."),
  ("platform", "platforma", "The train leaves from platform 3."),
  ("get on / get off", "(transportga) chiqmoq / tushmoq", "Get off the bus at the next stop."),
  ("catch / miss", "ulgurmoq / ulgurmay qolmoq", "Hurry, or we'll miss the train!"),
  ("delay", "kechikish", "There's a two-hour delay."),
  ("departure / arrival", "jo'nash / yetib kelish", "Check the departure time."),
  ("abroad", "chet elda, chet elga", "Have you ever been abroad?"),
  ("sightseeing", "diqqatga sazovor joylarni ko'rish", "We went sightseeing in Khiva."),
  ("book", "band qilmoq", "We booked a hotel online."),
 ],
 "tip": "by bus / by train / by plane / by car — but on foot. get on / off a bus, train, plane — get in / out of a car or taxi.",
 "ex": [
  ("Choose the correct word.", "mc", [
   ("You need a ___ to travel to another country.", ["passport", "platform", "luggage"]),
   ("The train leaves from ___ 4.", ["platform", "station", "ticket"]),
   ("Bags and suitcases are called ___.", ["luggage", "tickets", "journey"]),
   ("We ___ the bus at the second stop.", ["got off", "got out", "got down"]),
   ("I was late and ___ the train.", ["missed", "lost", "caught"]),
   ("Let's ___ a hotel online.", ["book", "buy", "rent"]),
  ]),
  ("Complete with a word from the box.", "gap", [
   ("We went on a school ___ to Samarkand.", ["trip"]),
   ("The ___ from Tashkent to Khiva is long by train.", ["journey"]),
   ("There's a two-hour ___ because of the snow.", ["delay"]),
   ("Have you ever travelled ___?", ["abroad"]),
   ("Tourists love going ___ in Bukhara.", ["sightseeing"]),
   ("Check the ___ time of the plane on the board.", ["arrival", "departure"]),
  ], ["trip", "journey", "delay", "abroad", "sightseeing", "arrival"]),
  ("Complete with by, on, into or off.", "gap", [
   ("I go to school ___ bus.", ["by"]),
   ("We didn't drive. We went ___ foot.", ["on"]),
   ("They travelled to Moscow ___ plane.", ["by"]),
   ("Get ___ the train quickly — it's leaving!", ["on"]),
   ("She got ___ a taxi and went home.", ["into", "in"]),
   ("We got ___ the bus at the last stop.", ["off"]),
  ]),
 ],
 "test": [
  ("How was your ___ to Paris?", ["trip", "travel", "luggage"]),
  ("Don't forget your ___! You can't fly without it.", ["passport", "platform", "arrival"]),
  ("We ___ the plane at gate 12.", ["got on", "got in", "got up"]),
  ("I go to school ___ foot.", ["on", "by", "with"]),
  ("The flight has a ___ of three hours.", ["delay", "journey", "trip"]),
  ("They went ___ in the old city.", ["sightseeing", "sightsee", "sight"]),
  ("Hurry up or we'll ___ the bus!", ["miss", "lose", "leave"]),
  ("How much is a return ___ to Fergana?", ["ticket", "passport", "luggage"]),
  ("My brother works ___ — in Korea.", ["abroad", "outside", "away"]),
  ("We ___ a room at the hotel last week.", ["booked", "bought", "ordered"]),
 ],
 "task": "Plan a 3-day trip in Uzbekistan for a foreign friend (8–10 sentences). How will you travel? Where will you stay? What will you see?",
},
{
 "n": 31, "title": "First conditional",
 "lesson": [
  ("Zero conditional", [
   "If + present simple, present simple — for facts and things that are always true.",
   "If you heat ice, it melts. · If you mix blue and yellow, you get green.",
   "UZ: Har doim to'g'ri bo'ladigan faktlar uchun."]),
  ("First conditional", [
   "If + present simple, will + base verb — for real possibilities in the future.",
   "If it rains tomorrow, we<b>'ll stay</b> at home. · We<b>'ll stay</b> at home if it rains.",
   "Don't use <i>will</i> after <i>if</i>: ✔ If it rains ✘ If it will rain",
   "UZ: Kelajakda sodir bo'lishi mumkin bo'lgan real shart: if-qismida present simple, natijada will."]),
  ("unless / when / as soon as", [
   "<b>unless</b> = if not: You'll be late <b>unless</b> you hurry.",
   "<b>when</b> = we are sure it will happen: I'll call you <b>when</b> I get home.",
   "<b>as soon as</b> = immediately when: I'll text you <b>as soon as</b> I arrive.",
   "After these words, use the present simple for the future too."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("If you heat ice, it ___.", ["melts", "will melted", "melted"]),
   ("If it rains tomorrow, we ___ at home.", ["'ll stay", "stay", "stayed"]),
   ("If you ___ hard, you'll pass.", ["study", "will study", "studied"]),
   ("I'll call you when I ___ home.", ["get", "will get", "got"]),
   ("___ you hurry, you'll miss the train.", ["Unless", "If", "When"]),
   ("If you mix red and white, you ___ pink.", ["get", "got", "will got"]),
  ]),
  ("Put the verb in brackets in the correct form.", "gap", [
   ("If she ___ (come), I'll be happy.", ["comes"]),
   ("We ___ (go) to the beach if the weather is nice.", ["'ll go", "will go"]),
   ("If you don't eat, you ___ (be) hungry.", ["'ll be", "will be"]),
   ("If you press this button, the machine ___ (start).", ["starts"]),
   ("I won't go unless you ___ (go) too.", ["go"]),
   ("What ___ (you / do) if you miss the bus?", ["will you do"]),
  ]),
  ("Complete with if, unless or when.", "gap", [
   ("___ I see Aziz, I'll give him your message.", ["If", "When"]),
   ("You won't get fit ___ you do exercise.", ["unless"]),
   ("Plants die ___ they don't get water.", ["if", "when"]),
   ("___ you are late again, the teacher will be angry.", ["If"]),
   ("I'll text you ___ I arrive. (I'm sure I'll arrive.)", ["when"]),
  ]),
 ],
 "test": [
  ("If you ___ water to 100°C, it boils.", ["heat", "will heat", "heated"]),
  ("If I see her, I ___ her.", ["'ll tell", "tell", "told"]),
  ("She'll be angry if you ___ late.", ["are", "will be", "were"]),
  ("___ you study, you won't pass.", ["Unless", "If", "When"]),
  ("What will you do if it ___?", ["snows", "will snow", "snowed"]),
  ("If you don't sleep, you ___ tired.", ["'ll feel", "are feeling", "felt"]),
  ("I'll phone you as soon as I ___ the results.", ["get", "'ll get", "got"]),
  ("If people ___ enough water, they get headaches.", ["don't drink", "won't drink", "didn't drink"]),
  ("We ___ go out if it's too cold.", ["won't", "don't will", "not"]),
  ("If you ___ me, I'll help you.", ["help", "will help", "helped"]),
 ],
 "task": "Make a chain story: If I get up late tomorrow, I'll miss the bus. If I miss the bus, I'll… Write at least 6 linked sentences.",
},
{
 "n": 32, "title": "Second conditional",
 "lesson": [
  ("Form", [
   "If + past simple, would ('d) + base verb",
   "If I <b>had</b> a lot of money, I<b>'d travel</b> around the world.",
   "Negative: If I <b>didn't</b> live here, I <b>wouldn't</b> know him. · Question: What <b>would</b> you <b>do</b> if you <b>won</b> the lottery?",
   "With <i>be</i> we often use <b>were</b> for all persons: If I <b>were</b> rich… (If I was rich… is also used.)",
   "UZ: Hozirgi yoki kelajakdagi real bo'lmagan, xayoliy vaziyat: if + past simple, natijada would + fe'l."]),
  ("Use", [
   "Imaginary or unlikely situations now or in the future: If I <b>could</b> fly, I<b>'d go</b> to Japan.",
   "Advice: <b>If I were you</b>, I<b>'d</b> study more.",
   "Compare: If it <b>rains</b>, I<b>'ll</b> stay home (real, possible). If I <b>lived</b> by the sea, I<b>'d</b> swim every day (imaginary)."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("If I ___ a lot of money, I'd travel around the world.", ["had", "have", "would have"]),
   ("If she knew the answer, she ___ tell us.", ["would", "will", "is"]),
   ("If I ___ you, I'd study more.", ["were", "am", "be"]),
   ("What ___ you do if you saw a ghost?", ["would", "will", "did"]),
   ("I ___ buy that car if I were you. It's too expensive.", ["wouldn't", "won't", "don't"]),
   ("If we lived by the sea, we ___ swim every day.", ["would", "will", "did"]),
  ]),
  ("Put the verb in brackets in the correct form.", "gap", [
   ("If I ___ (be) taller, I'd play basketball.", ["were", "was"]),
   ("If he ___ (have) a car, he would drive to work.", ["had"]),
   ("She ___ (be) happier if she had more friends.", ["would be", "'d be"]),
   ("If they ___ (not / live) so far away, we'd visit them more often.", ["didn't live", "did not live"]),
   ("What ___ (you / do) if you won the lottery?", ["would you do"]),
   ("If I could fly, I ___ (go) to Japan.", ["would go", "'d go"]),
  ]),
  ("First or second conditional? Put the verb in the correct form.", "gap", [
   ("If it ___ (rain) tomorrow, we'll stay at home.", ["rains"]),
   ("If I ___ (be) a bird, I would fly over the mountains.", ["were", "was"]),
   ("If you study, you ___ (pass).", ["will pass", "'ll pass"]),
   ("If I ___ (meet) the President, I'd ask him lots of questions.", ["met"]),
   ("If you heat ice, it ___ (melt).", ["melts"]),
  ]),
 ],
 "test": [
  ("If I ___ rich, I'd buy a big house.", ["were", "am", "will be"]),
  ("I'd help you if I ___ time.", ["had", "have", "would have"]),
  ("If you ___ a million dollars, what would you do?", ["found", "find", "will find"]),
  ("If I were you, I ___ tell her.", ["would", "will", "am"]),
  ("He ___ be angry if he knew.", ["would", "will", "is"]),
  ("If we ___ a dog, I'd walk it every day.", ["had", "have", "would have"]),
  ("Would you live in another country if you ___?", ["could", "can", "will"]),
  ("If she ___ harder, she'd get better marks.", ["studied", "studies", "would study"]),
  ("I ___ go to bed so late if I were you.", ["wouldn't", "won't", "don't"]),
  ("What would you do if you ___ your passport?", ["lost", "lose", "will lose"]),
 ],
 "task": "What would you do if…? Write 8 sentences: if you won the lottery, if you could be invisible, if you were the president, if you could meet anyone…",
},
{
 "n": 33, "title": "Health and fitness",
 "words": [
  ("headache / stomach ache", "bosh og'rig'i / qorin og'rig'i", "I've got a headache."),
  ("sore throat", "tomoq og'rig'i", "Drink warm tea for a sore throat."),
  ("cold / cough", "shamollash / yo'tal", "I've got a cold and a bad cough."),
  ("temperature", "harorat, isitma", "She has a high temperature."),
  ("hurt", "og'rimoq", "My leg hurts."),
  ("medicine", "dori", "Take this medicine twice a day."),
  ("appointment", "(shifokor) qabuli", "I have an appointment at 3 pm."),
  ("ill / get better", "kasal / tuzalmoq", "I hope you get better soon."),
  ("healthy", "sog'lom", "Eat well to stay healthy."),
  ("fit", "baquvvat, sport formasida", "She runs every day to keep fit."),
  ("exercise", "jismoniy mashq", "Do some exercise every day."),
  ("gym", "sport zali", "I go to the gym three times a week."),
  ("diet", "ovqatlanish tartibi, parhez", "A healthy diet has lots of vegetables."),
  ("lose / put on weight", "vazn tashlamoq / vazn qo'shmoq", "He wants to lose weight."),
 ],
 "tip": "I've got a headache / a cold · My back hurts · keep fit · do exercise · go to the gym · eat a healthy diet · lose weight.",
 "ex": [
  ("Choose the correct word.", "mc", [
   ("I ate too much. Now I've got a ___.", ["stomach ache", "headache", "sore throat"]),
   ("My ___ hurts. I can't speak.", ["throat", "knee", "back"]),
   ("You buy medicine at a ___.", ["pharmacy", "bakery", "library"]),
   ("I have an ___ with the doctor at 3 pm.", ["appointment", "date", "reservation"]),
   ("She has a high ___. It's 39°C.", ["temperature", "pressure", "heat"]),
   ("I go running every day to keep ___.", ["fit", "healthy food", "well done"]),
  ]),
  ("Complete with a word from the box.", "gap", [
   ("I've got a ___ — my nose is running.", ["cold"]),
   ("Take this ___ three times a day.", ["medicine"]),
   ("My leg ___ when I walk.", ["hurts"]),
   ("I lift weights at the ___ after work.", ["gym"]),
   ("He has a bad ___ and can't stop coughing.", ["cough"]),
   ("Eat fruit and vegetables to stay ___.", ["healthy"]),
  ], ["cold", "medicine", "hurts", "gym", "cough", "healthy"]),
  ("Complete the phrases.", "gap", [
   ("___ to the gym", ["go"]),
   ("___ exercise", ["do", "take"]),
   ("___ weight (= become thinner)", ["lose"]),
   ("___ a healthy diet", ["eat", "have", "follow"]),
   ("___ fit", ["keep", "stay", "get"]),
   ("___ a rest", ["have", "take"]),
  ]),
 ],
 "test": [
  ("I've got a ___. My head hurts.", ["headache", "stomach ache", "toothache"]),
  ("Go to the ___ if you have toothache.", ["dentist", "pharmacy", "vet"]),
  ("You should ___ exercise every day.", ["do", "make", "play"]),
  ("She ___ her arm playing basketball.", ["broke", "cut down", "hit up"]),
  ("You should ___ more water.", ["drink", "eat", "hurt"]),
  ("Get ___ soon!", ["well", "good", "fine"]),
  ("My back ___.", ["hurts", "ill", "sore"]),
  ("I feel ___. I think I have a fever.", ["ill", "good", "healthy"]),
  ("I go to the ___ three times a week to keep fit.", ["gym", "pharmacy", "dentist"]),
  ("He's on a ___ because he wants to lose weight.", ["diet", "medicine", "gym"]),
 ],
 "task": "A friend wants to get fit and healthy. Write 8 pieces of advice with should / shouldn't (food, sleep, exercise, the gym…).",
},
{
 "n": 34, "title": "so and such, either and neither",
 "lesson": [
  ("so and such", [
   "<b>so</b> + adjective / adverb: It's <b>so</b> cold! He drives <b>so</b> fast.",
   "<b>such</b> + (a / an) + adjective + noun: It's <b>such a</b> nice day! They are <b>such</b> good friends. It's <b>such</b> lovely weather.",
   "Result with <b>that</b>: The film was <b>so</b> boring <b>that</b> I fell asleep. It was <b>such a</b> boring film <b>that</b> I fell asleep.",
   "UZ: so – sifat/ravishdan oldin; such (a) – sifat + otdan oldin. Ikkalasi ham \"shunchalik\" ma'nosini beradi."]),
  ("Agreeing: so, neither, too, either", [
   "Positive → <b>So</b> + auxiliary + I: \"I love pizza.\" \"<b>So do I</b>.\" \"I'm tired.\" \"<b>So am I</b>.\" \"I can swim.\" \"<b>So can I</b>.\"",
   "Negative → <b>Neither</b> + auxiliary + I: \"I don't eat meat.\" \"<b>Neither do I</b>.\" \"I haven't seen it.\" \"<b>Neither have I</b>.\"",
   "Informal: Me too. / Me neither.",
   "<b>too</b> in positive sentences, <b>either</b> in negative sentences: I like it <b>too</b>. I don't like it <b>either</b>.",
   "UZ: Rozilik bildirish: So do I (men ham), Neither do I (men ham ... emas). Yordamchi fe'l gapdagi zamonga mos bo'ladi."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("It's ___ hot today!", ["so", "such", "such a"]),
   ("She's ___ nice girl.", ["such a", "so", "such"]),
   ("They are ___ good friends.", ["such", "so", "such a"]),
   ("\"I love pizza.\" \"___ do I.\"", ["So", "Neither", "Either"]),
   ("\"I can't swim.\" \"___ can I.\"", ["Neither", "So", "Either"]),
   ("I don't like horror films ___.", ["either", "too", "neither"]),
  ]),
  ("Complete with so, such or such a.", "gap", [
   ("The film was ___ boring that I fell asleep.", ["so"]),
   ("It was ___ boring film that I fell asleep.", ["such a"]),
   ("They have ___ beautiful children.", ["such"]),
   ("Why are you walking ___ slowly?", ["so"]),
   ("It's ___ lovely weather today!", ["such"]),
   ("He's ___ funny person.", ["such a"]),
  ]),
  ("Agree with the speaker. Write So / Neither + auxiliary + I.", "gap", [
   ("\"I'm hungry.\" \"___.\"", ["So am I"]),
   ("\"I don't eat meat.\" \"___.\"", ["Neither do I"]),
   ("\"I went to the party.\" \"___.\"", ["So did I"]),
   ("\"I haven't seen that film.\" \"___.\"", ["Neither have I"]),
   ("\"I can speak Russian.\" \"___.\"", ["So can I"]),
   ("\"I wasn't at school yesterday.\" \"___.\"", ["Neither was I"]),
  ]),
 ],
 "test": [
  ("The exam was ___ difficult!", ["so", "such", "such a"]),
  ("It was ___ difficult exam!", ["such a", "so", "such"]),
  ("\"I like tea.\" \"So ___ I.\"", ["do", "am", "like"]),
  ("\"I'm not tired.\" \"Neither ___ I.\"", ["am", "do", "have"]),
  ("\"I didn't go.\" \"I didn't go ___.\"", ["either", "too", "neither"]),
  ("\"She can dance.\" \"So ___ her sister.\"", ["can", "does", "is"]),
  ("It's ___ a long way to walk.", ["such", "so", "too"]),
  ("The music was ___ loud that we couldn't talk.", ["so", "such", "such a"]),
  ("\"I've never been to London.\" \"Neither ___ I.\"", ["have", "do", "am"]),
  ("\"I love this song!\" \"Me ___!\"", ["too", "either", "neither"]),
 ],
 "task": "Write 6 true sentences about yourself (I like…, I don't…, I can…, I've never…). Read them to a partner, who answers with So do I / Neither do I etc. Then write 4 sentences with so … that and such … that.",
},
{
 "n": 35, "title": "Question tags",
 "lesson": [
  ("Form", [
   "A question tag is a short question at the end of a sentence: You're Aziz, <b>aren't you</b>?",
   "Positive sentence → negative tag: She's a teacher, <b>isn't she</b>? · Negative sentence → positive tag: She isn't here, <b>is she</b>?",
   "Use the auxiliary from the sentence: You <b>can</b> swim, <b>can't</b> you? They <b>have</b> finished, <b>haven't</b> they? He <b>will</b> come, <b>won't</b> he?",
   "No auxiliary (present / past simple) → do / does / did: You <b>like</b> tea, <b>don't</b> you? She <b>lives</b> here, <b>doesn't</b> she? They <b>went</b> home, <b>didn't</b> they?",
   "Special: I'm right, <b>aren't I</b>? · Let's go, <b>shall we</b>?",
   "UZ: Tasdiq so'rash uchun gap oxiridagi qisqa savol: darak gap → inkor tag, inkor gap → darak tag."]),
  ("Use", [
   "To check information we think is true (falling intonation) or to ask a real question (rising intonation)."]),
 ],
 "ex": [
  ("Choose the correct question tag.", "mc", [
   ("You're a student, ___?", ["aren't you", "are you", "don't you"]),
   ("She doesn't eat meat, ___?", ["does she", "doesn't she", "is she"]),
   ("They went home, ___?", ["didn't they", "don't they", "did they"]),
   ("He can swim, ___?", ["can't he", "can he", "doesn't he"]),
   ("It isn't cold, ___?", ["is it", "isn't it", "does it"]),
   ("You've finished, ___?", ["haven't you", "have you", "didn't you"]),
  ]),
  ("Write the question tag.", "gap", [
   ("Your brother lives in Tashkent, ___?", ["doesn't he"]),
   ("We aren't late, ___?", ["are we"]),
   ("You will help me, ___?", ["won't you"]),
   ("She was at the party, ___?", ["wasn't she"]),
   ("They haven't met, ___?", ["have they"]),
   ("Let's go to the cinema, ___?", ["shall we"]),
  ]),
  ("Write the question tag.", "gap", [
   ("I'm right, ___?", ["aren't I"]),
   ("You don't like coffee, ___?", ["do you"]),
   ("Ali plays football, ___?", ["doesn't he"]),
   ("It was a great film, ___?", ["wasn't it"]),
   ("You can't drive, ___?", ["can you"]),
  ]),
 ],
 "test": [
  ("It's a nice day, ___?", ["isn't it", "is it", "doesn't it"]),
  ("You like pizza, ___?", ["don't you", "do you", "aren't you"]),
  ("She won't come, ___?", ["will she", "won't she", "does she"]),
  ("They were at home, ___?", ["weren't they", "were they", "didn't they"]),
  ("He hasn't called, ___?", ["has he", "hasn't he", "did he"]),
  ("You saw that film, ___?", ["didn't you", "did you", "haven't you"]),
  ("I'm late, ___?", ["aren't I", "amn't I", "don't I"]),
  ("We should go, ___?", ["shouldn't we", "should we", "don't we"]),
  ("Your sister can't swim, ___?", ["can she", "can't she", "does she"]),
  ("Let's start, ___?", ["shall we", "do we", "don't we"]),
 ],
 "task": "Write 8 sentences with question tags about a classmate that you think are true (You live near the school, don't you? You can't swim, can you?). Then ask them and check.",
},
{
 "n": 36, "title": "Technology",
 "words": [
  ("laptop", "noutbuk", "I do my homework on my laptop."),
  ("screen", "ekran", "The screen on my phone is broken."),
  ("keyboard", "klaviatura", "Type your name on the keyboard."),
  ("charger", "quvvatlagich (zaryadka)", "Have you got a phone charger?"),
  ("battery", "batareya", "My battery is almost dead."),
  ("password", "parol", "Never share your password."),
  ("website", "veb-sayt", "This website is very useful."),
  ("app", "ilova", "I use an app to learn English."),
  ("download / upload", "yuklab olmoq / yuklamoq (internetga)", "Download the file to your computer."),
  ("search", "qidirmoq", "Search for the answer online."),
  ("post / share", "joylashtirmoq / ulashmoq", "She posted a photo and shared it with friends."),
  ("online", "onlayn, internetda", "I buy books online."),
  ("subscribe", "obuna bo'lmoq", "Subscribe to our channel!"),
  ("message", "xabar", "Send me a message."),
 ],
 "tip": "download = from the internet to your device · upload = from your device to the internet.",
 "ex": [
  ("Choose the correct word.", "mc", [
   ("You type on a ___.", ["keyboard", "screen", "charger"]),
   ("My phone's ___ is dead. I need to charge it.", ["battery", "screen", "app"]),
   ("Never tell anyone your ___.", ["password", "website", "laptop"]),
   ("I ___ a photo on Instagram yesterday.", ["posted", "downloaded", "typed"]),
   ("Can you ___ me the link?", ["send", "search", "upload"]),
   ("I ___ the app from the store.", ["downloaded", "uploaded", "searched"]),
  ]),
  ("Complete with a word from the box.", "gap", [
   ("I forgot my ___, so my phone is at 5%.", ["charger"]),
   ("___ for the answer on the internet.", ["Search"]),
   ("The ___ on my phone is broken. I can't see anything.", ["screen"]),
   ("Do you buy clothes ___?", ["online"]),
   ("___ to our channel for new videos every week!", ["Subscribe"]),
   ("Please ___ this post with your friends.", ["share"]),
  ], ["charger", "search", "screen", "online", "subscribe", "share"]),
  ("Complete the verb + noun phrases.", "gap", [
   ("___ a message", ["send", "write", "read"]),
   ("___ your phone (when the battery is low)", ["charge"]),
   ("___ a password", ["enter", "type", "change"]),
   ("___ a website", ["visit", "open"]),
   ("___ a video", ["watch", "upload", "download", "post"]),
   ("___ a file", ["download", "save", "open", "upload"]),
  ]),
 ],
 "test": [
  ("I read the ___ on a website every morning.", ["news", "new", "newses"]),
  ("You can make video calls with this ___.", ["app", "battery", "charger"]),
  ("My laptop is ___ — it isn't working.", ["broken", "break", "breaking"]),
  ("___ your photos with your family.", ["Share", "Search", "Charge"]),
  ("This ___ has lots of useful information.", ["website", "keyboard", "battery"]),
  ("Is the Wi-Fi working? I can't go ___.", ["online", "inline", "on"]),
  ("It takes a long time to ___ big videos to the internet.", ["upload", "download", "search"]),
  ("You need a ___ to log in.", ["password", "keyboard", "screen"]),
  ("I ___ a message to my friend.", ["sent", "charged", "searched"]),
  ("Turn off your phone and ___ some time offline.", ["spend", "give", "take"]),
 ],
 "task": "Write 8–10 sentences: How do you use technology every day? What are the good and bad things about phones for students?",
},
{
 "n": 37, "title": "Relative pronouns and relative clauses",
 "lesson": [
  ("Relative pronouns", [
   "<b>who</b> (or that) for people: The man <b>who</b> lives next door is a doctor.",
   "<b>which</b> (or that) for things and animals: The phone <b>which</b> I bought is great.",
   "<b>where</b> for places: That's the restaurant <b>where</b> we had dinner.",
   "<b>whose</b> for possession: I have a friend <b>whose</b> father is a pilot.",
   "UZ: who – odamlar uchun; which – narsa va hayvonlar; that – ikkalasi uchun; where – joy; whose – egalik (kimningdir)."]),
  ("Relative clauses", [
   "A relative clause tells us which person or thing we mean: The girl <b>who won the race</b> is my sister.",
   "Don't repeat the pronoun: ✔ The book which I read ✘ The book which I read it",
   "Useful for definitions: A chef is a person <b>who</b> cooks in a restaurant. A library is a place <b>where</b> you borrow books."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("The man ___ lives next door is a doctor.", ["who", "which", "where"]),
   ("This is the book ___ I told you about.", ["that", "who", "where"]),
   ("That's the restaurant ___ we had dinner.", ["where", "which", "who"]),
   ("I have a friend ___ father is a pilot.", ["whose", "who", "who's"]),
   ("The phone ___ I bought is great.", ["which", "who", "where"]),
   ("A dentist is a person ___ looks after your teeth.", ["who", "which", "where"]),
  ]),
  ("Complete with who, which, where or whose.", "gap", [
   ("The girl ___ won the race is my sister.", ["who", "that"]),
   ("This is the house ___ I was born.", ["where"]),
   ("The cake ___ you made was delicious.", ["which", "that"]),
   ("That's the boy ___ bike was stolen.", ["whose"]),
   ("Samarkand is a city ___ many tourists visit.", ["which", "that"]),
   ("Do you know a shop ___ I can buy a charger?", ["where"]),
  ]),
  ("Complete the definitions.", "gap", [
   ("A chef is a person ___ cooks in a restaurant.", ["who", "that"]),
   ("A library is a place ___ you can borrow books.", ["where"]),
   ("A fridge is a machine ___ keeps food cold.", ["which", "that"]),
   ("An orphan is a child ___ parents are dead.", ["whose"]),
   ("A museum is a building ___ you can see old things.", ["where"]),
  ]),
 ],
 "test": [
  ("The teacher ___ teaches us maths is very kind.", ["who", "which", "whose"]),
  ("This is the car ___ my dad bought.", ["which", "who", "where"]),
  ("The hotel ___ we stayed was lovely.", ["where", "which", "who"]),
  ("I met a woman ___ son plays for Barcelona.", ["whose", "who", "which"]),
  ("The film ___ we watched was boring.", ["that", "who", "where"]),
  ("Is that the man ___ helped you?", ["who", "which", "whose"]),
  ("The town ___ I grew up is very small.", ["where", "which", "who"]),
  ("Pizza is a food ___ everybody likes.", ["which", "who", "where"]),
  ("He's the boy ___ sister is in my class.", ["whose", "who", "who's"]),
  ("The people ___ live upstairs are very noisy.", ["who", "which", "where"]),
 ],
 "task": "Write 8 definitions for words from this book using who, which, where and whose (A teacher is a person who…, A stadium is a place where…).",
},
{
 "n": 38, "title": "Past perfect",
 "lesson": [
  ("Form", [
   "had + past participle (for all persons)",
   "I <b>had ('d) finished</b> · She <b>hadn't seen</b> it · <b>Had</b> you <b>eaten</b>…? — Yes, I had. / No, I hadn't.",
   "UZ: had + fe'lning 3-shakli. O'tmishdagi boshqa harakatdan oldin sodir bo'lgan harakat."]),
  ("Use", [
   "The past perfect shows that one past action happened <b>before</b> another past action.",
   "When we arrived, the film <b>had</b> already <b>started</b>. (First the film started, then we arrived.)",
   "Compare: When I arrived, Tom <b>left</b>. (I arrived, then he left.) · When I arrived, Tom <b>had left</b>. (He left before I arrived.)",
   "Common words: already, never … before, by the time, after, before, because",
   "She was tired because she <b>had worked</b> all day. · By the time we got there, everyone <b>had gone</b> home."]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("When we arrived, the film ___ started.", ["had already", "has already", "already"]),
   ("She ___ never seen snow before she went to Moscow.", ["had", "has", "was"]),
   ("After he ___ his homework, he went out.", ["had finished", "has finished", "finishes"]),
   ("I couldn't get in because I ___ my keys.", ["had lost", "have lost", "lose"]),
   ("The train ___ when we got to the station.", ["had left", "has left", "leaves"]),
   ("___ you eaten before you came?", ["Had", "Have", "Did"]),
  ]),
  ("Put the verb in brackets in the past perfect.", "gap", [
   ("When I got home, my mum ___ (cook) dinner.", ["had cooked", "'d cooked"]),
   ("They ___ (not / meet) before the party.", ["hadn't met", "had not met"]),
   ("She was tired because she ___ (work) all day.", ["had worked", "'d worked"]),
   ("By the time we arrived, everyone ___ (go) home.", ["had gone", "'d gone"]),
   ("I ___ (never / fly) before that trip.", ["had never flown", "'d never flown"]),
   ("___ (he / see) the film before?", ["Had he seen"]),
  ]),
  ("Past simple or past perfect? Put the verb in the correct form.", "gap", [
   ("When I arrived, Tom ___ (leave). He wasn't there.", ["had left", "'d left"]),
   ("When I arrived, Tom ___ (leave). We said goodbye at the door.", ["left"]),
   ("After she ___ (read) the letter, she started to cry.", ["had read", "'d read", "read"]),
   ("We ___ (go) to bed after the film ended.", ["went"]),
   ("He didn't want to see the film because he ___ (see) it before.", ["had seen", "'d seen"]),
  ]),
 ],
 "test": [
  ("I ___ breakfast when she called, so I wasn't hungry.", ["had already had", "have already had", "already have"]),
  ("When the police arrived, the thief ___ away.", ["had run", "has run", "runs"]),
  ("She told me she ___ her job.", ["had lost", "has lose", "loses"]),
  ("They ___ never been abroad before 2020.", ["had", "have", "were"]),
  ("We were late. The lesson ___ started.", ["had already", "has already", "already has"]),
  ("After I ___ my exams, I went on holiday.", ["had passed", "have passed", "pass"]),
  ("Had you ever ___ plov before you came here?", ["eaten", "ate", "eat"]),
  ("He was hungry because he ___ eaten all day.", ["hadn't", "hasn't", "didn't"]),
  ("By the time I got to the shop, it ___.", ["had closed", "has closed", "closes"]),
  ("I recognised her because I ___ her before.", ["had met", "have met", "meet"]),
 ],
 "task": "Write a short story (8 sentences) about a bad day: By the time I got to school, the lesson had already started… Use the past perfect at least 5 times.",
},
{
 "n": 39, "title": "Nature",
 "words": [
  ("sunny / cloudy", "quyoshli / bulutli", "It's sunny today."),
  ("windy / rainy", "shamolli / yomg'irli", "Take an umbrella, it's rainy."),
  ("foggy / snowy", "tumanli / qorli", "It's foggy this morning."),
  ("storm", "bo'ron", "There was a big storm last night."),
  ("degrees", "daraja", "It's 35 degrees today!"),
  ("freezing", "juda sovuq", "It's freezing outside."),
  ("forecast", "ob-havo ma'lumoti", "The forecast says it will rain."),
  ("mountain / hill", "tog' / tepalik", "We climbed a hill near the village."),
  ("river / lake", "daryo / ko'l", "We swam in the lake."),
  ("forest", "o'rmon", "Many animals live in the forest."),
  ("desert", "cho'l", "The Kyzylkum is a desert."),
  ("field", "dala", "Cows are eating grass in the field."),
  ("island / coast", "orol / qirg'oq", "An island has water all around it."),
  ("wild animals / plants", "yovvoyi hayvonlar / o'simliklar", "Wild animals live in the mountains."),
 ],
 "tip": "noun + -y = adjective: sun → sunny, cloud → cloudy, wind → windy, rain → rainy, fog → foggy, snow → snowy.",
 "ex": [
  ("Choose the correct word.", "mc", [
   ("There are a lot of trees in a ___.", ["forest", "desert", "lake"]),
   ("A very hot, dry place with sand is a ___.", ["desert", "field", "coast"]),
   ("Take an umbrella. It's ___.", ["rainy", "sunny", "dry"]),
   ("I can't see anything. It's very ___.", ["foggy", "sunny", "windy"]),
   ("Land with water all around it is an ___.", ["island", "hill", "river"]),
   ("The weather ___ says it will snow tomorrow.", ["forecast", "program", "paper"]),
  ]),
  ("Complete with a word from the box.", "gap", [
   ("It's 35 ___ today. Very hot!", ["degrees"]),
   ("The sky is grey and ___.", ["cloudy"]),
   ("Hold your hat — it's very ___!", ["windy"]),
   ("There was a big ___ with thunder and lightning.", ["storm"]),
   ("We went swimming in the ___.", ["lake"]),
   ("The Tian Shan ___ are beautiful in spring.", ["mountains"]),
  ], ["degrees", "cloudy", "windy", "storm", "lake", "mountains"]),
  ("Make adjectives from the nouns.", "gap", [
   ("sun → ___", ["sunny"]),
   ("cloud → ___", ["cloudy"]),
   ("wind → ___", ["windy"]),
   ("rain → ___", ["rainy"]),
   ("fog → ___", ["foggy"]),
   ("snow → ___", ["snowy"]),
  ]),
 ],
 "test": [
  ("It's ___ today — let's go to the beach.", ["sunny", "snowy", "foggy"]),
  ("The ___ flows through the city.", ["river", "lake", "hill"]),
  ("Wear a coat. It's ___ outside.", ["cold", "hot", "warm"]),
  ("The Kyzylkum is a ___.", ["desert", "forest", "island"]),
  ("What's the ___ like today?", ["weather", "whether", "forecast"]),
  ("The temperature is below zero; it's ___.", ["freezing", "boiling", "warm"]),
  ("We climbed to the top of the ___.", ["hill", "lake", "river"]),
  ("Cows are eating grass in the ___.", ["field", "sea", "desert"]),
  ("There was a ___ last night. Some trees fell down.", ["storm", "fog", "sun"]),
  ("Tomorrow it will ___ in the mountains.", ["snow", "snowy", "snowing"]),
 ],
 "task": "Write a weather forecast for your city for the next three days, then describe your favourite place in nature (8–10 sentences).",
},
{
 "n": 40, "title": "Reported speech",
 "lesson": [
  ("Say and tell", [
   "<b>say</b> (something): He <b>said</b> (that) he was tired.",
   "<b>tell</b> + person: He <b>told me</b> (that) he was tired. ✘ He said me",
   "UZ: say – \"aytmoq\" (kimgaligi aytilmaydi); tell – kimgadir aytmoq (tell me, tell her)."]),
  ("Tense changes", [
   "When the reporting verb is in the past, the tense usually moves back:",
   "present simple → past simple: \"I <b>like</b> pizza.\" → He said he <b>liked</b> pizza.",
   "present continuous → past continuous: \"I'm <b>watching</b> TV.\" → She said she <b>was watching</b> TV.",
   "past simple / present perfect → past perfect: \"I <b>have finished</b>.\" → He said he <b>had finished</b>.",
   "will → would · can → could: \"I <b>will</b> call.\" → He said he <b>would</b> call.",
   "UZ: O'zlashtirma gapda zamon bir pog'ona orqaga suriladi."]),
  ("Other changes", [
   "Pronouns: \"<b>I</b> love <b>my</b> job.\" → She said <b>she</b> loved <b>her</b> job.",
   "Time and place: today → that day · tomorrow → the next day · yesterday → the day before · here → there · now → then"]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("She ___ me that she was tired.", ["told", "said", "says"]),
   ("He ___ that he liked pizza.", ["said", "told", "tell"]),
   ("\"I am happy.\" → She said she ___ happy.", ["was", "is", "were"]),
   ("\"I will call you.\" → He said he ___ call me.", ["would", "will", "can"]),
   ("\"I can swim.\" → She said she ___ swim.", ["could", "can", "would"]),
   ("\"We live in Tashkent.\" → They said they ___ in Tashkent.", ["lived", "live", "living"]),
  ]),
  ("Report the sentences.", "gap", [
   ("\"I like chocolate.\" → Aziz said that he ___ chocolate.", ["liked"]),
   ("\"I'm watching TV.\" → She said she ___ TV.", ["was watching"]),
   ("\"We will be late.\" → They said they ___ late.", ["would be"]),
   ("\"I can't come.\" → He said he ___ come.", ["couldn't", "could not"]),
   ("\"I don't know.\" → She said she ___ know.", ["didn't", "did not"]),
   ("\"I have finished.\" → He said he ___ finished.", ["had"]),
  ]),
  ("Complete with said or told.", "gap", [
   ("She ___ me a funny story.", ["told"]),
   ("He ___, \"Good morning!\"", ["said"]),
   ("They ___ that they were busy.", ["said"]),
   ("I ___ her to be careful.", ["told"]),
   ("My teacher ___ us that the test was easy.", ["told"]),
  ]),
 ],
 "test": [
  ("He said he ___ tired.", ["was", "is", "be"]),
  ("She ___ us that she was leaving.", ["told", "said", "spoke"]),
  ("\"I'll help.\" → He said he ___ help.", ["would", "will", "can"]),
  ("\"I'm going home.\" → She said she ___ going home.", ["was", "is", "were"]),
  ("They said they ___ like the film.", ["didn't", "don't", "doesn't"]),
  ("\"I can drive.\" → He said he ___ drive.", ["could", "can", "cans"]),
  ("\"I bought a dress yesterday.\" → She said she ___ a dress the day before.", ["had bought", "has bought", "buys"]),
  ("\"It's cold today.\" → He said it was cold ___.", ["that day", "today", "tomorrow"]),
  ("He told ___ he was ill.", ["me", "to me", "for me"]),
  ("\"We live here.\" → They said they lived ___.", ["there", "here", "where"]),
 ],
 "task": "Ask a classmate 5 questions (What's your favourite food? What will you do this weekend? …). Then report their answers: She said that…, He told me that…",
},
{
 "n": 41, "title": "Tenses: revision",
 "lesson": [
  ("Present tenses", [
   "Present simple — habits, facts, timetables: She <b>works</b> in a bank. The bus <b>leaves</b> at 8.",
   "Present continuous — now, temporary, arrangements: I<b>'m reading</b>. We<b>'re meeting</b> at 6.",
   "Present perfect — experience, result, up to now: I<b>'ve been</b> to Samarkand. I<b>'ve lived</b> here for 5 years."]),
  ("Past tenses", [
   "Past simple — finished action, known time: I <b>went</b> there <b>last year</b>.",
   "Past continuous — action in progress in the past: I <b>was cooking</b> when he called.",
   "Past perfect — the earlier of two past actions: When I arrived, they <b>had left</b>."]),
  ("Future", [
   "will — predictions, instant decisions, promises: I think it<b>'ll</b> rain. I<b>'ll</b> help you.",
   "be going to — plans, evidence: I<b>'m going to</b> study law. Look — it<b>'s going to</b> fall!",
   "UZ: Zamonni tanlashda vaqt so'zlariga e'tibor bering: now, usually, yesterday, ago, since, already, tomorrow, by the time…"]),
 ],
 "ex": [
  ("Choose the correct answer.", "mc", [
   ("I ___ to school every day.", ["go", "am going", "went"]),
   ("Look! It ___.", ["is snowing", "snows", "snowed"]),
   ("We ___ the film last night.", ["watched", "have watched", "watch"]),
   ("I ___ in this city since 2015.", ["have lived", "live", "lived"]),
   ("While I ___ dinner, the phone rang.", ["was cooking", "cooked", "am cooking"]),
   ("Look at those clouds! It ___ rain.", ["is going to", "will", "rains"]),
  ]),
  ("Put the verb in brackets in the correct tense.", "gap", [
   ("My dad usually ___ (drive) to work.", ["drives"]),
   ("At the moment she ___ (read) a book.", ["is reading", "'s reading"]),
   ("Last summer we ___ (go) to Khiva.", ["went"]),
   ("___ (you / ever / be) to Moscow?", ["Have you ever been"]),
   ("When I arrived, they ___ (already / eat).", ["had already eaten", "'d already eaten"]),
   ("I think it ___ (be) sunny tomorrow.", ["will be", "'ll be"]),
  ]),
  ("Complete with a time word: yet, just, ago, at, usually.", "gap", [
   ("I haven't finished my homework ___.", ["yet"]),
   ("He went to London two years ___.", ["ago"]),
   ("I'm studying for a test ___ the moment.", ["at"]),
   ("We ___ go to the cinema on Fridays.", ["usually", "often", "always", "sometimes"]),
   ("She has ___ left — you missed her by one minute!", ["just"]),
  ]),
 ],
 "test": [
  ("She ___ English very well.", ["speaks", "is speaking", "speak"]),
  ("They ___ football when it started to rain.", ["were playing", "played", "are playing"]),
  ("I ___ my wallet! I can't find it anywhere.", ["have lost", "had lost", "am losing"]),
  ("He ___ to Paris next week. It's all arranged.", ["is flying", "flew", "has flown"]),
  ("When did you ___ here?", ["arrive", "arrived", "arriving"]),
  ("We ___ each other for ten years.", ["have known", "know", "are knowing"]),
  ("By the time we arrived, the concert ___.", ["had started", "has started", "starts"]),
  ("I'm tired. I think I ___ to bed.", ["'ll go", "went", "had gone"]),
  ("What ___ you doing at 8 last night?", ["were", "did", "are"]),
  ("She ___ tea every morning.", ["drinks", "is drinking", "drunk"]),
 ],
 "task": "Write about your past, present and future (10 sentences): Last year I…, When I was a child I was…ing when…, Now I…, I've already…, Next year I'm going to…, I think I will…",
},
{
 "n": 42, "title": "Global problems",
 "words": [
  ("pollution", "ifloslanish", "Air pollution is a big problem in cities."),
  ("climate change", "iqlim o'zgarishi", "Climate change is making summers hotter."),
  ("global warming", "global isish", "Global warming is melting the ice."),
  ("environment", "atrof-muhit", "Plastic is bad for the environment."),
  ("rubbish", "axlat", "Don't throw rubbish on the street."),
  ("recycle", "qayta ishlamoq", "We recycle paper and glass."),
  ("save energy", "energiyani tejamoq", "Turn off the lights to save energy."),
  ("protect", "himoya qilmoq", "We must protect forests."),
  ("endangered", "yo'qolib ketish xavfi ostidagi", "Snow leopards are endangered animals."),
  ("poverty", "qashshoqlik", "Many people live in poverty."),
  ("hunger", "ochlik", "Hunger is a problem in some countries."),
  ("war", "urush", "Millions of people left their homes because of the war."),
  ("disease", "kasallik", "Clean water stops many diseases."),
  ("flood / drought / earthquake", "toshqin / qurg'oqchilik / zilzila", "The earthquake destroyed many buildings."),
 ],
 "tip": "Word formation: pollute → pollution, protect → protection, poor → poverty, hungry → hunger, danger → dangerous.",
 "ex": [
  ("Choose the correct word.", "mc", [
   ("Cars and factories cause air ___.", ["pollution", "poverty", "disease"]),
   ("Too much rain can cause a ___.", ["flood", "drought", "earthquake"]),
   ("No rain for a long time causes a ___.", ["drought", "flood", "storm"]),
   ("Put bottles in this bin so we can ___ them.", ["recycle", "pollute", "waste"]),
   ("Snow leopards are an ___ animal.", ["endangered", "dangerous", "empty"]),
   ("Many people in the world don't have enough food. They suffer from ___.", ["hunger", "war", "pollution"]),
  ]),
  ("Complete with a word or phrase from the box.", "gap", [
   ("Don't throw ___ on the street.", ["rubbish"]),
   ("Turn off the lights to ___ energy.", ["save"]),
   ("We must ___ forests and animals.", ["protect"]),
   ("___ is making summers hotter.", ["Climate change"]),
   ("Plastic is bad for the ___.", ["environment"]),
   ("Millions of people left their homes because of the ___.", ["war"]),
  ], ["rubbish", "save", "protect", "climate change", "environment", "war"]),
  ("Word formation: write the word.", "gap", [
   ("pollute → noun: ___", ["pollution"]),
   ("protect → noun: ___", ["protection"]),
   ("poor → noun: ___", ["poverty"]),
   ("hungry → noun: ___", ["hunger"]),
   ("danger → adjective: ___", ["dangerous"]),
   ("warm → noun: ___", ["warming", "warmth"]),
  ]),
 ],
 "test": [
  ("The ___ in big cities is very bad for people's health.", ["pollution", "poverty", "hunger"]),
  ("A strong ___ destroyed many buildings in the city.", ["earthquake", "drought", "recycling"]),
  ("We should use less ___ — it stays in the sea for hundreds of years.", ["plastic", "water", "energy"]),
  ("Tigers are ___ because people hunt them.", ["endangered", "dangerous", "polluted"]),
  ("Many children in poor countries die of ___.", ["disease", "environment", "recycling"]),
  ("We must ___ the planet for future generations.", ["protect", "pollute", "waste"]),
  ("Global ___ is making the ice melt.", ["warming", "warm", "warmer"]),
  ("___ is a big problem: many people have no money.", ["Poverty", "Pollution", "Flood"]),
  ("Please ___ paper and glass.", ["recycle", "rubbish", "protect"]),
  ("Save ___ — switch off your computer.", ["energy", "rubbish", "pollution"]),
 ],
 "task": "Write about one global problem (8–10 sentences): What is the problem? Why is it happening? What can we do? Use should, must and if.",
},
]
